// ═══════════════════════════════════════════════════════════════════
// TOOL REGISTRY — Every tool available to roles in Viewdicon
// Extracted from all 600 roles across 20 villages. Each tool has a
// key, name, icon, description, category, business-session flag,
// and Cowrie flow direction.
// ═══════════════════════════════════════════════════════════════════

import { getRoleByKey } from './role-registry'

// ── Types ────────────────────────────────────────────────────────

export interface ToolDefinition {
  key: string
  name: string
  icon: string // emoji fallback
  iconComponent?: string // key for afro-icons component
  description: string
  category:
    | 'commerce'
    | 'communication'
    | 'finance'
    | 'logistics'
    | 'professional'
    | 'community'
    | 'health'
    | 'agriculture'
    | 'education'
    | 'media'
    | 'creative'
    | 'government'
    | 'security'
    | 'energy'
    | 'sports'
  opensBusinessSession: boolean
  cowrieFlow: 'earns' | 'spends' | 'neutral'
}

// ── Master Registry ──────────────────────────────────────────────

export const TOOL_REGISTRY: Record<string, ToolDefinition> = {

  // ╔═══════════════════════════════════════════════════════════════╗
  // ║  COMMERCE TOOLS                                              ║
  // ╚═══════════════════════════════════════════════════════════════╝

  quick_invoice: {
    key: 'quick_invoice',
    name: 'Quick Invoice',
    icon: '📋',
    iconComponent: 'KowrieIcon',
    description: 'Generate a professional invoice in 30 seconds',
    category: 'commerce',
    opensBusinessSession: true,
    cowrieFlow: 'earns',
  },
  price_checker: {
    key: 'price_checker',
    name: 'Market Price Checker',
    icon: '💰',
    description: 'Live prices for 500+ common goods across African markets',
    category: 'commerce',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  inventory_tracker: {
    key: 'inventory_tracker',
    name: 'Inventory Tracker',
    icon: '📦',
    description: 'Track your stock levels with low-stock alerts',
    category: 'commerce',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  daily_menu_board: {
    key: 'daily_menu_board',
    name: 'Daily Menu Board',
    icon: '🍽',
    description: "Display today's menu with prices to customers",
    category: 'commerce',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  daily_target_tracker: {
    key: 'daily_target_tracker',
    name: 'Daily Target Tracker',
    icon: '🎯',
    description: 'Set and track daily sales targets',
    category: 'commerce',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  daily_rate_display: {
    key: 'daily_rate_display',
    name: 'Daily Rate Display',
    icon: '💲',
    description: 'Show your daily rate for services',
    category: 'commerce',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  social_shop: {
    key: 'social_shop',
    name: 'Social Shop',
    icon: '🛍',
    description: 'Create a social commerce storefront',
    category: 'commerce',
    opensBusinessSession: false,
    cowrieFlow: 'earns',
  },
  product_listing: {
    key: 'product_listing',
    name: 'Product Listing',
    icon: '📝',
    description: 'List products with photos and prices',
    category: 'commerce',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  order_dashboard: {
    key: 'order_dashboard',
    name: 'Order Dashboard',
    icon: '📊',
    description: 'Manage incoming orders from all channels',
    category: 'commerce',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  stock_tracker: {
    key: 'stock_tracker',
    name: 'Stock Tracker',
    icon: '📈',
    description: 'Track stock levels and reorder points',
    category: 'commerce',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  bulk_order_manager: {
    key: 'bulk_order_manager',
    name: 'Bulk Order Manager',
    icon: '📋',
    description: 'Manage large wholesale orders',
    category: 'commerce',
    opensBusinessSession: true,
    cowrieFlow: 'earns',
  },
  sales_target_tracker: {
    key: 'sales_target_tracker',
    name: 'Sales Target Tracker',
    icon: '📊',
    description: 'Track monthly sales targets',
    category: 'commerce',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  weight_calculator: {
    key: 'weight_calculator',
    name: 'Weight Calculator',
    icon: '⚖️',
    description: 'Calculate weight and convert units',
    category: 'commerce',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  invoice_scanner: {
    key: 'invoice_scanner',
    name: 'Invoice Scanner',
    icon: '📄',
    description: 'Scan and digitise paper invoices',
    category: 'commerce',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  invoice_generator: {
    key: 'invoice_generator',
    name: 'Invoice Generator',
    icon: '🧾',
    description: 'Generate formal invoices with line items',
    category: 'commerce',
    opensBusinessSession: true,
    cowrieFlow: 'earns',
  },
  rate_calculator: {
    key: 'rate_calculator',
    name: 'Rate Calculator',
    icon: '🧮',
    description: 'Calculate shipping and service rates',
    category: 'commerce',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  warranty_note: {
    key: 'warranty_note',
    name: 'Warranty Note',
    icon: '📜',
    description: 'Issue warranty certificates for products',
    category: 'commerce',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  live_auction: {
    key: 'live_auction',
    name: 'Live Auction',
    icon: '🔨',
    description: 'Run live auctions with real-time bidding',
    category: 'commerce',
    opensBusinessSession: true,
    cowrieFlow: 'earns',
  },
  bid_tracker: {
    key: 'bid_tracker',
    name: 'Bid Tracker',
    icon: '📊',
    description: 'Track bids in real-time',
    category: 'commerce',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  value_calculator: {
    key: 'value_calculator',
    name: 'Value Calculator',
    icon: '⚖️',
    description: 'Calculate fair exchange values',
    category: 'commerce',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  material_stock: {
    key: 'material_stock',
    name: 'Material Stock',
    icon: '📦',
    description: 'Track fabrication materials',
    category: 'commerce',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  order_tracker: {
    key: 'order_tracker',
    name: 'Order Tracker',
    icon: '📋',
    description: 'Track customer orders',
    category: 'commerce',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },

  // ╔═══════════════════════════════════════════════════════════════╗
  // ║  COMMUNICATION TOOLS                                         ║
  // ╚═══════════════════════════════════════════════════════════════╝

  trade_session: {
    key: 'trade_session',
    name: 'Open Trade Session',
    icon: '🤝',
    iconComponent: 'DjembeIcon',
    description: 'Start a sealed business chat with escrow',
    category: 'communication',
    opensBusinessSession: true,
    cowrieFlow: 'neutral',
  },
  food_order_chat: {
    key: 'food_order_chat',
    name: 'Food Order Chat',
    icon: '🥘',
    description: 'Take food orders via chat with delivery tracking',
    category: 'communication',
    opensBusinessSession: true,
    cowrieFlow: 'earns',
  },
  supplier_connect: {
    key: 'supplier_connect',
    name: 'Supplier Connect',
    icon: '🔗',
    description: 'Find and connect with verified suppliers',
    category: 'communication',
    opensBusinessSession: true,
    cowrieFlow: 'spends',
  },
  dispute_resolver: {
    key: 'dispute_resolver',
    name: 'Dispute Resolver',
    icon: '⚖️',
    description: 'Manage and resolve trade disputes',
    category: 'communication',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  service_session: {
    key: 'service_session',
    name: 'Service Session',
    icon: '🛠',
    description: 'Open a service delivery session with provider',
    category: 'communication',
    opensBusinessSession: true,
    cowrieFlow: 'earns',
  },
  team_connect: {
    key: 'team_connect',
    name: 'Team Connect',
    icon: '👥',
    description: 'Team communication tool',
    category: 'communication',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },

  // ╔═══════════════════════════════════════════════════════════════╗
  // ║  FINANCE TOOLS                                               ║
  // ╚═══════════════════════════════════════════════════════════════╝

  escrow_release: {
    key: 'escrow_release',
    name: 'Escrow Manager',
    icon: '🔒',
    iconComponent: 'NkisiShield',
    description: 'Lock and release payments when both parties agree',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  ajo_circle: {
    key: 'ajo_circle',
    name: 'Ajo Circle',
    icon: '⭕',
    description: 'Join or start a community savings circle',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'earns',
  },
  credit_book: {
    key: 'credit_book',
    name: 'Credit Book',
    icon: '📒',
    description: 'Track credit given to trusted customers',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  cash_tracker: {
    key: 'cash_tracker',
    name: 'Cash Tracker',
    icon: '💵',
    description: 'Track daily cash in and cash out',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  mobile_payment_collect: {
    key: 'mobile_payment_collect',
    name: 'Mobile Payment Collect',
    icon: '📱',
    description: 'Accept QR code and mobile money payments',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'earns',
  },
  payment_link: {
    key: 'payment_link',
    name: 'Payment Link',
    icon: '🔗',
    description: 'Generate shareable payment links',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'earns',
  },
  pos_dashboard: {
    key: 'pos_dashboard',
    name: 'POS Dashboard',
    icon: '🏧',
    description: 'Point-of-sale transaction dashboard',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  daily_settlement: {
    key: 'daily_settlement',
    name: 'Daily Settlement',
    icon: '🏦',
    description: 'End-of-day reconciliation and settlement',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  transaction_log: {
    key: 'transaction_log',
    name: 'Transaction Log',
    icon: '📜',
    description: 'Immutable log of all transactions',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  profit_calculator: {
    key: 'profit_calculator',
    name: 'Profit Calculator',
    icon: '🧮',
    description: 'Calculate profit margins on goods',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  forex_rate_display: {
    key: 'forex_rate_display',
    name: 'Forex Rate Display',
    icon: '💱',
    description: 'Display live currency exchange rates',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  cowrie_exchange: {
    key: 'cowrie_exchange',
    name: 'Cowrie Exchange',
    icon: '🐚',
    description: 'Convert between Cowrie and local currencies',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  risk_calculator: {
    key: 'risk_calculator',
    name: 'Risk Calculator',
    icon: '📉',
    description: 'Calculate lending risk score',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  settlement_manager: {
    key: 'settlement_manager',
    name: 'Settlement Manager',
    icon: '💰',
    description: 'Manage post-auction settlements',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  wallet_connect: {
    key: 'wallet_connect',
    name: 'Wallet Connect',
    icon: '👛',
    description: 'Connect blockchain wallets',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  prize_escrow: {
    key: 'prize_escrow',
    name: 'Prize Escrow',
    icon: '🏅',
    description: 'Hold tournament prizes in escrow',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },

  // ╔═══════════════════════════════════════════════════════════════╗
  // ║  LOGISTICS TOOLS                                             ║
  // ╚═══════════════════════════════════════════════════════════════╝

  runner_dispatch: {
    key: 'runner_dispatch',
    name: 'Call a Runner',
    icon: '🚚',
    description: 'Get the nearest available runner to collect and deliver',
    category: 'logistics',
    opensBusinessSession: true,
    cowrieFlow: 'spends',
  },
  territory_map: {
    key: 'territory_map',
    name: 'Territory Map',
    icon: '🗺',
    description: 'Map your distribution territory',
    category: 'logistics',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  delivery_tracker: {
    key: 'delivery_tracker',
    name: 'Delivery Tracker',
    icon: '📍',
    description: 'Track deliveries in real-time',
    category: 'logistics',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  collection_tracker: {
    key: 'collection_tracker',
    name: 'Collection Tracker',
    icon: '♻️',
    description: 'Track waste or goods collection routes',
    category: 'logistics',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  route_planner: {
    key: 'route_planner',
    name: 'Route Planner',
    icon: '🗺',
    description: 'Plan optimal delivery routes',
    category: 'logistics',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  cold_chain_tracker: {
    key: 'cold_chain_tracker',
    name: 'Cold Chain Tracker',
    icon: '❄️',
    description: 'Monitor temperature for perishable goods',
    category: 'logistics',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  parts_finder: {
    key: 'parts_finder',
    name: 'Parts Finder',
    icon: '🔍',
    description: 'Find replacement parts for devices',
    category: 'logistics',
    opensBusinessSession: true,
    cowrieFlow: 'spends',
  },
  spare_parts_finder: {
    key: 'spare_parts_finder',
    name: 'Spare Parts Finder',
    icon: '🔩',
    description: 'Find spare parts from verified suppliers',
    category: 'logistics',
    opensBusinessSession: true,
    cowrieFlow: 'spends',
  },
  fuel_tracker: {
    key: 'fuel_tracker',
    name: 'Fuel Tracker',
    icon: '⛽',
    description: 'Track fuel consumption and costs',
    category: 'logistics',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  daily_route: {
    key: 'daily_route',
    name: 'Daily Route',
    icon: '🗺',
    description: 'Plan and track daily delivery routes',
    category: 'logistics',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },

  // ╔═══════════════════════════════════════════════════════════════╗
  // ║  PROFESSIONAL TOOLS                                          ║
  // ╚═══════════════════════════════════════════════════════════════╝

  document_vault: {
    key: 'document_vault',
    name: 'Document Vault',
    icon: '🗃',
    description: 'Secure encrypted document storage',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  client_tracker: {
    key: 'client_tracker',
    name: 'Client Tracker',
    icon: '👥',
    description: 'Track clients and their session history',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  customer_list: {
    key: 'customer_list',
    name: 'Customer List',
    icon: '📋',
    description: 'Manage regular customer contacts',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  hourly_timer: {
    key: 'hourly_timer',
    name: 'Hourly Timer',
    icon: '⏱',
    description: 'Track service hours for billing',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  queue_manager: {
    key: 'queue_manager',
    name: 'Queue Manager',
    icon: '🎫',
    description: 'Manage customer queues digitally',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  booking_calendar: {
    key: 'booking_calendar',
    name: 'Booking Calendar',
    icon: '📅',
    description: 'Schedule and manage bookings',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  maintenance_log: {
    key: 'maintenance_log',
    name: 'Maintenance Log',
    icon: '🔧',
    description: 'Track equipment maintenance schedules',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  quality_log: {
    key: 'quality_log',
    name: 'Quality Log',
    icon: '✅',
    description: 'Track product quality checks',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  land_map_tool: {
    key: 'land_map_tool',
    name: 'Land Map Tool',
    icon: '🗺',
    description: 'GPS-based land mapping and measurement',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  appointment_book: {
    key: 'appointment_book',
    name: 'Appointment Book',
    icon: '📅',
    description: 'Manage bookings and appointments',
    category: 'professional',
    opensBusinessSession: true,
    cowrieFlow: 'earns',
  },
  telemedicine: {
    key: 'telemedicine',
    name: 'Telemedicine Call',
    icon: '💻',
    description: 'Remote video consultation',
    category: 'professional',
    opensBusinessSession: true,
    cowrieFlow: 'earns',
  },
  case_log: {
    key: 'case_log',
    name: 'Case Log',
    icon: '📒',
    description: 'Log incidents and cases',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  code_project: {
    key: 'code_project',
    name: 'Code Project',
    icon: '💻',
    description: 'Project management for software development',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  client_brief: {
    key: 'client_brief',
    name: 'Client Brief',
    icon: '📋',
    description: 'Receive and manage client requirements',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  app_deploy_tracker: {
    key: 'app_deploy_tracker',
    name: 'App Deploy Tracker',
    icon: '🚀',
    description: 'Track app deployments and versions',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  dataset_vault: {
    key: 'dataset_vault',
    name: 'Dataset Vault',
    icon: '📊',
    description: 'Secure storage for datasets',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  project_tracker: {
    key: 'project_tracker',
    name: 'Project Tracker',
    icon: '📋',
    description: 'Track project milestones',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  audit_report: {
    key: 'audit_report',
    name: 'Audit Report',
    icon: '📝',
    description: 'Generate security audit reports',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  nda_generator: {
    key: 'nda_generator',
    name: 'NDA Generator',
    icon: '📜',
    description: 'Generate non-disclosure agreements',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  infrastructure_log: {
    key: 'infrastructure_log',
    name: 'Infrastructure Log',
    icon: '🖥',
    description: 'Track cloud infrastructure changes',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  sla_generator: {
    key: 'sla_generator',
    name: 'SLA Generator',
    icon: '📋',
    description: 'Generate service level agreements',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  site_survey: {
    key: 'site_survey',
    name: 'Site Survey',
    icon: '📝',
    description: 'Conduct site assessments for installations',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  repair_queue: {
    key: 'repair_queue',
    name: 'Repair Queue',
    icon: '🔧',
    description: 'Manage device repair queue',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  warranty_log: {
    key: 'warranty_log',
    name: 'Warranty Log',
    icon: '📜',
    description: 'Track device warranties',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  hosting_tracker: {
    key: 'hosting_tracker',
    name: 'Hosting Tracker',
    icon: '🌐',
    description: 'Track hosting and domain expiry',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  api_tester: {
    key: 'api_tester',
    name: 'API Tester',
    icon: '🧪',
    description: 'Test API endpoints',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  compliance_checker: {
    key: 'compliance_checker',
    name: 'Compliance Checker',
    icon: '✅',
    description: 'Check regulatory compliance',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  smart_contract_tool: {
    key: 'smart_contract_tool',
    name: 'Smart Contract Tool',
    icon: '⛓',
    description: 'Deploy and manage smart contracts',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  flight_log: {
    key: 'flight_log',
    name: 'Flight Log',
    icon: '✈️',
    description: 'Log drone flight hours and missions',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  map_tool: {
    key: 'map_tool',
    name: 'Map Tool',
    icon: '🗺',
    description: 'Aerial mapping and survey tool',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  technical_docs: {
    key: 'technical_docs',
    name: 'Technical Docs',
    icon: '📚',
    description: 'Create technical documentation',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  work_order: {
    key: 'work_order',
    name: 'Work Order',
    icon: '📋',
    description: 'Manage field work orders',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  safety_checklist: {
    key: 'safety_checklist',
    name: 'Safety Checklist',
    icon: '✅',
    description: 'Pre-work safety verification',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  analytics_report: {
    key: 'analytics_report',
    name: 'Analytics Report',
    icon: '📊',
    description: 'Generate marketing analytics',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  ticket_system: {
    key: 'ticket_system',
    name: 'Ticket System',
    icon: '🎫',
    description: 'IT support ticketing system',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  remote_access_tool: {
    key: 'remote_access_tool',
    name: 'Remote Access Tool',
    icon: '🖥',
    description: 'Remote desktop support',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  moderation_queue: {
    key: 'moderation_queue',
    name: 'Moderation Queue',
    icon: '🚫',
    description: 'Content moderation work queue',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  backup_monitor: {
    key: 'backup_monitor',
    name: 'Backup Monitor',
    icon: '💾',
    description: 'Monitor database backups',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  grant_tracker: {
    key: 'grant_tracker',
    name: 'Grant Tracker',
    icon: '📋',
    description: 'Track research grants',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  publication_vault: {
    key: 'publication_vault',
    name: 'Publication Vault',
    icon: '📚',
    description: 'Store research publications',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  site_map: {
    key: 'site_map',
    name: 'Site Map',
    icon: '🗺',
    description: 'Field site mapping tool',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  time_tracker: {
    key: 'time_tracker',
    name: 'Time Tracker',
    icon: '⏱',
    description: 'Track billable hours',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  delivery_confirmation: {
    key: 'delivery_confirmation',
    name: 'Delivery Confirmation',
    icon: '✅',
    description: 'Confirm work delivery',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  interview_scheduler: {
    key: 'interview_scheduler',
    name: 'Interview Scheduler',
    icon: '🎙',
    description: 'Schedule interviews',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  staff_manager: {
    key: 'staff_manager',
    name: 'Staff Manager',
    icon: '👥',
    description: 'Manage healthcare staff',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  billing_dashboard: {
    key: 'billing_dashboard',
    name: 'Billing Dashboard',
    icon: '💰',
    description: 'Hospital revenue dashboard',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  appointment_system: {
    key: 'appointment_system',
    name: 'Appointment System',
    icon: '📅',
    description: 'Multi-provider appointment booking',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  report_generator: {
    key: 'report_generator',
    name: 'Report Generator',
    icon: '📊',
    description: 'Generate administrative reports',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },

  // ╔═══════════════════════════════════════════════════════════════╗
  // ║  COMMUNITY TOOLS                                             ║
  // ╚═══════════════════════════════════════════════════════════════╝

  buyer_shadow_score: {
    key: 'buyer_shadow_score',
    name: 'Buyer Shadow Score',
    icon: '👁',
    description: "See a buyer's transaction history and trust score",
    category: 'community',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  review_tracker: {
    key: 'review_tracker',
    name: 'Review Tracker',
    icon: '⭐',
    description: 'Monitor and respond to customer reviews',
    category: 'community',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  barter_match: {
    key: 'barter_match',
    name: 'Barter Match',
    icon: '🔄',
    description: 'Match goods and services for exchange',
    category: 'community',
    opensBusinessSession: true,
    cowrieFlow: 'neutral',
  },
  community_board: {
    key: 'community_board',
    name: 'Community Board',
    icon: '📌',
    description: 'Post and browse community notices',
    category: 'community',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  community_connect: {
    key: 'community_connect',
    name: 'Community Connect',
    icon: '🤝',
    description: 'Connect patients with community resources',
    category: 'community',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  community_alert: {
    key: 'community_alert',
    name: 'Community Alert',
    icon: '🚨',
    description: 'Send alerts to community members',
    category: 'community',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  forecast_share: {
    key: 'forecast_share',
    name: 'Forecast Share',
    icon: '📡',
    description: 'Share weather forecasts with community',
    category: 'community',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  alert_system: {
    key: 'alert_system',
    name: 'Alert System',
    icon: '🔔',
    description: 'Set up custom notification alerts',
    category: 'community',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  conservation_log: {
    key: 'conservation_log',
    name: 'Conservation Log',
    icon: '🌳',
    description: 'Track conservation activities',
    category: 'community',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  impact_tracker: {
    key: 'impact_tracker',
    name: 'Impact Tracker',
    icon: '📈',
    description: 'Track social impact metrics',
    category: 'community',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  campaign_manager: {
    key: 'campaign_manager',
    name: 'Campaign Manager',
    icon: '📢',
    description: 'Manage outreach campaigns',
    category: 'community',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  attendance_tracker: {
    key: 'attendance_tracker',
    name: 'Attendance Tracker',
    icon: '✅',
    description: 'Track event and class attendance',
    category: 'community',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  outreach_planner: {
    key: 'outreach_planner',
    name: 'Outreach Planner',
    icon: '📋',
    description: 'Plan community health outreach',
    category: 'community',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },

  // ╔═══════════════════════════════════════════════════════════════╗
  // ║  HEALTH TOOLS                                                ║
  // ╚═══════════════════════════════════════════════════════════════╝

  patient_queue: {
    key: 'patient_queue',
    name: 'Patient Queue Manager',
    icon: '🏥',
    description: 'Manage patient flow in your clinic',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  prescription_tool: {
    key: 'prescription_tool',
    name: 'Prescription Tool',
    icon: '💊',
    description: 'Write and send digital prescriptions',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  referral_generator: {
    key: 'referral_generator',
    name: 'Referral Generator',
    icon: '📤',
    description: 'Generate patient referral letters',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  billing_tool: {
    key: 'billing_tool',
    name: 'Billing Tool',
    icon: '💳',
    description: 'Generate medical bills and track payments',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'earns',
  },
  operating_schedule: {
    key: 'operating_schedule',
    name: 'Operating Schedule',
    icon: '🏨',
    description: 'Schedule surgical operations',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  patient_records: {
    key: 'patient_records',
    name: 'Patient Records',
    icon: '📁',
    description: 'Secure electronic health records',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  referral_inbox: {
    key: 'referral_inbox',
    name: 'Referral Inbox',
    icon: '📥',
    description: 'Receive and manage referrals',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  case_notes: {
    key: 'case_notes',
    name: 'Case Notes',
    icon: '📝',
    description: 'Secure clinical case documentation',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  antenatal_tracker: {
    key: 'antenatal_tracker',
    name: 'Antenatal Tracker',
    icon: '🤰',
    description: 'Track pregnancy milestones',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  delivery_log: {
    key: 'delivery_log',
    name: 'Delivery Log',
    icon: '👶',
    description: 'Record birth details and outcomes',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  emergency_connect: {
    key: 'emergency_connect',
    name: 'Emergency Connect',
    icon: '🚑',
    description: 'Connect to emergency services',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  vaccination_tracker: {
    key: 'vaccination_tracker',
    name: 'Vaccination Tracker',
    icon: '💉',
    description: 'Track immunisation records',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  malaria_case_log: {
    key: 'malaria_case_log',
    name: 'Malaria Case Log',
    icon: '🦟',
    description: 'Log and track malaria cases',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  drug_stock_log: {
    key: 'drug_stock_log',
    name: 'Drug Stock Log',
    icon: '💊',
    description: 'Track medicine stock levels',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  prescription_scanner: {
    key: 'prescription_scanner',
    name: 'Prescription Scanner',
    icon: '📋',
    description: 'Scan paper prescriptions',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  drug_stock: {
    key: 'drug_stock',
    name: 'Drug Stock',
    icon: '💊',
    description: 'Pharmacy inventory management',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  drug_interaction_checker: {
    key: 'drug_interaction_checker',
    name: 'Drug Interaction Checker',
    icon: '⚠️',
    description: 'Check for drug interactions',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  refill_tracker: {
    key: 'refill_tracker',
    name: 'Refill Tracker',
    icon: '🔄',
    description: 'Track prescription refills',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  drug_advisory: {
    key: 'drug_advisory',
    name: 'Drug Advisory',
    icon: '📖',
    description: 'Over-the-counter medicine guidance',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  herbal_recipe_vault: {
    key: 'herbal_recipe_vault',
    name: 'Herbal Recipe Vault',
    icon: '🌿',
    description: 'Store traditional medicine formulations',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  patient_notes: {
    key: 'patient_notes',
    name: 'Patient Notes',
    icon: '📝',
    description: 'Simple patient care notes',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  session_notes: {
    key: 'session_notes',
    name: 'Session Notes',
    icon: '📝',
    description: 'Therapy and counselling session notes',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  case_management: {
    key: 'case_management',
    name: 'Case Management',
    icon: '📋',
    description: 'Social work case management',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  test_request_system: {
    key: 'test_request_system',
    name: 'Test Request System',
    icon: '🔬',
    description: 'Order and manage lab tests',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  result_delivery: {
    key: 'result_delivery',
    name: 'Result Delivery',
    icon: '📩',
    description: 'Secure test result delivery',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  result_alert: {
    key: 'result_alert',
    name: 'Result Alert',
    icon: '🔔',
    description: 'Alert when results are ready',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  image_vault: {
    key: 'image_vault',
    name: 'Image Vault',
    icon: '📸',
    description: 'Secure medical image storage',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  sample_log: {
    key: 'sample_log',
    name: 'Sample Log',
    icon: '🧪',
    description: 'Track collected samples',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  hospital_connect: {
    key: 'hospital_connect',
    name: 'Hospital Connect',
    icon: '🏥',
    description: 'Connect with hospitals for transfers',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  vital_signs_log: {
    key: 'vital_signs_log',
    name: 'Vital Signs Log',
    icon: '❤️',
    description: 'Record and track vital signs',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  medication_tracker: {
    key: 'medication_tracker',
    name: 'Medication Tracker',
    icon: '💊',
    description: 'Track medication schedules',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  shift_planner: {
    key: 'shift_planner',
    name: 'Shift Planner',
    icon: '🕐',
    description: 'Plan nursing and staff shifts',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  disease_tracker: {
    key: 'disease_tracker',
    name: 'Disease Tracker',
    icon: '📊',
    description: 'Track disease outbreaks',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  data_reporter: {
    key: 'data_reporter',
    name: 'Data Reporter',
    icon: '📈',
    description: 'Generate health data reports',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  contact_trace: {
    key: 'contact_trace',
    name: 'Contact Trace',
    icon: '🔍',
    description: 'Contact tracing tool',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  meal_planner: {
    key: 'meal_planner',
    name: 'Meal Planner',
    icon: '🥗',
    description: 'Create nutrition-optimised meal plans',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  inspection_log: {
    key: 'inspection_log',
    name: 'Inspection Log',
    icon: '📋',
    description: 'Record health and safety inspections',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  violation_notice: {
    key: 'violation_notice',
    name: 'Violation Notice',
    icon: '⚠️',
    description: 'Issue health code violations',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  follow_up_tracker: {
    key: 'follow_up_tracker',
    name: 'Follow Up Tracker',
    icon: '📝',
    description: 'Track follow-up visits',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  treatment_log: {
    key: 'treatment_log',
    name: 'Treatment Log',
    icon: '📋',
    description: 'Record treatment sessions',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  exercise_guide: {
    key: 'exercise_guide',
    name: 'Exercise Guide',
    icon: '🏋️',
    description: 'Prescribe exercise routines',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  home_assessment: {
    key: 'home_assessment',
    name: 'Home Assessment',
    icon: '🏠',
    description: 'Conduct home accessibility assessments',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  ARV_tracker: {
    key: 'ARV_tracker',
    name: 'ARV Tracker',
    icon: '💊',
    description: 'Track antiretroviral adherence',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  supply_tracker: {
    key: 'supply_tracker',
    name: 'Supply Tracker',
    icon: '📦',
    description: 'Track medical supply inventory',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },

  // ╔═══════════════════════════════════════════════════════════════╗
  // ║  AGRICULTURE TOOLS                                           ║
  // ╚═══════════════════════════════════════════════════════════════╝

  weather_alert: {
    key: 'weather_alert',
    name: 'Weather Alert',
    icon: '🌦',
    description: 'Real-time weather warnings for your area',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  crop_calendar: {
    key: 'crop_calendar',
    name: 'Crop Calendar',
    icon: '📅',
    description: 'Planting and harvest schedule guide',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  harvest_calculator: {
    key: 'harvest_calculator',
    name: 'Harvest Calculator',
    icon: '🌾',
    description: 'Estimate harvest yield and value',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  market_price_checker: {
    key: 'market_price_checker',
    name: 'Market Price Checker',
    icon: '💰',
    description: 'Live farm gate and market prices',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  input_supplier: {
    key: 'input_supplier',
    name: 'Input Supplier Connect',
    icon: '🌱',
    description: 'Connect with verified seed and fertiliser suppliers',
    category: 'agriculture',
    opensBusinessSession: true,
    cowrieFlow: 'spends',
  },
  export_connect: {
    key: 'export_connect',
    name: 'Export Connect',
    icon: '🌍',
    description: 'Connect with international commodity buyers',
    category: 'agriculture',
    opensBusinessSession: true,
    cowrieFlow: 'earns',
  },
  weather_station: {
    key: 'weather_station',
    name: 'Weather Station',
    icon: '🌡',
    description: 'Advanced weather monitoring for large farms',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  irrigation_schedule: {
    key: 'irrigation_schedule',
    name: 'Irrigation Schedule',
    icon: '💧',
    description: 'Automated irrigation timing planner',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  mill_connect: {
    key: 'mill_connect',
    name: 'Mill Connect',
    icon: '🏭',
    description: 'Connect farmers to milling facilities',
    category: 'agriculture',
    opensBusinessSession: true,
    cowrieFlow: 'earns',
  },
  certification_tracker: {
    key: 'certification_tracker',
    name: 'Certification Tracker',
    icon: '✅',
    description: 'Track organic and fair trade certifications',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  price_floor_alert: {
    key: 'price_floor_alert',
    name: 'Price Floor Alert',
    icon: '📢',
    description: 'Alert when commodity price drops below threshold',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  daily_price_checker: {
    key: 'daily_price_checker',
    name: 'Daily Price Checker',
    icon: '📊',
    description: 'Day-by-day price tracking for perishables',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  market_connect: {
    key: 'market_connect',
    name: 'Market Connect',
    icon: '🏪',
    description: 'Connect producers to market buyers',
    category: 'agriculture',
    opensBusinessSession: true,
    cowrieFlow: 'earns',
  },
  harvest_calendar: {
    key: 'harvest_calendar',
    name: 'Harvest Calendar',
    icon: '🗓',
    description: 'Track harvest windows for multiple crops',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  drying_guide: {
    key: 'drying_guide',
    name: 'Drying Guide',
    icon: '☀️',
    description: 'Post-harvest drying protocols',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  packaging_tool: {
    key: 'packaging_tool',
    name: 'Packaging Tool',
    icon: '📦',
    description: 'Packaging specifications and labeling',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  livestock_tracker: {
    key: 'livestock_tracker',
    name: 'Livestock Tracker',
    icon: '🐄',
    description: 'Track herd size, health, and value',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  veterinary_connect: {
    key: 'veterinary_connect',
    name: 'Veterinary Connect',
    icon: '🩺',
    description: 'Connect with veterinary services',
    category: 'agriculture',
    opensBusinessSession: true,
    cowrieFlow: 'spends',
  },
  movement_log: {
    key: 'movement_log',
    name: 'Movement Log',
    icon: '📍',
    description: 'Track livestock movement and grazing',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  cattle_insurance: {
    key: 'cattle_insurance',
    name: 'Cattle Insurance',
    icon: '🛡',
    description: 'Livestock insurance enrolment and claims',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'spends',
  },
  festive_demand_alert: {
    key: 'festive_demand_alert',
    name: 'Festive Demand Alert',
    icon: '🎉',
    description: 'Alert when festive season drives demand up',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  milk_log: {
    key: 'milk_log',
    name: 'Milk Log',
    icon: '🥛',
    description: 'Daily milk production tracking',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  cooperative_connect: {
    key: 'cooperative_connect',
    name: 'Cooperative Connect',
    icon: '🤝',
    description: 'Connect with farmer cooperatives',
    category: 'agriculture',
    opensBusinessSession: true,
    cowrieFlow: 'neutral',
  },
  catch_log: {
    key: 'catch_log',
    name: 'Catch Log',
    icon: '🐟',
    description: 'Log daily fishing catch',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  boat_maintenance_log: {
    key: 'boat_maintenance_log',
    name: 'Boat Maintenance Log',
    icon: '🚤',
    description: 'Track boat repairs and maintenance',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  pond_monitor: {
    key: 'pond_monitor',
    name: 'Pond Monitor',
    icon: '🌊',
    description: 'Monitor fish pond water quality',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  production_log: {
    key: 'production_log',
    name: 'Production Log',
    icon: '📋',
    description: 'Track daily production output',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  farmer_connect: {
    key: 'farmer_connect',
    name: 'Farmer Connect',
    icon: '🌾',
    description: 'Connect with farmers in your area',
    category: 'agriculture',
    opensBusinessSession: true,
    cowrieFlow: 'neutral',
  },
  soil_testing: {
    key: 'soil_testing',
    name: 'Soil Testing',
    icon: '🧪',
    description: 'Request and log soil test results',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  crop_advisory: {
    key: 'crop_advisory',
    name: 'Crop Advisory',
    icon: '📖',
    description: 'Expert crop management advice',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  weather_log: {
    key: 'weather_log',
    name: 'Weather Log',
    icon: '📝',
    description: 'Record daily weather observations',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  carbon_credit_connect: {
    key: 'carbon_credit_connect',
    name: 'Carbon Credit Connect',
    icon: '🌿',
    description: 'Connect with carbon credit programs',
    category: 'agriculture',
    opensBusinessSession: true,
    cowrieFlow: 'earns',
  },

  // ╔═══════════════════════════════════════════════════════════════╗
  // ║  EDUCATION TOOLS                                             ║
  // ╚═══════════════════════════════════════════════════════════════╝

  class_manager: {
    key: 'class_manager',
    name: 'Class Manager',
    icon: '📚',
    description: 'Manage training classes',
    category: 'education',
    opensBusinessSession: false,
    cowrieFlow: 'earns',
  },
  curriculum_vault: {
    key: 'curriculum_vault',
    name: 'Curriculum Vault',
    icon: '📖',
    description: 'Store and share curricula',
    category: 'education',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  certificate_generator: {
    key: 'certificate_generator',
    name: 'Certificate Generator',
    icon: '🎓',
    description: 'Issue completion certificates',
    category: 'education',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },

  // ╔═══════════════════════════════════════════════════════════════╗
  // ║  MEDIA TOOLS                                                 ║
  // ╚═══════════════════════════════════════════════════════════════╝

  press_pass: {
    key: 'press_pass',
    name: 'Press Pass',
    icon: '🪪',
    description: 'Digital press credentials',
    category: 'media',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },

  // ╔═══════════════════════════════════════════════════════════════╗
  // ║  CREATIVE TOOLS                                              ║
  // ╚═══════════════════════════════════════════════════════════════╝

  portfolio_vault: {
    key: 'portfolio_vault',
    name: 'Portfolio Vault',
    icon: '🎨',
    description: 'Showcase your work portfolio',
    category: 'creative',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  design_brief: {
    key: 'design_brief',
    name: 'Design Brief',
    icon: '🎨',
    description: 'Receive and manage design briefs',
    category: 'creative',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  game_project: {
    key: 'game_project',
    name: 'Game Project',
    icon: '🎮',
    description: 'Game development project tracker',
    category: 'creative',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  content_calendar: {
    key: 'content_calendar',
    name: 'Content Calendar',
    icon: '📅',
    description: 'Plan content publishing schedule',
    category: 'creative',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  article_vault: {
    key: 'article_vault',
    name: 'Article Vault',
    icon: '📰',
    description: 'Store published articles',
    category: 'creative',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },

  // ╔═══════════════════════════════════════════════════════════════╗
  // ║  SPORTS TOOLS                                                ║
  // ╚═══════════════════════════════════════════════════════════════╝

  tournament_manager: {
    key: 'tournament_manager',
    name: 'Tournament Manager',
    icon: '🏆',
    description: 'Organise esports tournaments',
    category: 'sports',
    opensBusinessSession: true,
    cowrieFlow: 'earns',
  },

  // ── Missing tools referenced by ROLE_REGISTRY ────────────────────────────

  chat_secure: {
    key: 'chat_secure',
    name: 'Seso Chat (Secure)',
    icon: '💬',
    description: 'End-to-end encrypted messaging with clients, colleagues, and community',
    category: 'communication',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },

  medical_records: {
    key: 'medical_records',
    name: 'Medical Records',
    icon: '🩺',
    description: 'Secure digital patient records — consultations, prescriptions, referrals',
    category: 'health',
    opensBusinessSession: true,
    cowrieFlow: 'earns',
  },

  portfolio_tracker: {
    key: 'portfolio_tracker',
    name: 'Portfolio Tracker',
    icon: '📊',
    description: 'Track investment portfolio performance, assets, and returns',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },

  // ── Tools from canonical 160-role spec ───────────────────────────
  recording_vault: {
    key: 'recording_vault',
    name: 'Recording Vault',
    icon: '🎙️',
    description: 'Secure vault for audio recordings, music tracks, oral traditions, and podcast archives',
    category: 'media',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  health_log: {
    key: 'health_log',
    name: 'Health Log',
    icon: '🐄',
    description: 'Track health status, treatments, and vaccination records for livestock and animals',
    category: 'agriculture',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  fleet_manager: {
    key: 'fleet_manager',
    name: 'Fleet Manager',
    icon: '🚛',
    description: 'Manage vehicle fleet assignments, driver schedules, availability, and performance tracking',
    category: 'logistics',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  incident_log: {
    key: 'incident_log',
    name: 'Incident Log',
    icon: '🚨',
    description: 'Record and track security incidents, breaches, alerts, and emergency response actions',
    category: 'security',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  prescription_vault: {
    key: 'prescription_vault',
    name: 'Prescription Vault',
    icon: '💊',
    description: 'Secure digital prescription records, medication history, and drug dispensing logs',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  debug_log: {
    key: 'debug_log',
    name: 'Debug Log',
    icon: '🔍',
    description: 'Track and resolve software bugs with linked code references and resolution history',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  knowledge_base: {
    key: 'knowledge_base',
    name: 'Knowledge Base',
    icon: '📖',
    description: 'Searchable library of solutions, how-to guides, and support documentation',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  invoice_batch: {
    key: 'invoice_batch',
    name: 'Invoice Batch',
    icon: '📑',
    description: 'Generate and send bulk invoices to multiple clients or suppliers simultaneously',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'earns',
  },
  escrow_monitor: {
    key: 'escrow_monitor',
    name: 'Escrow Monitor',
    icon: '🔒',
    description: 'Monitor escrow accounts, track hold periods, and manage conditional release of funds',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  budget_tracker: {
    key: 'budget_tracker',
    name: 'Budget Tracker',
    icon: '💰',
    description: 'Plan and monitor budgets, expenses, and variance against financial targets',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  vehicle_log: {
    key: 'vehicle_log',
    name: 'Vehicle Log',
    icon: '🚗',
    description: 'Log vehicle trips, fuel usage, mileage, and compliance records for each unit in fleet',
    category: 'logistics',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  blueprint_vault: {
    key: 'blueprint_vault',
    name: 'Blueprint Vault',
    icon: '📐',
    description: 'Store and share architectural drawings, CAD files, and engineering blueprints securely',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  research_vault: {
    key: 'research_vault',
    name: 'Research Vault',
    icon: '📚',
    description: 'Organise case law, legal research, academic publications, and reference documents',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  evidence_vault: {
    key: 'evidence_vault',
    name: 'Evidence Vault',
    icon: '🔎',
    description: 'Secure chain-of-custody storage for digital evidence, exhibits, and forensic records',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  session_log: {
    key: 'session_log',
    name: 'Session Log',
    icon: '📝',
    description: 'Log counselling sessions, mediation records, and client interaction notes with timestamps',
    category: 'health',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  member_tracker: {
    key: 'member_tracker',
    name: 'Member Tracker',
    icon: '👥',
    description: 'Track cooperative/group members, contributions, attendance, and standing',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  press_kit_vault: {
    key: 'press_kit_vault',
    name: 'Press Kit Vault',
    icon: '📰',
    description: 'Store media kits, brand assets, bios, and press releases for journalists and media contacts',
    category: 'media',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  episode_tracker: {
    key: 'episode_tracker',
    name: 'Episode Tracker',
    icon: '🎧',
    description: 'Track podcast/show episodes — publish status, listener metrics, and guest schedule',
    category: 'media',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  equipment_log: {
    key: 'equipment_log',
    name: 'Equipment Log',
    icon: '🎬',
    description: 'Track equipment bookings, maintenance status, and usage records for production gear',
    category: 'media',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  daily_pnl: {
    key: 'daily_pnl',
    name: 'Daily P&L',
    icon: '📈',
    description: 'Real-time daily profit and loss dashboard tracking trades, positions, and net exposure',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  donation_tracker: {
    key: 'donation_tracker',
    name: 'Donation Tracker',
    icon: '🤲',
    description: 'Track charity donations, tithes, and community contributions with receipts',
    category: 'community',
    opensBusinessSession: false,
    cowrieFlow: 'earns',
  },
  policy_vault: {
    key: 'policy_vault',
    name: 'Policy Vault',
    icon: '📋',
    description: 'Store insurance policies, compliance documents, and regulatory filings securely',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  claims_log: {
    key: 'claims_log',
    name: 'Claims Log',
    icon: '📄',
    description: 'Track insurance claims from filing through assessment to settlement resolution',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  translation_log: {
    key: 'translation_log',
    name: 'Translation Log',
    icon: '🌐',
    description: 'Log translation projects, language pairs, and culturally sensitive document adaptations',
    category: 'government',
    opensBusinessSession: false,
    cowrieFlow: 'earns',
  },
  data_dashboard: {
    key: 'data_dashboard',
    name: 'Data Dashboard',
    icon: '📊',
    description: 'Interactive policy and civic data visualisation with trend analysis and public metrics',
    category: 'government',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  archive_log: {
    key: 'archive_log',
    name: 'Archive Log',
    icon: '🗄️',
    description: 'Preserve and index historical records, oral histories, and cultural artefact documentation',
    category: 'education',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  resource_tracker: {
    key: 'resource_tracker',
    name: 'Resource Tracker',
    icon: '📦',
    description: 'Track emergency resources, stockpiles, and deployment status during crisis response',
    category: 'security',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  cargo_log: {
    key: 'cargo_log',
    name: 'Cargo Log',
    icon: '⚓',
    description: 'Log marine cargo manifests, loading records, and voyage documentation',
    category: 'logistics',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  vendor_log: {
    key: 'vendor_log',
    name: 'Vendor Log',
    icon: '🤝',
    description: 'Track hospitality vendors, suppliers, and event service providers with ratings and contracts',
    category: 'community',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  media_list: {
    key: 'media_list',
    name: 'Media List',
    icon: '📡',
    description: 'Manage journalist contacts, media relationships, and press outreach databases',
    category: 'media',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  source_log: {
    key: 'source_log',
    name: 'Source Log',
    icon: '🗂️',
    description: 'Record and verify journalistic sources, interviews, and reference documentation',
    category: 'media',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  audit_log: {
    key: 'audit_log',
    name: 'Audit Log',
    icon: '🔐',
    description: 'Immutable activity log tracking all system access, changes, and compliance events',
    category: 'security',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  cost_dashboard: {
    key: 'cost_dashboard',
    name: 'Cost Dashboard',
    icon: '💸',
    description: 'Monitor cloud and infrastructure spend, track budgets, and optimise cost efficiency',
    category: 'professional',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  settlement_tracker: {
    key: 'settlement_tracker',
    name: 'Settlement Tracker',
    icon: '⚖️',
    description: 'Track trade and financial settlement timelines, counterparty obligations, and cleared positions',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  fraud_alert: {
    key: 'fraud_alert',
    name: 'Fraud Alert',
    icon: '🛡️',
    description: 'Real-time fraud detection alerts for suspicious transactions, failed auth, and anomalies',
    category: 'finance',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
  timer_board: {
    key: 'timer_board',
    name: 'Timer Board',
    icon: '⏱️',
    description: 'Live countdown board for auctions, bids, and time-sensitive sales events',
    category: 'commerce',
    opensBusinessSession: false,
    cowrieFlow: 'neutral',
  },
}

// ── Helpers ──────────────────────────────────────────────────────

/** Retrieve ToolDefinition objects by an array of tool keys */
export function getToolsByKeys(keys: string[]): ToolDefinition[] {
  return keys.map(k => TOOL_REGISTRY[k]).filter(Boolean)
}

/** Retrieve all tools assigned to a given role key */
export function getToolsForRole(roleKey: string): ToolDefinition[] {
  const role = getRoleByKey(roleKey)
  if (!role) return []
  return getToolsByKeys(role.tools)
}

/** Get all tools in a specific category */
export function getToolsByCategory(category: ToolDefinition['category']): ToolDefinition[] {
  return Object.values(TOOL_REGISTRY).filter(t => t.category === category)
}

/** Get all tools that open a business session */
export function getBusinessSessionTools(): ToolDefinition[] {
  return Object.values(TOOL_REGISTRY).filter(t => t.opensBusinessSession)
}

/** Get all tools that earn Cowrie */
export function getEarningTools(): ToolDefinition[] {
  return Object.values(TOOL_REGISTRY).filter(t => t.cowrieFlow === 'earns')
}

/** Get all tools that spend Cowrie */
export function getSpendingTools(): ToolDefinition[] {
  return Object.values(TOOL_REGISTRY).filter(t => t.cowrieFlow === 'spends')
}

/** Total number of tools in the registry */
export const TOTAL_TOOLS = Object.keys(TOOL_REGISTRY).length
