import type { VillageRole } from './village-roles-part1'
export type { VillageRole }

export const VILLAGE_ROLES_PART2: Record<string, VillageRole[]> = {

security: [
  {id:'se01',emoji:'🛡️',name:'Private Security Guard',sector:'Private Security',desc:'Protects premises, people, and property from unauthorised access'},
  {id:'se02',emoji:'👮',name:'Security Supervisor',sector:'Private Security',desc:'Manages a team of security officers across a site or facility'},
  {id:'se03',emoji:'🔫',name:'Armed Response Officer',sector:'Private Security',desc:'Provides rapid armed response to security incidents and alarms'},
  {id:'se04',emoji:'📷',name:'CCTV Operator',sector:'Private Security',desc:'Monitors surveillance feeds and reports suspicious activities'},
  {id:'se05',emoji:'🚪',name:'Access Control Technician',sector:'Private Security',desc:'Installs and manages biometric and electronic access systems'},
  {id:'se06',emoji:'🔥',name:'Fire Safety Officer',sector:'Private Security',desc:'Conducts fire risk assessments and trains emergency responses'},
  {id:'se07',emoji:'👔',name:'Chief Security Officer',sector:'Private Security',desc:'Leads the strategic security function across an organisation'},
  {id:'se08',emoji:'🎪',name:'Event Security Marshal',sector:'Private Security',desc:'Manages crowd safety and access control at public events'},
  {id:'se09',emoji:'🕴️',name:'VIP Protection / Bodyguard',sector:'Private Security',desc:'Provides close personal protection for high-profile individuals'},
  {id:'se10',emoji:'🔍',name:'Loss Prevention Officer',sector:'Private Security',desc:'Detects shoplifting and reduces retail shrinkage losses'},
  {id:'se11',emoji:'🎖️',name:'Military Officer',sector:'Military',desc:'Commands military units and leads operations on the field'},
  {id:'se12',emoji:'🪖',name:'Soldier / Infantry Officer',sector:'Military',desc:'Serves as a frontline military combatant and defender'},
  {id:'se13',emoji:'⚕️',name:'Combat Medic',sector:'Military',desc:'Delivers emergency medical care in active combat environments'},
  {id:'se14',emoji:'📡',name:'Military Intelligence Analyst',sector:'Military',desc:'Collects and interprets intelligence to support military operations'},
  {id:'se15',emoji:'🔊',name:'Signals / Communications Soldier',sector:'Military',desc:'Operates military communication and signals equipment'},
  {id:'se16',emoji:'⚓',name:'Naval Officer',sector:'Military',desc:'Commands and operates naval vessels for maritime security'},
  {id:'se17',emoji:'✈️',name:'Air Force Pilot (Military)',sector:'Military',desc:'Flies military aircraft for combat, transport, and surveillance'},
  {id:'se18',emoji:'👮',name:'Military Police',sector:'Military',desc:'Enforces military law and discipline within armed forces'},
  {id:'se19',emoji:'💣',name:'Explosive Ordnance Disposal (EOD)',sector:'Military',desc:'Detects and safely neutralises explosive devices and mines'},
  {id:'se20',emoji:'🥷',name:'Special Forces Operator',sector:'Military',desc:'Conducts high-risk unconventional and counter-terrorism operations'},
  {id:'se21',emoji:'👮',name:'Police Officer',sector:'Law Enforcement',desc:'Enforces the law and maintains public order and safety'},
  {id:'se22',emoji:'🔎',name:'Detective / Criminal Investigator',sector:'Law Enforcement',desc:'Investigates crimes and gathers evidence for prosecution'},
  {id:'se23',emoji:'🏛️',name:'Police Commissioner',sector:'Law Enforcement',desc:'Commands the national or state police organisation'},
  {id:'se24',emoji:'🛂',name:'Border Guard / Immigration Officer',sector:'Law Enforcement',desc:'Controls and secures international border crossings'},
  {id:'se25',emoji:'💣',name:'Anti-Terrorism Officer',sector:'Law Enforcement',desc:'Prevents and responds to terrorism threats and attacks'},
  {id:'se26',emoji:'💊',name:'Drug Squad Officer',sector:'Law Enforcement',desc:'Investigates narcotics trafficking and supply chain networks'},
  {id:'se27',emoji:'💴',name:'Fraud Investigator',sector:'Law Enforcement',desc:'Probes financial crimes, forgery, and economic offences'},
  {id:'se28',emoji:'🧑‍💻',name:'Cybercrime Officer',sector:'Law Enforcement',desc:'Investigates online fraud, hacking, and digital criminal activity'},
  {id:'se29',emoji:'🔬',name:'Forensic Analyst',sector:'Law Enforcement',desc:'Examines physical evidence to support criminal investigations'},
  {id:'se30',emoji:'🌿',name:'Wildlife / Anti-Poaching Ranger',sector:'Law Enforcement',desc:'Protects wildlife reserves and combats illegal poaching'},
  {id:'se31',emoji:'🕵️',name:'Intelligence Analyst',sector:'Intelligence',desc:'Analyses data to assess threats and support national security'},
  {id:'se32',emoji:'🔐',name:'Counter-Intelligence Officer',sector:'Intelligence',desc:'Detects and neutralises infiltration by foreign intelligence services'},
  {id:'se33',emoji:'👁️',name:'Surveillance Specialist',sector:'Intelligence',desc:'Conducts covert monitoring of individuals and organisations'},
  {id:'se34',emoji:'⚠️',name:'Risk & Threat Assessor',sector:'Intelligence',desc:'Evaluates security risks and advises on protective measures'},
  {id:'se35',emoji:'🆘',name:'Emergency Coordinator',sector:'Cybersecurity & Technology',desc:'Manages multi-agency responses to major emergency incidents'},
  {id:'se36',emoji:'🗺️',name:'Crisis Management Specialist',sector:'Intelligence',desc:'Develops and executes plans to resolve security crises'},
  {id:'se37',emoji:'🌊',name:'Disaster Response Officer',sector:'Intelligence',desc:'Coordinates rescue and relief operations after disasters'},
  {id:'se38',emoji:'🚒',name:'Fire Fighter',sector:'Law Enforcement',desc:'Extinguishes fires and rescues persons from emergency situations'},
  {id:'se39',emoji:'🤿',name:'Rescue Diver',sector:'Law Enforcement',desc:'Performs water rescues and underwater search and recovery'},
  {id:'se40',emoji:'🪂',name:'Pararescue Specialist',sector:'Military',desc:'Executes personnel recovery and combat search-and-rescue missions'},
  {id:'se41',emoji:'🔒',name:'Cybersecurity Analyst',sector:'Cybersecurity & Technology',desc:'Defends digital systems against cyber threats and intrusions'},
  {id:'se42',emoji:'🕵️',name:'Ethical Hacker',sector:'Cybersecurity & Technology',desc:'Probes systems for vulnerabilities before malicious actors do'},
  {id:'se43',emoji:'🏗️',name:'Security Architect',sector:'Cybersecurity & Technology',desc:'Designs secure organisational IT and network infrastructure'},
  {id:'se44',emoji:'📡',name:'SOC Analyst',sector:'Cybersecurity & Technology',desc:'Monitors alerts and responds to incidents in a Security Operations Centre'},
  {id:'se45',emoji:'🧬',name:'Digital Forensics Expert',sector:'Cybersecurity & Technology',desc:'Recovers and analyses digital evidence from compromised systems'},
  {id:'se46',emoji:'🌍',name:'Homeland Security Officer',sector:'Law Enforcement',desc:'Coordinates national security programmes across agencies'},
  {id:'se47',emoji:'⚓',name:'Port Security Officer',sector:'Private Security',desc:'Secures ports and maritime facilities against threats and smuggling'},
  {id:'se48',emoji:'✈️',name:'Airport Security Screener',sector:'Private Security',desc:'Screens passengers and baggage at airport checkpoints'},
  {id:'se49',emoji:'🚗',name:'Armoured Vehicle Driver',sector:'Private Security',desc:'Transports cash and valuables in protected security vehicles'},
  {id:'se50',emoji:'🐕',name:'Explosives Detection K9 Handler',sector:'Law Enforcement',desc:'Partners with trained dogs to detect explosives and contraband'},
],

spirituality: [
  {id:'sp01',emoji:'✝️',name:'Pastor / Reverend',sector:'Faith Leadership',desc:'Leads a Christian congregation in worship, teaching, and pastoral care'},
  {id:'sp02',emoji:'⛪',name:'Catholic Priest',sector:'Faith Leadership',desc:'Celebrates the sacraments and leads a Catholic parish community'},
  {id:'sp03',emoji:'🎵',name:'Gospel Choir Director',sector:'Faith Leadership',desc:'Leads and trains a church choir in sacred music and worship'},
  {id:'sp04',emoji:'👑',name:'Bishop',sector:'Faith Leadership',desc:'Provides oversight and governance over a diocese or church region'},
  {id:'sp05',emoji:'🏛️',name:'Archbishop',sector:'Faith Leadership',desc:'Leads a metropolitan archdiocese or major church jurisdiction'},
  {id:'sp06',emoji:'🕌',name:'Imam',sector:'Faith Leadership',desc:'Leads Friday prayers and provides guidance to a Muslim community'},
  {id:'sp07',emoji:'📖',name:'Islamic Scholar / Mufti',sector:'Faith Leadership',desc:'Issues Islamic legal rulings and scholarly religious opinions'},
  {id:'sp08',emoji:'📿',name:'Quran Teacher',sector:'Education & Research',desc:'Teaches Quranic recitation, memorisation, and interpretation'},
  {id:'sp09',emoji:'🔔',name:'Muezzin',sector:'Faith Leadership',desc:'Issues the call to prayer five times daily at the mosque'},
  {id:'sp10',emoji:'❤️',name:'Islamic Welfare Officer',sector:'Administration',desc:'Coordinates zakat collection and distribution to those in need'},
  {id:'sp11',emoji:'✡️',name:'Rabbi',sector:'Faith Leadership',desc:'Leads a Jewish congregation and teaches Torah and Jewish law'},
  {id:'sp12',emoji:'🛕',name:'Traditional Priest / Babalawo',sector:'Traditional Religion',desc:'Reads Ifa oracle and performs African traditional religious rites'},
  {id:'sp13',emoji:'🌊',name:'Voodoo / Vodun Priest',sector:'Traditional Religion',desc:'Mediates between the living and the spirits in Vodun tradition'},
  {id:'sp14',emoji:'🏺',name:'Traditional Shrine Keeper',sector:'Traditional Religion',desc:'Maintains and protects sacred shrines and ancestral ritual spaces'},
  {id:'sp15',emoji:'🌙',name:'Ancestral Rites Officiant',sector:'Traditional Religion',desc:'Conducts ceremonies honouring ancestors and community heritage'},
  {id:'sp16',emoji:'🌿',name:'Sangoma / Diviner',sector:'Traditional Religion',desc:'Facilitates healing and guidance through ancestral spirit communication'},
  {id:'sp17',emoji:'🌱',name:'Spiritual Healer',sector:'Traditional Religion',desc:'Uses prayer, herbs, and rituals to restore physical and spiritual health'},
  {id:'sp18',emoji:'🌿',name:'Herbalist-Spiritual',sector:'Traditional Religion',desc:'Combines traditional plant medicine with spiritual healing practices'},
  {id:'sp19',emoji:'🧘',name:'Monk / Religious Brother',sector:'Faith Leadership',desc:'Lives a devoted monastic life of prayer, work, and community'},
  {id:'sp20',emoji:'🙏',name:'Nun / Religious Sister',sector:'Faith Leadership',desc:'Serves God and community through a consecrated religious vocation'},
  {id:'sp21',emoji:'🎓',name:'Seminary Teacher',sector:'Education & Research',desc:'Trains future ministers and religious leaders in theology'},
  {id:'sp22',emoji:'👶',name:'Sunday School Teacher',sector:'Education & Research',desc:'Provides religious education and moral formation for children'},
  {id:'sp23',emoji:'🌟',name:'Youth Ministry Leader',sector:'Faith Leadership',desc:'Leads faith formation and discipleship programmes for young people'},
  {id:'sp24',emoji:'🏥',name:'Hospital Chaplain',sector:'Faith Leadership',desc:'Provides spiritual care to patients and families in healthcare settings'},
  {id:'sp25',emoji:'🏢',name:'Military Chaplain',sector:'Faith Leadership',desc:'Offers pastoral support and religious services to military personnel'},
  {id:'sp26',emoji:'🔒',name:'Prison Chaplain',sector:'Faith Leadership',desc:'Ministers to incarcerated individuals and supports rehabilitation'},
  {id:'sp27',emoji:'🌲',name:'Retreat Facilitator',sector:'Faith Leadership',desc:'Designs and leads spiritual retreat experiences for growth and renewal'},
  {id:'sp28',emoji:'✈️',name:'Pilgrimage / Hajj Coordinator',sector:'Administration',desc:'Organises and supervises pilgrimage journeys to sacred sites'},
  {id:'sp29',emoji:'📚',name:'Theologian',sector:'Education & Research',desc:'Conducts academic research on God, faith, and religious tradition'},
  {id:'sp30',emoji:'📖',name:'Religious Scholar',sector:'Education & Research',desc:'Studies and teaches religious texts, history, and comparative faith'},
  {id:'sp31',emoji:'❤️',name:'Faith-Based Social Worker',sector:'Administration',desc:'Provides welfare services through a religious organisation'},
  {id:'sp32',emoji:'🤝',name:'Interfaith Dialogue Officer',sector:'Administration',desc:'Facilitates constructive dialogue between different religious communities'},
  {id:'sp33',emoji:'🏢',name:'Religious NGO Manager',sector:'Administration',desc:'Manages faith-based non-profit programmes and funding'},
  {id:'sp34',emoji:'📋',name:'Church / Mosque Administrator',sector:'Administration',desc:'Handles administrative operations for a house of worship'},
  {id:'sp35',emoji:'🎵',name:'Choir Director',sector:'Faith Leadership',desc:'Trains and conducts choirs for worship and sacred performance'},
  {id:'sp36',emoji:'🎹',name:'Worship Musician',sector:'Faith Leadership',desc:'Leads musical worship through instruments and vocal performance'},
  {id:'sp37',emoji:'📺',name:'Religious Media Producer',sector:'Administration',desc:'Creates broadcasts, podcasts, and digital content for faith audiences'},
  {id:'sp38',emoji:'🎨',name:'Sacred Arts Practitioner',sector:'Traditional Religion',desc:'Creates religious icons, sculptures, and sacred objects for worship'},
  {id:'sp39',emoji:'🗣️',name:'Griot-Spiritual Keeper',sector:'Traditional Religion',desc:'Holds and transmits sacred knowledge through oral heritage tradition'},
  {id:'sp40',emoji:'🎊',name:'Rite of Passage Facilitator',sector:'Traditional Religion',desc:'Guides initiation ceremonies marking life transitions and identity'},
  {id:'sp41',emoji:'👶',name:'Naming Ceremony Officiant',sector:'Traditional Religion',desc:'Presides over traditional ceremonies marking a child\'s entry to community'},
  {id:'sp42',emoji:'💒',name:'Wedding / Funeral Celebrant',sector:'Faith Leadership',desc:'Officiates weddings and funerals according to religious tradition'},
  {id:'sp43',emoji:'🤲',name:'Zakat / Charity Administrator',sector:'Administration',desc:'Manages Islamic charitable giving and distributes funds equitably'},
  {id:'sp44',emoji:'🌍',name:'Faith Community Development Officer',sector:'Administration',desc:'Drives social development projects through faith-based institutions'},
  {id:'sp45',emoji:'💬',name:'Spiritual Counsellor',sector:'Faith Leadership',desc:'Provides guidance on faith, purpose, grief, and life challenges'},
  {id:'sp46',emoji:'🌙',name:'Meditation & Mindfulness Guide',sector:'Faith Leadership',desc:'Teaches contemplative practices for spiritual and mental wellbeing'},
  {id:'sp47',emoji:'⭐',name:'Astrologer / Cosmologist (Traditional)',sector:'Traditional Religion',desc:'Reads celestial signs to guide timing of ceremonies and decisions'},
  {id:'sp48',emoji:'📜',name:'Religious Broadcaster',sector:'Administration',desc:'Hosts or produces faith-based radio and television programming'},
  {id:'sp49',emoji:'🎓',name:'Divinity School Dean',sector:'Education & Research',desc:'Leads an institution dedicated to theological and ministerial education'},
  {id:'sp50',emoji:'🏘️',name:'Community Spiritual Elder',sector:'Traditional Religion',desc:'Provides moral and spiritual counsel rooted in ancestral wisdom'},
],

fashion: [
  {id:'fa01',emoji:'👗',name:'Fashion Designer',sector:'Design & Creation',desc:'Creates original clothing collections for runway and retail'},
  {id:'fa02',emoji:'🎨',name:'Textile Designer',sector:'Design & Creation',desc:'Designs fabric patterns and woven or printed textiles'},
  {id:'fa03',emoji:'🌿',name:'Adire / Batik Specialist',sector:'Design & Creation',desc:'Creates tie-dye and wax-resist fabric patterns from African tradition'},
  {id:'fa04',emoji:'🧶',name:'Kente / Aso-Oke Weaver',sector:'Design & Creation',desc:'Weaves prestige cloth on traditional handlooms for ceremonial use'},
  {id:'fa05',emoji:'✂️',name:'Master Tailor / Seamstress',sector:'Design & Creation',desc:'Cuts and sews garments to measure with expert precision'},
  {id:'fa06',emoji:'📐',name:'Pattern Maker',sector:'Design & Creation',desc:'Creates technical templates for garment cutting and production'},
  {id:'fa07',emoji:'🪡',name:'Embroiderer',sector:'Design & Creation',desc:'Hand and machine embroiders decorative designs on fabric and garments'},
  {id:'fa08',emoji:'📿',name:'Beadwork Artisan',sector:'Design & Creation',desc:'Designs and crafts beaded jewellery, accessories, and embellishments'},
  {id:'fa09',emoji:'👜',name:'Leather Goods Maker',sector:'Design & Creation',desc:'Crafts handbags, belts, wallets, and accessories from leather'},
  {id:'fa10',emoji:'👟',name:'Shoe Designer / Cobbler',sector:'Design & Creation',desc:'Designs and handcrafts footwear in traditional and contemporary styles'},
  {id:'fa11',emoji:'👒',name:'Milliner / Hat Maker',sector:'Design & Creation',desc:'Designs and constructs hats, turbans, and headwear accessories'},
  {id:'fa12',emoji:'💍',name:'Jewellery Designer',sector:'Design & Creation',desc:'Creates necklaces, bangles, and rings using precious and artisan materials'},
  {id:'fa13',emoji:'👜',name:'Accessories Designer',sector:'Design & Creation',desc:'Designs scarves, belts, bags, and complementary fashion accessories'},
  {id:'fa14',emoji:'✏️',name:'Fashion Illustrator',sector:'Design & Creation',desc:'Creates technical and artistic sketches to communicate fashion designs'},
  {id:'fa15',emoji:'🎭',name:'Costume Designer',sector:'Design & Creation',desc:'Creates costumes for film, theatre, television, and events productions'},
  {id:'fa16',emoji:'📸',name:'Fashion Photographer',sector:'Styling & Media',desc:'Captures editorial and commercial fashion photography for publication'},
  {id:'fa17',emoji:'✨',name:'Fashion Stylist',sector:'Styling & Media',desc:'Selects and coordinates outfits for shoots, celebrities, and clients'},
  {id:'fa18',emoji:'🛍️',name:'Personal Shopper',sector:'Styling & Media',desc:'Curates wardrobes and makes fashion purchases on behalf of clients'},
  {id:'fa19',emoji:'💃',name:'Fashion Model',sector:'Styling & Media',desc:'Showcases clothing in runway shows, magazines, and commercial campaigns'},
  {id:'fa20',emoji:'🎬',name:'Runway Director',sector:'Styling & Media',desc:'Choreographs and directs runway fashion shows and presentations'},
  {id:'fa21',emoji:'👥',name:'Casting Director (Fashion)',sector:'Styling & Media',desc:'Selects models and talent for fashion campaigns and runway shows'},
  {id:'fa22',emoji:'🏷️',name:'Brand Manager (Fashion)',sector:'Retail & Commerce',desc:'Develops and protects a fashion label\'s identity and market position'},
  {id:'fa23',emoji:'🏪',name:'Boutique Owner',sector:'Retail & Commerce',desc:'Manages an independent fashion retail store and curates products'},
  {id:'fa24',emoji:'🛒',name:'Retail Fashion Manager',sector:'Retail & Commerce',desc:'Oversees operations and staff at a fashion retail location'},
  {id:'fa25',emoji:'🗂️',name:'Fashion Buyer',sector:'Retail & Commerce',desc:'Selects and purchases clothing lines for retail stores and brands'},
  {id:'fa26',emoji:'🖼️',name:'Visual Merchandiser (Fashion)',sector:'Retail & Commerce',desc:'Designs store layouts and window displays to drive fashion sales'},
  {id:'fa27',emoji:'📣',name:'Fashion Publicist',sector:'Styling & Media',desc:'Secures media coverage and manages press for fashion brands and designers'},
  {id:'fa28',emoji:'📝',name:'Fashion Journalist / Blogger',sector:'Styling & Media',desc:'Writes editorial content covering fashion trends and industry news'},
  {id:'fa29',emoji:'📱',name:'Social Media Fashion Creator',sector:'Styling & Media',desc:'Builds audiences and influences fashion culture on digital platforms'},
  {id:'fa30',emoji:'🛍️',name:'E-commerce Fashion Manager',sector:'Retail & Commerce',desc:'Manages online fashion retail operations, listings, and digital marketing'},
  {id:'fa31',emoji:'♻️',name:'Vintage / Secondhand Curator',sector:'Retail & Commerce',desc:'Sources and sells curated vintage and pre-loved clothing collections'},
  {id:'fa32',emoji:'🌍',name:'Export & Trade Officer (Fashion)',sector:'Retail & Commerce',desc:'Manages international sales and export of African fashion products'},
  {id:'fa33',emoji:'🧵',name:'Fabric Sourcing Agent',sector:'Education & Business',desc:'Identifies and procures fabrics from domestic and international suppliers'},
  {id:'fa34',emoji:'✅',name:'Quality Control Inspector (Fashion)',sector:'Education & Business',desc:'Ensures garments meet quality, finishing, and size specifications'},
  {id:'fa35',emoji:'📋',name:'Fashion Production Manager',sector:'Education & Business',desc:'Oversees all stages of garment manufacturing and delivery schedules'},
  {id:'fa36',emoji:'✂️',name:'Sample Room Manager',sector:'Education & Business',desc:'Manages the creation of garment prototypes and pre-production samples'},
  {id:'fa37',emoji:'💻',name:'Fashion Tech Developer',sector:'Education & Business',desc:'Builds apps, AI-styling tools, and tech solutions for fashion retail'},
  {id:'fa38',emoji:'🌱',name:'Sustainability Officer (Fashion)',sector:'Education & Business',desc:'Drives ethical sourcing, eco-materials, and circular fashion practices'},
  {id:'fa39',emoji:'💡',name:'Fashion Business Consultant',sector:'Education & Business',desc:'Advises fashion entrepreneurs on growth, funding, and strategy'},
  {id:'fa40',emoji:'🎪',name:'Fashion Show Organiser',sector:'Education & Business',desc:'Plans logistics, staging, and branding for fashion event productions'},
  {id:'fa41',emoji:'🌍',name:'Fashion Week Director',sector:'Education & Business',desc:'Leads the organisation of a city-wide fashion week programme'},
  {id:'fa42',emoji:'🎓',name:'Fashion Educator / Lecturer',sector:'Education & Business',desc:'Teaches fashion design, history, and business at academic institutions'},
  {id:'fa43',emoji:'🏫',name:'Fashion School Administrator',sector:'Education & Business',desc:'Manages operations, enrolment, and administration of a fashion school'},
  {id:'fa44',emoji:'💰',name:'Fashion Grant Researcher',sector:'Education & Business',desc:'Identifies funding opportunities and writes grants for designers'},
  {id:'fa45',emoji:'🌐',name:'Cultural Fashion Ambassador',sector:'Styling & Media',desc:'Promotes African and diaspora fashion on the global cultural stage'},
  {id:'fa46',emoji:'🎬',name:'Fashion Film Director',sector:'Styling & Media',desc:'Creates short films and visual campaigns for fashion brands'},
  {id:'fa47',emoji:'📦',name:'Costume Archivist',sector:'Education & Business',desc:'Preserves historical costumes and garments in museum and institutional collections'},
  {id:'fa48',emoji:'🔮',name:'Fashion Trend Forecaster',sector:'Education & Business',desc:'Predicts emerging styles and consumer movements for the industry'},
  {id:'fa49',emoji:'🏭',name:'Garment Factory Supervisor',sector:'Education & Business',desc:'Supervises workers and quality on a garment manufacturing production line'},
  {id:'fa50',emoji:'🤝',name:'Fashion Buying Agent',sector:'Retail & Commerce',desc:'Negotiates with manufacturers and brokers deals for fashion buyers'},
],

family: [
  {id:'fm01',emoji:'👶',name:'Early Childhood Educator',sector:'Childcare & Development',desc:'Nurtures the holistic development of young children aged 0 to 6'},
  {id:'fm02',emoji:'🤱',name:'Childminder / Nanny',sector:'Childcare & Development',desc:'Provides full-time childcare in a home or family setting'},
  {id:'fm03',emoji:'🏫',name:'Nursery School Owner',sector:'Childcare & Development',desc:'Establishes and manages a private nursery or daycare centre'},
  {id:'fm04',emoji:'💬',name:'Family Therapist',sector:'Social Work & Welfare',desc:'Provides counselling to improve family communication and relationships'},
  {id:'fm05',emoji:'🧠',name:'Child Psychologist',sector:'Social Work & Welfare',desc:'Assesses and treats psychological disorders in children and teens'},
  {id:'fm06',emoji:'👶',name:'Paediatric Social Worker',sector:'Social Work & Welfare',desc:'Supports children at risk of abuse, neglect, and family breakdown'},
  {id:'fm07',emoji:'🤝',name:'Adoption Social Worker',sector:'Social Work & Welfare',desc:'Facilitates the legal process of matching children with adoptive families'},
  {id:'fm08',emoji:'🏡',name:'Foster Care Coordinator',sector:'Social Work & Welfare',desc:'Recruits, trains, and supports foster carers for looked-after children'},
  {id:'fm09',emoji:'🛡️',name:'Child Rights Officer',sector:'Social Work & Welfare',desc:'Monitors and enforces laws protecting children\'s rights and wellbeing'},
  {id:'fm10',emoji:'🌱',name:'School Readiness Coach',sector:'Childcare & Development',desc:'Prepares children aged 3 to 5 for the transition into formal schooling'},
  {id:'fm11',emoji:'🤱',name:'Midwife (Family-focused)',sector:'Childcare & Development',desc:'Supports mothers through pregnancy and postnatal family adjustment'},
  {id:'fm12',emoji:'❤️',name:'Postnatal Support Worker',sector:'Childcare & Development',desc:'Provides practical and emotional support to new mothers and parents'},
  {id:'fm13',emoji:'🍼',name:'Breastfeeding Counsellor',sector:'Childcare & Development',desc:'Supports and educates mothers on successful infant breastfeeding'},
  {id:'fm14',emoji:'🏘️',name:'Home Visiting Nurse',sector:'Childcare & Development',desc:'Visits vulnerable families at home to monitor health and development'},
  {id:'fm15',emoji:'📢',name:'Family Health Educator',sector:'Childcare & Development',desc:'Promotes nutrition, hygiene, and preventive health within households'},
  {id:'fm16',emoji:'👴',name:'Elder Care Worker',sector:'Elder Care',desc:'Assists elderly persons with daily living activities and personal care'},
  {id:'fm17',emoji:'🏢',name:'Nursing Home Administrator',sector:'Elder Care',desc:'Manages residential care facilities for the elderly and infirm'},
  {id:'fm18',emoji:'💊',name:'Palliative Care Nurse',sector:'Elder Care',desc:'Provides comfort-focused nursing care for terminally ill patients'},
  {id:'fm19',emoji:'🧓',name:'Geriatric Specialist',sector:'Elder Care',desc:'Provides medical care focused on the health needs of older adults'},
  {id:'fm20',emoji:'🏠',name:'Age-at-Home Caregiver',sector:'Elder Care',desc:'Supports elderly individuals to live independently in their own homes'},
  {id:'fm21',emoji:'⚖️',name:'Family Lawyer',sector:'Legal & Administrative',desc:'Handles divorce, custody, maintenance, and inheritance legal matters'},
  {id:'fm22',emoji:'🤝',name:'Divorce Mediator',sector:'Legal & Administrative',desc:'Facilitates amicable separation agreements between divorcing spouses'},
  {id:'fm23',emoji:'📜',name:'Inheritance / Probate Officer',sector:'Legal & Administrative',desc:'Manages the legal distribution of assets after a person\'s death'},
  {id:'fm24',emoji:'👶',name:'Family Court Social Worker',sector:'Legal & Administrative',desc:'Prepares welfare reports to inform family court decisions'},
  {id:'fm25',emoji:'📋',name:'Child Custody Evaluator',sector:'Legal & Administrative',desc:'Assesses and recommends custody arrangements in the child\'s best interest'},
  {id:'fm26',emoji:'💰',name:'Family Financial Counsellor',sector:'Community & Culture',desc:'Helps families manage debt, budgets, and financial planning'},
  {id:'fm27',emoji:'🏘️',name:'Cooperative Housing Manager',sector:'Community & Culture',desc:'Manages member-owned shared housing communities and estates'},
  {id:'fm28',emoji:'🌍',name:'Community Development Officer',sector:'Community & Culture',desc:'Designs and delivers social development programmes for families'},
  {id:'fm29',emoji:'💑',name:'Marriage Counsellor',sector:'Social Work & Welfare',desc:'Provides therapeutic support to coupled partners navigating conflict'},
  {id:'fm30',emoji:'🌟',name:'Relationship Coach',sector:'Social Work & Welfare',desc:'Coaches individuals and couples to build healthier relationships'},
  {id:'fm31',emoji:'🎊',name:'Rites-of-Passage Facilitator',sector:'Community & Culture',desc:'Guides young people through culturally significant life transitions'},
  {id:'fm32',emoji:'🏺',name:'Cultural Heritage Keeper',sector:'Community & Culture',desc:'Preserves and transmits family lineages, stories, and traditions'},
  {id:'fm33',emoji:'👑',name:'Community Elder / Chief Advisor',sector:'Community & Culture',desc:'Provides wisdom and conflict resolution rooted in community authority'},
  {id:'fm34',emoji:'📦',name:'Family Archive Keeper',sector:'Community & Culture',desc:'Collects and preserves photographs, documents, and family records'},
  {id:'fm35',emoji:'🔍',name:'Genealogy Researcher',sector:'Community & Culture',desc:'Traces and documents family trees and ancestral lineages'},
  {id:'fm36',emoji:'🏠',name:'Household Manager',sector:'Community & Culture',desc:'Manages the operations and budget of a household or compound'},
  {id:'fm37',emoji:'🛡️',name:'Domestic Violence Counsellor',sector:'Social Work & Welfare',desc:'Supports survivors of domestic abuse with safety and recovery plans'},
  {id:'fm38',emoji:'🏠',name:'Safe House Manager',sector:'Social Work & Welfare',desc:'Operates emergency shelters for survivors of family or gender violence'},
  {id:'fm39',emoji:'🌟',name:'Youth Mentor',sector:'Community & Culture',desc:'Guides young people in education, career, and personal development'},
  {id:'fm40',emoji:'🤝',name:'Big Brother / Sister Programme Coordinator',sector:'Community & Culture',desc:'Matches young people with positive adult role models for mentorship'},
  {id:'fm41',emoji:'⚠️',name:'Gender-Based Violence Officer',sector:'Social Work & Welfare',desc:'Delivers programmes preventing and responding to family violence'},
  {id:'fm42',emoji:'🍲',name:'Feeding Programme Coordinator',sector:'Community & Culture',desc:'Manages community feeding initiatives and food security programmes'},
  {id:'fm43',emoji:'🍳',name:'Community Kitchen Manager',sector:'Community & Culture',desc:'Runs shared cooking facilities for community nourishment and solidarity'},
  {id:'fm44',emoji:'📚',name:'Parent Education Facilitator',sector:'Childcare & Development',desc:'Delivers parenting skills workshops in schools and communities'},
  {id:'fm45',emoji:'💻',name:'Family Digital Literacy Trainer',sector:'Childcare & Development',desc:'Teaches online safety and digital tools to families and caregivers'},
  {id:'fm46',emoji:'♿',name:'Disability Support Worker',sector:'Social Work & Welfare',desc:'Assists individuals with disabilities to live full and independent lives'},
  {id:'fm47',emoji:'🤲',name:'Special Needs Family Carer',sector:'Childcare & Development',desc:'Provides intensive care for children or adults with special needs'},
  {id:'fm48',emoji:'🌍',name:'Refugee Family Integration Officer',sector:'Social Work & Welfare',desc:'Helps refugee families rebuild lives and access community services'},
  {id:'fm49',emoji:'🏠',name:'Orphanage Manager',sector:'Social Work & Welfare',desc:'Oversees the residential care and welfare of children without parents'},
  {id:'fm50',emoji:'💛',name:'Foster Parent / Carer',sector:'Childcare & Development',desc:'Provides a loving temporary home for children in the care system'},
],

transport: [
  {id:'tr01',emoji:'✈️',name:'Commercial Airline Pilot',sector:'Aviation',desc:'Commands passenger aircraft on scheduled and charter routes'},
  {id:'tr02',emoji:'🛫',name:'Co-Pilot / First Officer',sector:'Aviation',desc:'Assists the captain in operating aircraft and monitoring systems'},
  {id:'tr03',emoji:'🛎️',name:'Flight Attendant / Cabin Crew',sector:'Aviation',desc:'Ensures passenger safety and comfort throughout the flight'},
  {id:'tr04',emoji:'📡',name:'Air Traffic Controller',sector:'Aviation',desc:'Guides aircraft movements safely through controlled airspace'},
  {id:'tr05',emoji:'🔧',name:'Aviation Mechanic / Engineer',sector:'Aviation',desc:'Inspects, repairs, and certifies aircraft airworthiness'},
  {id:'tr06',emoji:'📋',name:'Aircraft Dispatcher',sector:'Aviation',desc:'Plans flights, files plans, and monitors operational performance'},
  {id:'tr07',emoji:'🛬',name:'Ground Handling Agent',sector:'Aviation',desc:'Manages aircraft turnaround including refuelling and loading'},
  {id:'tr08',emoji:'🏢',name:'Airport Terminal Manager',sector:'Aviation',desc:'Manages passenger terminal operations and service standards'},
  {id:'tr09',emoji:'📦',name:'Cargo / Freight Handler',sector:'Aviation',desc:'Loads, unloads, and manages cargo at airport freight facilities'},
  {id:'tr10',emoji:'🔍',name:'Airport Security Screener',sector:'Aviation',desc:'Screens passengers and baggage at airport security checkpoints'},
  {id:'tr11',emoji:'⚓',name:'Ship Captain / Master Mariner',sector:'Maritime',desc:'Commands and navigates merchant and passenger vessels at sea'},
  {id:'tr12',emoji:'🧭',name:'First Officer (Maritime)',sector:'Maritime',desc:'Assists the captain in vessel navigation and deck operations'},
  {id:'tr13',emoji:'⚙️',name:'Marine Engineer',sector:'Maritime',desc:'Operates and maintains ship propulsion and mechanical systems'},
  {id:'tr14',emoji:'🚢',name:'Port Manager',sector:'Maritime',desc:'Oversees port operations, shipping schedules, and berth allocation'},
  {id:'tr15',emoji:'📝',name:'Customs Clearing Agent (Port)',sector:'Maritime',desc:'Handles import and export documentation at seaport facilities'},
  {id:'tr16',emoji:'🔍',name:'Cargo Surveyor',sector:'Maritime',desc:'Inspects cargo condition, quantity, and compliance at ports'},
  {id:'tr17',emoji:'🏋️',name:'Stevedore / Dockworker',sector:'Maritime',desc:'Loads and unloads cargo from ships at port facilities'},
  {id:'tr18',emoji:'🗺️',name:'Maritime Pilot',sector:'Maritime',desc:'Guides ships safely through ports, channels, and harbours'},
  {id:'tr19',emoji:'🔧',name:'Ship Chandler',sector:'Maritime',desc:'Supplies provisions, spare parts, and equipment to vessels'},
  {id:'tr20',emoji:'🌊',name:'Coastguard Officer',sector:'Maritime',desc:'Enforces maritime law and conducts search-and-rescue operations'},
  {id:'tr21',emoji:'🚛',name:'Long-Haul Truck Driver',sector:'Road Transport',desc:'Transports goods over long distances by road across the continent'},
  {id:'tr22',emoji:'🚌',name:'Bus Driver',sector:'Road Transport',desc:'Operates passenger buses on urban and inter-city routes'},
  {id:'tr23',emoji:'🛵',name:'Boda-Boda / Okada Rider',sector:'Road Transport',desc:'Provides motorcycle taxi services for urban last-mile mobility'},
  {id:'tr24',emoji:'🚖',name:'Taxi / Ride-Hailing Driver',sector:'Road Transport',desc:'Transports passengers on demand using metered or digital platforms'},
  {id:'tr25',emoji:'🚐',name:'Minibus Driver',sector:'Road Transport',desc:'Operates commuter minibuses on set urban and suburban routes'},
  {id:'tr26',emoji:'🏫',name:'Driving Instructor',sector:'Road Transport',desc:'Teaches learners safe vehicle operation and traffic regulations'},
  {id:'tr27',emoji:'🔧',name:'Vehicle Inspector / Mechanic',sector:'Road Transport',desc:'Inspects, diagnoses, and repairs motor vehicles and engines'},
  {id:'tr28',emoji:'🪪',name:'Motor Vehicle Licensing Officer',sector:'Road Transport',desc:'Processes vehicle registration and driver licensing applications'},
  {id:'tr29',emoji:'🚦',name:'Traffic Warden',sector:'Road Transport',desc:'Manages parking enforcement and supports road traffic flow'},
  {id:'tr30',emoji:'🛣️',name:'Road Safety Officer',sector:'Road Transport',desc:'Promotes safe driving practices and investigates road accidents'},
  {id:'tr31',emoji:'🚂',name:'Train Driver / Locomotive Engineer',sector:'Rail',desc:'Operates passenger and freight trains on rail networks'},
  {id:'tr32',emoji:'🏢',name:'Railway Station Master',sector:'Rail',desc:'Manages a train station\'s operations, safety, and customer service'},
  {id:'tr33',emoji:'🛤️',name:'Rail Track Maintenance Worker',sector:'Rail',desc:'Inspects and maintains railway tracks and permanent way infrastructure'},
  {id:'tr34',emoji:'📡',name:'Signalling Engineer (Rail)',sector:'Rail',desc:'Designs and maintains electronic rail signalling and control systems'},
  {id:'tr35',emoji:'🎟️',name:'Ticketing Officer (Rail)',sector:'Rail',desc:'Sells tickets and assists passengers at rail stations and counters'},
  {id:'tr36',emoji:'📊',name:'Logistics Coordinator',sector:'Logistics & Supply Chain',desc:'Plans and coordinates the movement of goods across supply chains'},
  {id:'tr37',emoji:'🚢',name:'Freight Forwarder',sector:'Logistics & Supply Chain',desc:'Arranges multi-modal shipments of goods from origin to destination'},
  {id:'tr38',emoji:'🛵',name:'Last-Mile Delivery Rider',sector:'Logistics & Supply Chain',desc:'Delivers packages to end customers in urban and peri-urban areas'},
  {id:'tr39',emoji:'🏭',name:'Warehouse Operations Manager',sector:'Logistics & Supply Chain',desc:'Oversees receiving, storage, and dispatch operations in warehouses'},
  {id:'tr40',emoji:'🚗',name:'Fleet Manager',sector:'Logistics & Supply Chain',desc:'Manages a company\'s vehicle fleet, maintenance, and driver operations'},
  {id:'tr41',emoji:'📋',name:'Supply Chain Planner',sector:'Logistics & Supply Chain',desc:'Forecasts demand and optimises supply chain flow and inventory'},
  {id:'tr42',emoji:'📦',name:'Courier / Dispatch Rider',sector:'Logistics & Supply Chain',desc:'Delivers documents and parcels quickly across urban areas'},
  {id:'tr43',emoji:'❄️',name:'Cold-Chain Transport Specialist',sector:'Logistics & Supply Chain',desc:'Manages temperature-sensitive cargo for food, pharma, and chemicals'},
  {id:'tr44',emoji:'⛽',name:'Fuel Tanker Driver',sector:'Road Transport',desc:'Transports petroleum products and fuel safely by road tanker'},
  {id:'tr45',emoji:'🔒',name:'Armoured Vehicle Driver',sector:'Road Transport',desc:'Transports cash and valuables in secured armoured vehicles'},
  {id:'tr46',emoji:'🚁',name:'Drone Delivery Operator',sector:'Logistics & Supply Chain',desc:'Operates unmanned drones to deliver medical supplies and parcels'},
  {id:'tr47',emoji:'⚡',name:'Electric Vehicle Technician',sector:'Road Transport',desc:'Maintains and repairs battery-electric and hybrid vehicles'},
  {id:'tr48',emoji:'🏙️',name:'Smart Mobility Planner',sector:'Logistics & Supply Chain',desc:'Designs integrated, data-driven urban transport solutions'},
  {id:'tr49',emoji:'📜',name:'Transport Policy Analyst',sector:'Logistics & Supply Chain',desc:'Researches and advises governments on transport regulation and infrastructure'},
  {id:'tr50',emoji:'🌐',name:'Traffic Engineer',sector:'Road Transport',desc:'Designs traffic management systems and road network improvements'},
],

energy: [
  {id:'en01',emoji:'🛢️',name:'Petroleum Engineer',sector:'Oil & Gas',desc:'Designs systems to extract oil and gas from subsurface reservoirs'},
  {id:'en02',emoji:'⛏️',name:'Drilling Engineer',sector:'Oil & Gas',desc:'Plans and oversees the drilling of oil and gas production wells'},
  {id:'en03',emoji:'🔬',name:'Reservoir Engineer',sector:'Oil & Gas',desc:'Models underground reservoirs to optimise hydrocarbon recovery'},
  {id:'en04',emoji:'🌍',name:'Geologist (Oil & Gas)',sector:'Oil & Gas',desc:'Analyses rock formations to locate subsurface oil and gas deposits'},
  {id:'en05',emoji:'👷',name:'Well Site Supervisor',sector:'Oil & Gas',desc:'Manages drilling crew and operations at oil and gas well sites'},
  {id:'en06',emoji:'🔧',name:'Pipeline Engineer',sector:'Oil & Gas',desc:'Designs, constructs, and maintains oil and gas pipeline systems'},
  {id:'en07',emoji:'🏭',name:'LNG Plant Operator',sector:'Oil & Gas',desc:'Operates liquefied natural gas processing and export facilities'},
  {id:'en08',emoji:'🔧',name:'Oil Refinery Technician',sector:'Oil & Gas',desc:'Operates and maintains petroleum refining equipment and processes'},
  {id:'en09',emoji:'⚠️',name:'HSE Officer (Oil & Gas)',sector:'Oil & Gas',desc:'Manages health, safety, and environmental compliance on oil sites'},
  {id:'en10',emoji:'📊',name:'Petroleum Economist',sector:'Oil & Gas',desc:'Analyses financial viability and market trends in the oil sector'},
  {id:'en11',emoji:'☀️',name:'Solar Energy Engineer',sector:'Renewables',desc:'Designs and installs photovoltaic and solar thermal energy systems'},
  {id:'en12',emoji:'🌬️',name:'Wind Energy Technician',sector:'Renewables',desc:'Installs and services wind turbines for electricity generation'},
  {id:'en13',emoji:'💧',name:'Hydropower Engineer',sector:'Renewables',desc:'Designs and builds hydroelectric power generation infrastructure'},
  {id:'en14',emoji:'🌿',name:'Biomass Energy Specialist',sector:'Renewables',desc:'Develops bioenergy systems using organic waste and agricultural residues'},
  {id:'en15',emoji:'🌋',name:'Geothermal Engineer',sector:'Renewables',desc:'Harnesses subsurface heat for electricity and direct heating use'},
  {id:'en16',emoji:'🔆',name:'Solar System Installer',sector:'Renewables',desc:'Fits and commissions rooftop and ground-mount solar panel systems'},
  {id:'en17',emoji:'🔋',name:'Energy Storage Specialist',sector:'Renewables',desc:'Designs and manages battery and grid-scale energy storage systems'},
  {id:'en18',emoji:'🏘️',name:'Mini-Grid Developer',sector:'Renewables',desc:'Designs and deploys off-grid solar mini-grids for rural communities'},
  {id:'en19',emoji:'🌍',name:'Rural Electrification Officer',sector:'Renewables',desc:'Extends electricity access to underserved and off-grid communities'},
  {id:'en20',emoji:'⚗️',name:'Green Hydrogen Researcher',sector:'Renewables',desc:'Develops hydrogen production technology using renewable energy sources'},
  {id:'en21',emoji:'⚡',name:'Power Plant Operator',sector:'Power Generation & Grid',desc:'Monitors and controls generation equipment at electricity plants'},
  {id:'en22',emoji:'🔌',name:'Grid Engineer (Transmission)',sector:'Power Generation & Grid',desc:'Designs high-voltage power transmission lines and infrastructure'},
  {id:'en23',emoji:'🏗️',name:'Substation Technician',sector:'Power Generation & Grid',desc:'Installs and maintains electrical substations and switchgear'},
  {id:'en24',emoji:'🔍',name:'Electrical Distribution Officer',sector:'Power Generation & Grid',desc:'Manages medium-voltage distribution networks to homes and businesses'},
  {id:'en25',emoji:'📡',name:'Load Dispatch Controller',sector:'Power Generation & Grid',desc:'Balances electricity supply and demand across the national grid'},
  {id:'en26',emoji:'🔍',name:'Energy Auditor',sector:'Energy Services',desc:'Assesses energy consumption and recommends efficiency improvements'},
  {id:'en27',emoji:'💡',name:'Energy Efficiency Consultant',sector:'Energy Services',desc:'Advises organisations on reducing energy use and carbon emissions'},
  {id:'en28',emoji:'📊',name:'Smart Meter Technician',sector:'Energy Services',desc:'Installs and maintains smart meters for real-time energy monitoring'},
  {id:'en29',emoji:'📉',name:'Demand-Side Management Analyst',sector:'Energy Services',desc:'Develops programmes to reduce peak energy demand from consumers'},
  {id:'en30',emoji:'🏢',name:'Facilities Energy Manager',sector:'Energy Services',desc:'Optimises energy use across a company\'s buildings and operations'},
  {id:'en31',emoji:'📜',name:'Energy Policy Analyst',sector:'Policy & Research',desc:'Researches and advises on energy regulation and transition policy'},
  {id:'en32',emoji:'📋',name:'Regulatory Affairs Officer',sector:'Policy & Research',desc:'Ensures compliance with energy sector licensing and regulations'},
  {id:'en33',emoji:'🌱',name:'Carbon Market Specialist',sector:'Policy & Research',desc:'Develops and trades carbon credits and carbon offset projects'},
  {id:'en34',emoji:'🌍',name:'ESG & Climate Finance Officer',sector:'Policy & Research',desc:'Raises and manages green finance for clean energy transitions'},
  {id:'en35',emoji:'📊',name:'Energy Economist',sector:'Policy & Research',desc:'Analyses energy market dynamics, pricing, and investment flows'},
  {id:'en36',emoji:'🫙',name:'LPG Distribution Operator',sector:'Energy Services',desc:'Manages bottled cooking gas supply and distribution networks'},
  {id:'en37',emoji:'⛽',name:'Fuel Retail / Station Manager',sector:'Energy Services',desc:'Manages a petroleum filling station and fuel retail operations'},
  {id:'en38',emoji:'🌿',name:'Biogas Technician',sector:'Renewables',desc:'Installs and maintains biogas digesters for cooking and electricity'},
  {id:'en39',emoji:'⚡',name:'EV Charging Station Operator',sector:'Energy Services',desc:'Manages electric vehicle charging infrastructure and operations'},
  {id:'en40',emoji:'📡',name:'Energy Data Analyst',sector:'Policy & Research',desc:'Analyses energy generation, consumption, and grid performance data'},
  {id:'en41',emoji:'🔧',name:'Power Equipment Maintenance Technician',sector:'Power Generation & Grid',desc:'Services generators, transformers, and grid hardware in the field'},
  {id:'en42',emoji:'🏭',name:'Generator Rental Manager',sector:'Energy Services',desc:'Manages a fleet of diesel generators rented to commercial clients'},
  {id:'en43',emoji:'💼',name:'Energy Sales Representative',sector:'Energy Services',desc:'Sells power purchase agreements and energy solutions to businesses'},
  {id:'en44',emoji:'🏘️',name:'Off-Grid Community Energy Coordinator',sector:'Renewables',desc:'Deploys and maintains renewable energy access for rural communities'},
  {id:'en45',emoji:'📋',name:'Energy Project Manager',sector:'Policy & Research',desc:'Leads the planning and delivery of energy infrastructure projects'},
  {id:'en46',emoji:'⚖️',name:'Power Sector Lawyer',sector:'Policy & Research',desc:'Advises on energy law, licensing, and power purchase agreements'},
  {id:'en47',emoji:'🌡️',name:'Climate Change Officer',sector:'Policy & Research',desc:'Designs and monitors climate adaptation and mitigation programmes'},
  {id:'en48',emoji:'👤',name:'Utility Customer Service Agent',sector:'Energy Services',desc:'Handles billing enquiries and service requests for utility customers'},
  {id:'en49',emoji:'📊',name:'Metering & Billing Specialist',sector:'Energy Services',desc:'Manages electricity metering, bill generation, and revenue collection'},
  {id:'en50',emoji:'🎓',name:'Energy Training Instructor',sector:'Energy Services',desc:'Trains technicians and engineers in energy systems operations'},
],

hospitality: [
  {id:'ho01',emoji:'🏨',name:'Hotel General Manager',sector:'Accommodation',desc:'Provides strategic leadership across all hotel departments and functions'},
  {id:'ho02',emoji:'🛎️',name:'Front Desk Officer',sector:'Accommodation',desc:'Manages guest check-in, check-out, and reservation requests'},
  {id:'ho03',emoji:'🗝️',name:'Concierge',sector:'Accommodation',desc:'Personalises guest experiences and arranges tours, dining, and services'},
  {id:'ho04',emoji:'🧹',name:'Housekeeping Supervisor',sector:'Accommodation',desc:'Manages room cleaning, laundry, and housekeeping team operations'},
  {id:'ho05',emoji:'🛏️',name:'Room Attendant',sector:'Accommodation',desc:'Cleans, services, and maintains hotel rooms to quality standards'},
  {id:'ho06',emoji:'🧳',name:'Bellhop / Porter',sector:'Accommodation',desc:'Greets guests, assists with luggage, and escorts to their rooms'},
  {id:'ho07',emoji:'📋',name:'Reservations Agent',sector:'Accommodation',desc:'Manages room bookings via phone, email, and online platforms'},
  {id:'ho08',emoji:'📊',name:'Revenue Manager (Hotel)',sector:'Accommodation',desc:'Optimises room pricing and availability to maximise hotel revenue'},
  {id:'ho09',emoji:'🔍',name:'Hotel Inspector / Assessor',sector:'Accommodation',desc:'Evaluates hotels against quality and star-rating standards'},
  {id:'ho10',emoji:'🏘️',name:'Airbnb / Short-Let Manager',sector:'Accommodation',desc:'Manages short-term rental properties for digital booking platforms'},
  {id:'ho11',emoji:'👨‍🍳',name:'Head Chef / Executive Chef',sector:'Food & Beverage',desc:'Leads culinary operations and drives a restaurant\'s creative menu'},
  {id:'ho12',emoji:'🍳',name:'Sous Chef',sector:'Food & Beverage',desc:'Supports the head chef and manages the kitchen in their absence'},
  {id:'ho13',emoji:'🎂',name:'Pastry Chef',sector:'Food & Beverage',desc:'Creates breads, cakes, desserts, and pastries for the kitchen'},
  {id:'ho14',emoji:'🍲',name:'Line Cook',sector:'Food & Beverage',desc:'Prepares and plates dishes on an assigned section of the kitchen'},
  {id:'ho15',emoji:'🧼',name:'Kitchen Porter',sector:'Food & Beverage',desc:'Maintains kitchen cleanliness and handles dishwashing duties'},
  {id:'ho16',emoji:'🍽️',name:'Restaurant Manager',sector:'Food & Beverage',desc:'Manages front-of-house operations, staff, and customer experience'},
  {id:'ho17',emoji:'🛎️',name:'Waiter / Waitress',sector:'Food & Beverage',desc:'Takes orders and serves food and beverages to restaurant guests'},
  {id:'ho18',emoji:'🍷',name:'Sommelier / Drinks Specialist',sector:'Food & Beverage',desc:'Advises guests on wines and curates the restaurant beverage list'},
  {id:'ho19',emoji:'☕',name:'Barista',sector:'Food & Beverage',desc:'Prepares and serves speciality coffee and cafe beverages'},
  {id:'ho20',emoji:'🍸',name:'Bartender / Mixologist',sector:'Food & Beverage',desc:'Creates cocktails and manages bar operations and guest service'},
  {id:'ho21',emoji:'🍢',name:'Suya / Street Food Vendor',sector:'Food & Beverage',desc:'Prepares and sells popular African street food in public spaces'},
  {id:'ho22',emoji:'🍱',name:'Catering Manager',sector:'Food & Beverage',desc:'Plans and delivers catering services for events and institutions'},
  {id:'ho23',emoji:'✅',name:'Food Safety Officer (Hospitality)',sector:'Food & Beverage',desc:'Ensures food handling, hygiene, and storage meet health standards'},
  {id:'ho24',emoji:'🎪',name:'Event Manager',sector:'Events',desc:'Plans and coordinates corporate and social events end-to-end'},
  {id:'ho25',emoji:'💒',name:'Wedding Planner',sector:'Events',desc:'Designs and manages all elements of traditional and modern weddings'},
  {id:'ho26',emoji:'🎤',name:'Conference & Banqueting Manager',sector:'Events',desc:'Manages meeting rooms, banquet halls, and event client logistics'},
  {id:'ho27',emoji:'🎊',name:'Event Decorator',sector:'Events',desc:'Designs and sets up venue decorations and thematic installations'},
  {id:'ho28',emoji:'🎭',name:'Entertainment Coordinator',sector:'Events',desc:'Books and manages performers, DJs, and entertainment acts for events'},
  {id:'ho29',emoji:'🎧',name:'DJ (Events)',sector:'Events',desc:'Provides music for weddings, corporate functions, and club events'},
  {id:'ho30',emoji:'🌍',name:'Tour Guide',sector:'Tourism',desc:'Leads visitors on guided cultural, historical, and city tours'},
  {id:'ho31',emoji:'🦁',name:'Safari Guide',sector:'Tourism',desc:'Leads wildlife safari tours and educates visitors on nature conservation'},
  {id:'ho32',emoji:'🏛️',name:'Cultural Tourism Officer',sector:'Tourism',desc:'Develops and promotes cultural heritage tourism programmes and routes'},
  {id:'ho33',emoji:'🌿',name:'Eco-Tourism Specialist',sector:'Tourism',desc:'Creates sustainable nature-based tourism experiences and products'},
  {id:'ho34',emoji:'✈️',name:'Travel Agent',sector:'Tourism',desc:'Plans and books travel itineraries, tickets, and accommodation'},
  {id:'ho35',emoji:'📣',name:'Destination Marketing Officer',sector:'Tourism',desc:'Promotes tourist destinations through campaigns and trade shows'},
  {id:'ho36',emoji:'📊',name:'Hotel Marketing Manager',sector:'Accommodation',desc:'Drives hotel brand awareness and direct bookings through marketing'},
  {id:'ho37',emoji:'📱',name:'Social Media Manager (Hospitality)',sector:'Accommodation',desc:'Manages brand presence and guest engagement on digital platforms'},
  {id:'ho38',emoji:'🎓',name:'Hospitality Trainer / Educator',sector:'Accommodation',desc:'Delivers professional hospitality and customer service training'},
  {id:'ho39',emoji:'🧹',name:'Housekeeping Manager',sector:'Accommodation',desc:'Leads the housekeeping department and maintains room quality standards'},
  {id:'ho40',emoji:'👘',name:'Linen Room Attendant',sector:'Accommodation',desc:'Manages laundry, linen inventory, and room supply operations'},
  {id:'ho41',emoji:'🔧',name:'Facilities Manager (Hotel)',sector:'Accommodation',desc:'Maintains engineering, plumbing, electrical, and HVAC hotel systems'},
  {id:'ho42',emoji:'🏊',name:'Pool Attendant / Lifeguard',sector:'Accommodation',desc:'Supervises pool safety and maintains aquatic facility condition'},
  {id:'ho43',emoji:'💆',name:'Spa Therapist',sector:'Accommodation',desc:'Delivers massage, beauty, and wellness treatments for hotel guests'},
  {id:'ho44',emoji:'🏋️',name:'Fitness Centre Instructor',sector:'Accommodation',desc:'Trains guests and manages hotel gym and wellness facilities'},
  {id:'ho45',emoji:'🚗',name:'Shuttle & Transfer Driver',sector:'Accommodation',desc:'Transports guests between hotel, airports, and attractions'},
  {id:'ho46',emoji:'🌙',name:'Night Auditor',sector:'Accommodation',desc:'Reconciles daily hotel transactions and produces financial reports'},
  {id:'ho47',emoji:'💻',name:'Hospitality IT Specialist',sector:'Accommodation',desc:'Manages property management systems and hotel technology platforms'},
  {id:'ho48',emoji:'🛒',name:'Hospitality Procurement Officer',sector:'Accommodation',desc:'Sources and purchases food, beverage, and operational supplies'},
  {id:'ho49',emoji:'🛡️',name:'Security Officer (Hotel)',sector:'Accommodation',desc:'Ensures guest and staff security across the hotel property'},
  {id:'ho50',emoji:'🍛',name:'African Cuisine Chef',sector:'Food & Beverage',desc:'Specialises in authentic African dishes from across the continent'},
],

government: [
  {id:'go01',emoji:'🏛️',name:'President / Head of State',sector:'Executive & Legislative',desc:'Leads the nation as the chief executive and head of government'},
  {id:'go02',emoji:'👔',name:'Vice President',sector:'Executive & Legislative',desc:'Supports the president and assumes leadership in their absence'},
  {id:'go03',emoji:'📋',name:'Cabinet Minister',sector:'Executive & Legislative',desc:'Leads a government ministry and implements national policy'},
  {id:'go04',emoji:'👔',name:'Permanent Secretary',sector:'Public Administration',desc:'Manages the administration of a government ministry'},
  {id:'go05',emoji:'🏢',name:'Director-General',sector:'Public Administration',desc:'Leads a government agency or department at director level'},
  {id:'go06',emoji:'⚖️',name:'Senator / Member of Parliament',sector:'Executive & Legislative',desc:'Represents citizens in the national legislative assembly'},
  {id:'go07',emoji:'🌍',name:'State Governor',sector:'Executive & Legislative',desc:'Leads a state or provincial government and its administration'},
  {id:'go08',emoji:'🏘️',name:'Local Government Chairman',sector:'Local Government',desc:'Heads a local government council and delivers community services'},
  {id:'go09',emoji:'🗣️',name:'Councillor / Ward Representative',sector:'Local Government',desc:'Represents ward constituents on the local government council'},
  {id:'go10',emoji:'📣',name:'Political Party Officer',sector:'Executive & Legislative',desc:'Manages political party organisation, campaigns, and membership'},
  {id:'go11',emoji:'🌐',name:'Ambassador / High Commissioner',sector:'Diplomacy',desc:'Represents the nation at the highest level in a foreign country'},
  {id:'go12',emoji:'🌍',name:'Deputy Ambassador',sector:'Diplomacy',desc:'Assists the ambassador and leads missions in their absence'},
  {id:'go13',emoji:'✈️',name:'Diplomat / Foreign Service Officer',sector:'Diplomacy',desc:'Manages bilateral relations and national interests abroad'},
  {id:'go14',emoji:'📋',name:'Consular Officer',sector:'Diplomacy',desc:'Assists citizens abroad and processes visa and travel documents'},
  {id:'go15',emoji:'🤝',name:'Protocol Officer',sector:'Diplomacy',desc:'Manages official state visits, ceremonies, and diplomatic etiquette'},
  {id:'go16',emoji:'📁',name:'Civil Servant',sector:'Public Administration',desc:'Implements government policy and delivers public services'},
  {id:'go17',emoji:'👔',name:'Administrative Officer',sector:'Public Administration',desc:'Manages correspondence, records, and administrative operations'},
  {id:'go18',emoji:'📊',name:'Policy Analyst',sector:'Public Administration',desc:'Researches issues and develops evidence-based policy recommendations'},
  {id:'go19',emoji:'💰',name:'Budget Officer',sector:'Public Administration',desc:'Prepares and monitors government financial plans and appropriations'},
  {id:'go20',emoji:'🛒',name:'Public Procurement Officer',sector:'Public Administration',desc:'Manages transparent and competitive public sector tendering processes'},
  {id:'go21',emoji:'🏘️',name:'Local Government Administrator',sector:'Local Government',desc:'Manages day-to-day administration of a local government council'},
  {id:'go22',emoji:'📜',name:'Town Clerk',sector:'Local Government',desc:'Serves as the principal administrative officer of a local council'},
  {id:'go23',emoji:'🌍',name:'District Commissioner',sector:'Local Government',desc:'Coordinates government services and security across a district'},
  {id:'go24',emoji:'🏗️',name:'Community Development Officer',sector:'Local Government',desc:'Plans and implements social projects in rural and urban communities'},
  {id:'go25',emoji:'🗺️',name:'Lands & Survey Officer',sector:'Local Government',desc:'Manages land registration, allocation, and boundary disputes'},
  {id:'go26',emoji:'💵',name:'Revenue Collection Officer',sector:'Local Government',desc:'Collects taxes, levies, and fees for local government revenue'},
  {id:'go27',emoji:'📋',name:'Vital Statistics Registrar',sector:'Local Government',desc:'Registers births, deaths, and marriages for official record keeping'},
  {id:'go28',emoji:'🏥',name:'Public Health Authority Officer',sector:'Public Administration',desc:'Enforces public health laws and coordinates disease outbreak response'},
  {id:'go29',emoji:'🌿',name:'Environmental Regulatory Officer',sector:'Public Administration',desc:'Monitors and enforces environmental protection laws and standards'},
  {id:'go30',emoji:'🚦',name:'Transport Regulatory Officer',sector:'Public Administration',desc:'Regulates road transport operators, vehicles, and road safety'},
  {id:'go31',emoji:'🛂',name:'Immigration Officer',sector:'Public Services',desc:'Processes visas, residency, and citizenship applications'},
  {id:'go32',emoji:'📘',name:'Passport Officer',sector:'Public Services',desc:'Issues travel documents and verifies identity for applications'},
  {id:'go33',emoji:'🪪',name:'National ID Registration Officer',sector:'Public Services',desc:'Registers citizens and issues national identity documents'},
  {id:'go34',emoji:'🗳️',name:'Electoral Commission Officer',sector:'Public Services',desc:'Organises elections and ensures transparent ballot processes'},
  {id:'go35',emoji:'📢',name:'Government Spokesperson',sector:'Diplomacy',desc:'Communicates official government positions to the media and public'},
  {id:'go36',emoji:'📰',name:'State House Correspondent',sector:'Diplomacy',desc:'Covers government and executive branch activities for the media'},
  {id:'go37',emoji:'📜',name:'Parliamentary Journalist',sector:'Executive & Legislative',desc:'Reports on legislative proceedings and parliamentary debates'},
  {id:'go38',emoji:'🏘️',name:'Constituency Outreach Officer',sector:'Executive & Legislative',desc:'Manages engagement between parliamentarians and their constituents'},
  {id:'go39',emoji:'📋',name:'Legislative Research Assistant',sector:'Executive & Legislative',desc:'Provides research and analysis support to parliamentarians'},
  {id:'go40',emoji:'⚖️',name:'Parliamentary Counsel',sector:'Executive & Legislative',desc:'Drafts and advises on legislation before parliament'},
  {id:'go41',emoji:'📜',name:'Government Lawyer',sector:'Public Administration',desc:'Provides legal advice and representation for government ministries'},
  {id:'go42',emoji:'⚖️',name:'Solicitor-General',sector:'Public Administration',desc:'Represents the government in major legal proceedings and appeals'},
  {id:'go43',emoji:'🏛️',name:'Attorney-General',sector:'Public Administration',desc:'Heads the nation\'s legal system and advises the government on law'},
  {id:'go44',emoji:'🔍',name:'Auditor-General',sector:'Public Administration',desc:'Independently audits government accounts and public expenditures'},
  {id:'go45',emoji:'💰',name:'Comptroller',sector:'Public Administration',desc:'Controls government financial transactions and treasury operations'},
  {id:'go46',emoji:'📢',name:'Information Commissioner',sector:'Public Administration',desc:'Enforces freedom of information and data access laws'},
  {id:'go47',emoji:'🛡️',name:'Data Protection Officer (Government)',sector:'Public Administration',desc:'Ensures government data is handled lawfully and securely'},
  {id:'go48',emoji:'🤝',name:'International Aid Coordinator',sector:'Diplomacy',desc:'Manages relationships with international donors and aid agencies'},
  {id:'go49',emoji:'📊',name:'National Planning Officer',sector:'Public Administration',desc:'Develops national development plans and strategic frameworks'},
  {id:'go50',emoji:'🔧',name:'Public Service Reform Officer',sector:'Public Administration',desc:'Designs and implements improvements to public service delivery'},
],

sports: [
  {id:'so01',emoji:'⚽',name:'Professional Footballer',sector:'Team Sports',desc:'Plays football at professional club or national team level'},
  {id:'so02',emoji:'🧑‍💼',name:'Football Coach / Manager',sector:'Team Sports',desc:'Leads training and match-day strategy for a football team'},
  {id:'so03',emoji:'🧤',name:'Goalkeeper Coach',sector:'Team Sports',desc:'Develops goalkeeping technique and decision-making skills'},
  {id:'so04',emoji:'🏀',name:'Basketball Player',sector:'Team Sports',desc:'Competes at professional or elite amateur basketball level'},
  {id:'so05',emoji:'🎯',name:'Basketball Coach',sector:'Team Sports',desc:'Develops team tactics and player performance in basketball'},
  {id:'so06',emoji:'🏉',name:'Rugby Player',sector:'Team Sports',desc:'Competes in union or league rugby at club or national level'},
  {id:'so07',emoji:'🏏',name:'Cricket Player',sector:'Team Sports',desc:'Plays competitive cricket as a batsman, bowler, or all-rounder'},
  {id:'so08',emoji:'🎯',name:'Cricket Coach',sector:'Team Sports',desc:'Coaches batting, bowling, and fielding technique in cricket'},
  {id:'so09',emoji:'🏐',name:'Volleyball Player',sector:'Team Sports',desc:'Competes in indoor or beach volleyball at a competitive level'},
  {id:'so10',emoji:'🏃',name:'Track & Field Athlete',sector:'Individual Sports',desc:'Competes in running, jumping, or throwing field events'},
  {id:'so11',emoji:'🏃',name:'Athletics Coach',sector:'Individual Sports',desc:'Trains sprinters, distance runners, and field event athletes'},
  {id:'so12',emoji:'🏊',name:'Swimmer',sector:'Individual Sports',desc:'Competes in competitive swimming across multiple disciplines'},
  {id:'so13',emoji:'🏊',name:'Swimming Coach',sector:'Individual Sports',desc:'Develops stroke technique and racing performance for swimmers'},
  {id:'so14',emoji:'🥊',name:'Boxer',sector:'Individual Sports',desc:'Competes in amateur or professional boxing weight categories'},
  {id:'so15',emoji:'🥊',name:'Boxing Trainer',sector:'Individual Sports',desc:'Develops boxing technique, fitness, and fight strategy for athletes'},
  {id:'so16',emoji:'🤼',name:'Wrestler (Freestyle / Traditional)',sector:'Individual Sports',desc:'Competes in Greco-Roman, traditional, or freestyle wrestling'},
  {id:'so17',emoji:'🥋',name:'Martial Artist',sector:'Individual Sports',desc:'Trains and competes in judo, taekwondo, karate, or capoeira'},
  {id:'so18',emoji:'🏋️',name:'Weightlifter',sector:'Individual Sports',desc:'Competes in snatch and clean-and-jerk at national and international level'},
  {id:'so19',emoji:'🚴',name:'Road Race Cyclist',sector:'Individual Sports',desc:'Competes in road cycling time trials and stage races'},
  {id:'so20',emoji:'🎾',name:'Tennis Player',sector:'Individual Sports',desc:'Competes on clay, grass, and hard tennis courts globally'},
  {id:'so21',emoji:'🎾',name:'Tennis Coach',sector:'Individual Sports',desc:'Develops tennis technique, movement, and match strategy'},
  {id:'so22',emoji:'🏸',name:'Badminton Player',sector:'Individual Sports',desc:'Competes in singles and doubles badminton tournaments'},
  {id:'so23',emoji:'🏓',name:'Table Tennis Player',sector:'Individual Sports',desc:'Competes in national and international table tennis competitions'},
  {id:'so24',emoji:'⛳',name:'Golfer',sector:'Individual Sports',desc:'Plays professional or amateur golf on courses across Africa'},
  {id:'so25',emoji:'🚶',name:'Golf Caddie',sector:'Individual Sports',desc:'Carries clubs and advises golfers on course strategy and conditions'},
  {id:'so26',emoji:'🏐',name:'Beach Volleyball Player',sector:'Individual Sports',desc:'Competes in sand-based two-person volleyball competitions'},
  {id:'so27',emoji:'🧑‍⚕️',name:'Sports Physiotherapist',sector:'Support & Science',desc:'Treats and rehabilitates sports injuries for athletes'},
  {id:'so28',emoji:'⚕️',name:'Sports Doctor / Team Physician',sector:'Support & Science',desc:'Provides medical care and prescreening for athletes'},
  {id:'so29',emoji:'🧠',name:'Sports Psychologist',sector:'Support & Science',desc:'Develops mental resilience and focus strategies for athletes'},
  {id:'so30',emoji:'💪',name:'Strength & Conditioning Coach',sector:'Support & Science',desc:'Develops physical power, speed, and fitness in elite athletes'},
  {id:'so31',emoji:'🥗',name:'Sports Nutritionist',sector:'Support & Science',desc:'Designs performance diets and recovery nutrition for athletes'},
  {id:'so32',emoji:'🟨',name:'Referee / Umpire',sector:'Support & Science',desc:'Enforces rules and officiates competitive sporting events'},
  {id:'so33',emoji:'📊',name:'Sports Data Analyst',sector:'Support & Science',desc:'Analyses performance statistics to inform training and tactics'},
  {id:'so34',emoji:'🎬',name:'Video Analyst',sector:'Support & Science',desc:'Records and reviews match footage to identify tactical insights'},
  {id:'so35',emoji:'🔍',name:'Scout / Talent Identifier',sector:'Support & Science',desc:'Discovers and recommends emerging young talent for recruitment'},
  {id:'so36',emoji:'📋',name:'Sports Administrator',sector:'Media & Business',desc:'Manages club or federation administration and competition planning'},
  {id:'so37',emoji:'🏟️',name:'Athletic Director',sector:'Media & Business',desc:'Provides strategic leadership for a sports organisation or federation'},
  {id:'so38',emoji:'🏟️',name:'Stadium Manager',sector:'Media & Business',desc:'Oversees stadium operations, safety, and event day management'},
  {id:'so39',emoji:'📣',name:'Sports Marketing Manager',sector:'Media & Business',desc:'Develops brand partnerships and commercial events in sport'},
  {id:'so40',emoji:'🤝',name:'Sports Agent / Manager',sector:'Media & Business',desc:'Represents and negotiates commercial contracts for athletes'},
  {id:'so41',emoji:'💰',name:'Sponsorship Manager (Sport)',sector:'Media & Business',desc:'Secures and manages corporate sponsorships for clubs and events'},
  {id:'so42',emoji:'📺',name:'Sports Broadcaster / Commentator',sector:'Media & Business',desc:'Provides live commentary and analysis for broadcast media'},
  {id:'so43',emoji:'📰',name:'Sports Journalist',sector:'Media & Business',desc:'Reports on sporting events and athlete news for media outlets'},
  {id:'so44',emoji:'📱',name:'Social Media Sports Creator',sector:'Media & Business',desc:'Produces viral sports content for digital and social platforms'},
  {id:'so45',emoji:'👶',name:'Youth Development Coach',sector:'Grassroots',desc:'Develops football, basketball, and athletic skills in young people'},
  {id:'so46',emoji:'🏫',name:'School Sports Coordinator',sector:'Grassroots',desc:'Manages inter-school sports competitions and physical education'},
  {id:'so47',emoji:'🌍',name:'Grassroots Football Organiser',sector:'Grassroots',desc:'Runs community leagues and academies for young players'},
  {id:'so48',emoji:'🏋️',name:'Community Fitness Trainer',sector:'Grassroots',desc:'Delivers affordable group fitness and wellness classes locally'},
  {id:'so49',emoji:'🏊',name:'Swim School Operator',sector:'Grassroots',desc:'Runs swimming lessons and water safety programmes for all ages'},
  {id:'so50',emoji:'♟️',name:'Chess Coach / Educator',sector:'Grassroots',desc:'Teaches chess strategy and critical thinking to youth and adults'},
],

holdings: [
  {id:'hl01',emoji:'🏛️',name:'Holding Company Director',sector:'Investment & Private Equity',desc:'Provides strategic governance across a portfolio of subsidiaries'},
  {id:'hl02',emoji:'👔',name:'Chief Executive Officer',sector:'Corporate Services',desc:'Sets the vision and leads the overall direction of a corporation'},
  {id:'hl03',emoji:'⚙️',name:'Chief Operating Officer',sector:'Corporate Services',desc:'Oversees day-to-day operations and execution across business units'},
  {id:'hl04',emoji:'💰',name:'Chief Financial Officer',sector:'Corporate Services',desc:'Leads financial strategy, reporting, and investor relations'},
  {id:'hl05',emoji:'🎯',name:'Chief Strategy Officer',sector:'Corporate Services',desc:'Develops and coordinates long-term corporate strategy and growth'},
  {id:'hl06',emoji:'👑',name:'Board Chairman',sector:'Governance',desc:'Chairs the board of directors and ensures corporate governance'},
  {id:'hl07',emoji:'📋',name:'Non-Executive Director',sector:'Governance',desc:'Provides independent oversight and governance on a company board'},
  {id:'hl08',emoji:'📜',name:'Company Secretary',sector:'Governance',desc:'Manages board administration, compliance, and legal filings'},
  {id:'hl09',emoji:'⚖️',name:'Corporate Lawyer',sector:'Corporate Services',desc:'Advises on corporate law, transactions, and regulatory compliance'},
  {id:'hl10',emoji:'🤝',name:'M&A Analyst',sector:'Investment & Private Equity',desc:'Evaluates mergers, acquisitions, and strategic transactions'},
  {id:'hl11',emoji:'💹',name:'Private Equity Analyst',sector:'Investment & Private Equity',desc:'Analyses fund investments across portfolio company opportunities'},
  {id:'hl12',emoji:'🌱',name:'Venture Capital Analyst',sector:'Investment & Private Equity',desc:'Evaluates and supports early-stage startup investments'},
  {id:'hl13',emoji:'💼',name:'Angel Investor Relations Manager',sector:'Investment & Private Equity',desc:'Manages communication with angel and high-net-worth investors'},
  {id:'hl14',emoji:'🗂️',name:'Investment Committee Member',sector:'Investment & Private Equity',desc:'Reviews and approves investment decisions at governance level'},
  {id:'hl15',emoji:'🏢',name:'Portfolio Company Manager',sector:'Investment & Private Equity',desc:'Leads the operational performance of a portfolio group company'},
  {id:'hl16',emoji:'🏠',name:'Real Estate Investment Manager',sector:'Real Estate',desc:'Manages property acquisitions, disposals, and income optimisation'},
  {id:'hl17',emoji:'📊',name:'REIT Analyst',sector:'Real Estate',desc:'Analyses Real Estate Investment Trust performance and assets'},
  {id:'hl18',emoji:'🏗️',name:'Property Developer',sector:'Real Estate',desc:'Manages land acquisition and commercial or residential development'},
  {id:'hl19',emoji:'📈',name:'Asset Manager',sector:'Real Estate',desc:'Maximises the value and return of real estate and investment assets'},
  {id:'hl20',emoji:'🗺️',name:'Land Acquisition Officer',sector:'Real Estate',desc:'Identifies, negotiates, and secures land for development projects'},
  {id:'hl21',emoji:'✅',name:'Corporate Governance Officer',sector:'Governance',desc:'Ensures the organisation adheres to governance frameworks and codes'},
  {id:'hl22',emoji:'🔍',name:'Compliance Director',sector:'Governance',desc:'Leads regulatory compliance programmes across group operations'},
  {id:'hl23',emoji:'⚠️',name:'Risk Director',sector:'Governance',desc:'Identifies and mitigates strategic, operational, and financial risks'},
  {id:'hl24',emoji:'🔎',name:'Internal Auditor',sector:'Governance',desc:'Reviews systems and controls to ensure operational integrity'},
  {id:'hl25',emoji:'📋',name:'External Auditor',sector:'Governance',desc:'Independently verifies group financial statements for stakeholders'},
  {id:'hl26',emoji:'💰',name:'Treasury Director',sector:'Corporate Services',desc:'Manages group liquidity, funding, and foreign exchange operations'},
  {id:'hl27',emoji:'📒',name:'Group Accountant',sector:'Corporate Services',desc:'Produces consolidated group accounts and financial reports'},
  {id:'hl28',emoji:'📜',name:'Tax Director',sector:'Corporate Services',desc:'Manages group tax strategy, planning, and cross-border compliance'},
  {id:'hl29',emoji:'📣',name:'Investor Relations Officer',sector:'Corporate Services',desc:'Communicates financial results and strategy to shareholders'},
  {id:'hl30',emoji:'📋',name:'Shareholder Services Manager',sector:'Corporate Services',desc:'Manages shareholder registers, dividends, and AGM processes'},
  {id:'hl31',emoji:'🗣️',name:'Corporate Communications Director',sector:'Corporate Services',desc:'Leads external communications, media, and reputation management'},
  {id:'hl32',emoji:'📰',name:'Group PR Manager',sector:'Corporate Services',desc:'Manages media relations and public communications for the group'},
  {id:'hl33',emoji:'👥',name:'HR Director (Group)',sector:'Corporate Services',desc:'Provides strategic human resources leadership for the entire group'},
  {id:'hl34',emoji:'🔍',name:'Talent Acquisition Lead',sector:'Corporate Services',desc:'Leads executive and specialist recruitment across group companies'},
  {id:'hl35',emoji:'🎓',name:'Learning & Development Director',sector:'Corporate Services',desc:'Designs and delivers organisation-wide learning and leadership programmes'},
  {id:'hl36',emoji:'💻',name:'Group IT Director',sector:'Corporate Services',desc:'Oversees technology strategy and digital infrastructure group-wide'},
  {id:'hl37',emoji:'🔄',name:'Digital Transformation Lead',sector:'Corporate Services',desc:'Leads enterprise-wide adoption of digital tools and processes'},
  {id:'hl38',emoji:'🛒',name:'Group Procurement Director',sector:'Corporate Services',desc:'Leads procurement strategy and vendor management for the group'},
  {id:'hl39',emoji:'🌐',name:'Supply Chain Director',sector:'Corporate Services',desc:'Oversees end-to-end supply chain optimisation and resilience'},
  {id:'hl40',emoji:'🌱',name:'Sustainability Director',sector:'Governance',desc:'Leads ESG strategy, reporting, and sustainability programme delivery'},
  {id:'hl41',emoji:'🌍',name:'ESG Officer',sector:'Governance',desc:'Measures and improves environmental, social, and governance metrics'},
  {id:'hl42',emoji:'📣',name:'Group Marketing Director',sector:'Corporate Services',desc:'Leads brand marketing strategy across all group business units'},
  {id:'hl43',emoji:'🏷️',name:'Brand Strategist',sector:'Corporate Services',desc:'Develops brand positioning and architecture for group companies'},
  {id:'hl44',emoji:'🤝',name:'Group Sales Director',sector:'Corporate Services',desc:'Drives commercial performance and revenue growth group-wide'},
  {id:'hl45',emoji:'🗺️',name:'New Markets Director',sector:'Investment & Private Equity',desc:'Identifies and enters new geographical and sector investment markets'},
  {id:'hl46',emoji:'📊',name:'Business Intelligence Director',sector:'Corporate Services',desc:'Leads data analytics to drive evidence-based strategic decisions'},
  {id:'hl47',emoji:'📡',name:'Data & Analytics Director',sector:'Corporate Services',desc:'Manages the group\'s data governance, platforms, and analytics capability'},
  {id:'hl48',emoji:'⚖️',name:'Group Legal Counsel',sector:'Governance',desc:'Provides in-house legal advisory to all group companies and boards'},
  {id:'hl49',emoji:'📜',name:'Regulatory Affairs Director',sector:'Governance',desc:'Monitors and manages regulatory relationships and licence obligations'},
  {id:'hl50',emoji:'💼',name:'Family Office Manager',sector:'Investment & Private Equity',desc:'Manages financial and administrative affairs for a wealthy family'},
],

}
