export interface VillageRole { id:string; emoji:string; name:string; sector:string; desc:string }

export const VILLAGE_ROLES_PART1: Record<string, VillageRole[]> = {

health: [
  {id:'h01',emoji:'👨‍⚕️',name:'Medical Doctor',sector:'Clinical',desc:'Diagnoses and treats illness across all patient groups'},
  {id:'h02',emoji:'🔬',name:'Specialist Physician',sector:'Clinical',desc:'Provides advanced care in a focused medical specialty'},
  {id:'h03',emoji:'🏥',name:'General Surgeon',sector:'Clinical',desc:'Performs operations on organs, bones, and soft tissue'},
  {id:'h04',emoji:'🧒',name:'Pediatrician',sector:'Clinical',desc:'Provides medical care for infants, children, and teens'},
  {id:'h05',emoji:'👶',name:'Obstetrician / Gynaecologist',sector:'Clinical',desc:'Manages pregnancy, childbirth, and female reproductive health'},
  {id:'h06',emoji:'🧠',name:'Psychiatrist',sector:'Clinical',desc:'Diagnoses and treats mental health and behavioural disorders'},
  {id:'h07',emoji:'❤️',name:'Cardiologist',sector:'Clinical',desc:'Specialises in heart and cardiovascular system disorders'},
  {id:'h08',emoji:'🫁',name:'Pulmonologist',sector:'Clinical',desc:'Diagnoses and manages respiratory and lung diseases'},
  {id:'h09',emoji:'🦴',name:'Orthopedic Surgeon',sector:'Clinical',desc:'Treats musculoskeletal injuries, joints, and spine conditions'},
  {id:'h10',emoji:'🌡️',name:'Emergency Medicine Doctor',sector:'Clinical',desc:'Delivers immediate care for acute and critical conditions'},
  {id:'h11',emoji:'👁️',name:'Ophthalmologist',sector:'Clinical',desc:'Diagnoses and treats eye diseases and vision disorders'},
  {id:'h12',emoji:'🩻',name:'Radiologist',sector:'Clinical',desc:'Interprets medical images to guide diagnosis and treatment'},
  {id:'h13',emoji:'💉',name:'Anaesthetist',sector:'Clinical',desc:'Administers anaesthesia and monitors patients during surgery'},
  {id:'h14',emoji:'🧪',name:'Pathologist',sector:'Clinical',desc:'Studies disease through lab analysis of tissue and fluids'},
  {id:'h15',emoji:'🩺',name:'Neurologist',sector:'Clinical',desc:'Diagnoses and manages disorders of the nervous system'},
  {id:'h16',emoji:'👩‍⚕️',name:'Registered Nurse',sector:'Nursing',desc:'Provides direct patient care and coordinates treatment plans'},
  {id:'h17',emoji:'🤱',name:'Midwife',sector:'Nursing',desc:'Supports women through pregnancy, labour, and postnatal care'},
  {id:'h18',emoji:'🏘️',name:'Community Health Nurse',sector:'Nursing',desc:'Delivers preventive care and health education in communities'},
  {id:'h19',emoji:'🏨',name:'ICU Nurse',sector:'Nursing',desc:'Provides intensive monitoring and care for critical patients'},
  {id:'h20',emoji:'🩹',name:'Ward Sister / Charge Nurse',sector:'Nursing',desc:'Leads a hospital ward team and manages patient flow'},
  {id:'h21',emoji:'💊',name:'Pharmacist',sector:'Pharmacy',desc:'Dispenses medication and counsels patients on drug therapy'},
  {id:'h22',emoji:'🏪',name:'Pharmacy Technician',sector:'Pharmacy',desc:'Assists pharmacists in preparing and dispensing prescriptions'},
  {id:'h23',emoji:'🚛',name:'Drug Supply Chain Officer',sector:'Pharmacy',desc:'Manages procurement and distribution of essential medicines'},
  {id:'h24',emoji:'🌿',name:'Traditional Herbalist',sector:'Traditional Medicine',desc:'Uses plant-based remedies rooted in African healing traditions'},
  {id:'h25',emoji:'👵',name:'Traditional Birth Attendant',sector:'Traditional Medicine',desc:'Supports community childbirth using indigenous practices'},
  {id:'h26',emoji:'🌱',name:'Naturopath',sector:'Traditional Medicine',desc:'Integrates natural and evidence-based therapeutic approaches'},
  {id:'h27',emoji:'🦿',name:'Physiotherapist',sector:'Allied Health',desc:'Restores movement and function through rehabilitative therapy'},
  {id:'h28',emoji:'🗣️',name:'Speech Therapist',sector:'Allied Health',desc:'Assesses and treats speech, language, and swallowing disorders'},
  {id:'h29',emoji:'🥗',name:'Clinical Nutritionist',sector:'Allied Health',desc:'Designs therapeutic diets to manage and prevent disease'},
  {id:'h30',emoji:'🔭',name:'Medical Laboratory Scientist',sector:'Allied Health',desc:'Conducts laboratory tests on body fluids for diagnosis'},
  {id:'h31',emoji:'📡',name:'Radiographer',sector:'Allied Health',desc:'Operates X-ray, MRI, and CT imaging equipment'},
  {id:'h32',emoji:'🔍',name:'Optometrist',sector:'Allied Health',desc:'Examines eyes and prescribes corrective lenses or treatments'},
  {id:'h33',emoji:'🦷',name:'Dental Surgeon',sector:'Allied Health',desc:'Diagnoses and treats diseases and conditions of the mouth'},
  {id:'h34',emoji:'🚑',name:'Paramedic / EMT',sector:'Allied Health',desc:'Delivers emergency medical care in pre-hospital settings'},
  {id:'h35',emoji:'👂',name:'Audiologist',sector:'Allied Health',desc:'Diagnoses and manages hearing loss and balance disorders'},
  {id:'h36',emoji:'🧘',name:'Occupational Therapist',sector:'Allied Health',desc:'Helps patients regain daily living and work independence'},
  {id:'h37',emoji:'🌍',name:'Public Health Officer',sector:'Public Health',desc:'Plans population-level disease prevention and health programs'},
  {id:'h38',emoji:'📊',name:'Epidemiologist',sector:'Public Health',desc:'Investigates patterns and causes of disease in communities'},
  {id:'h39',emoji:'📢',name:'Health Educator',sector:'Public Health',desc:'Promotes healthy behaviours through community outreach'},
  {id:'h40',emoji:'🏡',name:'Environmental Health Officer',sector:'Public Health',desc:'Inspects environments to prevent hazards and disease spread'},
  {id:'h41',emoji:'🦟',name:'Malaria Control Officer',sector:'Public Health',desc:'Coordinates vector control and malaria prevention programs'},
  {id:'h42',emoji:'🎗️',name:'HIV / AIDS Counsellor',sector:'Public Health',desc:'Provides testing, counselling, and treatment adherence support'},
  {id:'h43',emoji:'💉',name:'Vaccine Administrator',sector:'Public Health',desc:'Delivers immunisation programs to protect community health'},
  {id:'h44',emoji:'🏗️',name:'Biomedical Engineer',sector:'Administration',desc:'Designs and maintains medical equipment used in hospitals'},
  {id:'h45',emoji:'📋',name:'Hospital Administrator',sector:'Administration',desc:'Manages hospital operations, staffing, and service delivery'},
  {id:'h46',emoji:'📁',name:'Medical Records Officer',sector:'Administration',desc:'Maintains accurate patient data and health information systems'},
  {id:'h47',emoji:'🛡️',name:'Health Insurance Officer',sector:'Administration',desc:'Processes claims and manages healthcare financing schemes'},
  {id:'h48',emoji:'🚘',name:'Ambulance Driver',sector:'Administration',desc:'Transports patients safely to medical facilities in emergencies'},
  {id:'h49',emoji:'🩸',name:'Blood Bank Technician',sector:'Administration',desc:'Collects, tests, and stores blood for transfusion services'},
  {id:'h50',emoji:'🧹',name:'Hospital Sanitation Worker',sector:'Administration',desc:'Maintains hygiene and cleanliness in clinical environments'},
],

agriculture: [
  {id:'ag01',emoji:'🌾',name:'Arable / Crop Farmer',sector:'Crop Farming',desc:'Cultivates staple crops like maize, rice, and sorghum'},
  {id:'ag02',emoji:'🌿',name:'Vegetable Farmer',sector:'Crop Farming',desc:'Grows fresh vegetables for local markets and households'},
  {id:'ag03',emoji:'🍌',name:'Fruit Grower',sector:'Crop Farming',desc:'Cultivates fruits including plantain, mango, and citrus'},
  {id:'ag04',emoji:'☕',name:'Coffee / Cocoa Grower',sector:'Crop Farming',desc:'Cultivates cash crops for export and domestic processing'},
  {id:'ag05',emoji:'🌿',name:'Cassava Farmer',sector:'Crop Farming',desc:'Grows cassava as a primary food and processing crop'},
  {id:'ag06',emoji:'🍠',name:'Yam Farmer',sector:'Crop Farming',desc:'Cultivates yam as a culturally significant staple crop'},
  {id:'ag07',emoji:'🌱',name:'Rice Paddy Farmer',sector:'Crop Farming',desc:'Manages lowland and upland rice cultivation systems'},
  {id:'ag08',emoji:'🌿',name:'Cotton Grower',sector:'Crop Farming',desc:'Produces cotton lint for the textile manufacturing industry'},
  {id:'ag09',emoji:'🌴',name:'Palm Oil Farmer',sector:'Crop Farming',desc:'Maintains oil palm plantations for edible oil production'},
  {id:'ag10',emoji:'🎋',name:'Sugarcane Farmer',sector:'Crop Farming',desc:'Grows sugarcane for sugar refining and ethanol production'},
  {id:'ag11',emoji:'🌲',name:'Rubber Tapper',sector:'Crop Farming',desc:'Extracts natural rubber latex from rubber tree plantations'},
  {id:'ag12',emoji:'🌿',name:'Spice Farmer',sector:'Crop Farming',desc:'Cultivates spices like ginger, pepper, and turmeric'},
  {id:'ag13',emoji:'🍄',name:'Mushroom Cultivator',sector:'Crop Farming',desc:'Grows edible mushrooms for nutrition and market sales'},
  {id:'ag14',emoji:'🐄',name:'Cattle Rancher',sector:'Livestock',desc:'Raises cattle for beef, dairy, and hide production'},
  {id:'ag15',emoji:'🐔',name:'Poultry Farmer',sector:'Livestock',desc:'Raises chickens, turkeys, and ducks for meat and eggs'},
  {id:'ag16',emoji:'🐄',name:'Dairy Farmer',sector:'Livestock',desc:'Manages cows or goats to produce and supply fresh milk'},
  {id:'ag17',emoji:'🐖',name:'Pig Farmer',sector:'Livestock',desc:'Breeds and rears pigs for pork and animal by-products'},
  {id:'ag18',emoji:'🐐',name:'Sheep / Goat Keeper',sector:'Livestock',desc:'Raises goats and sheep for meat, milk, and hides'},
  {id:'ag19',emoji:'🐝',name:'Beekeeper / Apiarist',sector:'Livestock',desc:'Manages bee colonies for honey and pollination services'},
  {id:'ag20',emoji:'🐟',name:'Artisanal Fisherman',sector:'Fishery',desc:'Catches fish using traditional nets, lines, and traps'},
  {id:'ag21',emoji:'🦐',name:'Aquaculture Specialist',sector:'Fishery',desc:'Farms fish, shrimp, and shellfish in controlled environments'},
  {id:'ag22',emoji:'🐠',name:'Fish Processor',sector:'Fishery',desc:'Smokes, dries, or freezes fish to extend shelf life'},
  {id:'ag23',emoji:'🛒',name:'Fish Trader',sector:'Fishery',desc:'Buys and sells fish from fishermen to final consumers'},
  {id:'ag24',emoji:'🌾',name:'Grain Miller',sector:'Agro-Processing',desc:'Processes grains into flour, meal, or starch products'},
  {id:'ag25',emoji:'🥫',name:'Food Preservation Specialist',sector:'Agro-Processing',desc:'Applies canning, drying, and fermentation to extend shelf life'},
  {id:'ag26',emoji:'❄️',name:'Cold Chain Operator',sector:'Agro-Processing',desc:'Manages refrigerated storage and transport for perishables'},
  {id:'ag27',emoji:'🏗️',name:'Silo Operator',sector:'Agro-Processing',desc:'Manages bulk grain storage facilities and drying systems'},
  {id:'ag28',emoji:'🔬',name:'Agronomist',sector:'Science & Technology',desc:'Advises farmers on crop production and soil management'},
  {id:'ag29',emoji:'🌍',name:'Soil Scientist',sector:'Science & Technology',desc:'Studies soil properties to improve agricultural productivity'},
  {id:'ag30',emoji:'📢',name:'Agricultural Extension Officer',sector:'Science & Technology',desc:'Transfers research knowledge and skills to rural farmers'},
  {id:'ag31',emoji:'🌿',name:'Plant Pathologist',sector:'Science & Technology',desc:'Identifies and manages diseases affecting crops and plants'},
  {id:'ag32',emoji:'🛠️',name:'Agricultural Engineer',sector:'Science & Technology',desc:'Designs and maintains farm machinery and irrigation systems'},
  {id:'ag33',emoji:'💧',name:'Irrigation Specialist',sector:'Science & Technology',desc:'Plans and installs water delivery systems for crop production'},
  {id:'ag34',emoji:'🌱',name:'Greenhouse Manager',sector:'Science & Technology',desc:'Operates controlled-environment crop facilities year-round'},
  {id:'ag35',emoji:'🚁',name:'Agricultural Drone Operator',sector:'Science & Technology',desc:'Uses drones for crop monitoring, mapping, and spraying'},
  {id:'ag36',emoji:'🐾',name:'Veterinary Doctor',sector:'Science & Technology',desc:'Provides health care and disease control for farm animals'},
  {id:'ag37',emoji:'🥩',name:'Animal Nutritionist',sector:'Science & Technology',desc:'Formulates balanced feed rations for livestock optimisation'},
  {id:'ag38',emoji:'🚜',name:'Farm Equipment Operator',sector:'Support & Trade',desc:'Operates tractors, harvesters, and other farm machinery'},
  {id:'ag39',emoji:'📋',name:'Farm Manager',sector:'Support & Trade',desc:'Oversees all farm operations, budgets, and labour planning'},
  {id:'ag40',emoji:'📊',name:'Agricultural Economist',sector:'Support & Trade',desc:'Analyses markets, prices, and policy affecting agriculture'},
  {id:'ag41',emoji:'🤝',name:'Agricultural Commodity Trader',sector:'Support & Trade',desc:'Buys and sells farm produce across regional markets'},
  {id:'ag42',emoji:'🌱',name:'Seed Bank Guardian',sector:'Support & Trade',desc:'Preserves and manages genetic diversity of crop varieties'},
  {id:'ag43',emoji:'✅',name:'Organic Certification Auditor',sector:'Support & Trade',desc:'Verifies and certifies organic farming practices and standards'},
  {id:'ag44',emoji:'💰',name:'Farm Accountant',sector:'Support & Trade',desc:'Manages financial records, costs, and tax returns for farms'},
  {id:'ag45',emoji:'🌳',name:'Agro-Forestry Specialist',sector:'Support & Trade',desc:'Integrates trees with crops and livestock for sustainability'},
  {id:'ag46',emoji:'☔',name:'Meteorologist / Rain Watcher',sector:'Support & Trade',desc:'Monitors weather patterns to advise farming communities'},
  {id:'ag47',emoji:'🌿',name:'Nursery Operator',sector:'Support & Trade',desc:'Grows and sells seedlings, saplings, and planting materials'},
  {id:'ag48',emoji:'🐂',name:'Livestock Broker',sector:'Support & Trade',desc:'Facilitates buying and selling of cattle, goats, and pigs'},
  {id:'ag49',emoji:'🌺',name:'Floriculture Farmer',sector:'Crop Farming',desc:'Grows cut flowers and ornamental plants for export markets'},
  {id:'ag50',emoji:'🥦',name:'Market Garden Farmer',sector:'Crop Farming',desc:'Produces mixed vegetables intensively for urban food markets'},
],

education: [
  {id:'ed01',emoji:'👶',name:'Early Childhood Educator',sector:'Teaching',desc:'Nurtures the development of children aged 0 to 5 years'},
  {id:'ed02',emoji:'📚',name:'Primary School Teacher',sector:'Teaching',desc:'Delivers foundational education across all core subjects'},
  {id:'ed03',emoji:'🏫',name:'Secondary School Teacher',sector:'Teaching',desc:'Teaches specialist subjects to students aged 11 to 17'},
  {id:'ed04',emoji:'🔢',name:'Mathematics Teacher',sector:'Teaching',desc:'Teaches numeracy, algebra, geometry, and calculus'},
  {id:'ed05',emoji:'🧪',name:'Science Teacher',sector:'Teaching',desc:'Delivers biology, chemistry, and physics education'},
  {id:'ed06',emoji:'📖',name:'English / Literature Teacher',sector:'Teaching',desc:'Develops reading, writing, and critical thinking skills'},
  {id:'ed07',emoji:'🌍',name:'History & Geography Teacher',sector:'Teaching',desc:'Teaches social studies, civics, and world geography'},
  {id:'ed08',emoji:'⚽',name:'Physical Education Teacher',sector:'Teaching',desc:'Promotes sport, fitness, and health through movement'},
  {id:'ed09',emoji:'🎨',name:'Art & Craft Teacher',sector:'Teaching',desc:'Develops creativity through visual arts and crafts'},
  {id:'ed10',emoji:'🎵',name:'Music Teacher',sector:'Teaching',desc:'Teaches vocal and instrumental music performance skills'},
  {id:'ed11',emoji:'💻',name:'Computer Science Teacher',sector:'Teaching',desc:'Delivers coding, digital literacy, and IT education'},
  {id:'ed12',emoji:'🌐',name:'Indigenous Language Teacher',sector:'Teaching',desc:'Preserves and teaches African languages and oral traditions'},
  {id:'ed13',emoji:'🕌',name:'Islamic Studies Teacher',sector:'Teaching',desc:'Teaches Quranic studies, Arabic, and Islamic ethics'},
  {id:'ed14',emoji:'✝️',name:'Religious Education Teacher',sector:'Teaching',desc:'Delivers Christian or multi-faith religious instruction'},
  {id:'ed15',emoji:'♿',name:'Special Needs Educator',sector:'Teaching',desc:'Supports learners with disabilities and learning differences'},
  {id:'ed16',emoji:'🏛️',name:'University Lecturer',sector:'Tertiary',desc:'Delivers undergraduate and postgraduate subject teaching'},
  {id:'ed17',emoji:'🎓',name:'University Professor',sector:'Tertiary',desc:'Leads research and teaching at senior academic level'},
  {id:'ed18',emoji:'📝',name:'Research Supervisor',sector:'Tertiary',desc:'Guides postgraduate students through thesis research'},
  {id:'ed19',emoji:'📜',name:'Academic Dean',sector:'Tertiary',desc:'Provides academic and strategic leadership for a faculty'},
  {id:'ed20',emoji:'🗂️',name:'University Registrar',sector:'Tertiary',desc:'Manages student enrolment, records, and graduation processes'},
  {id:'ed21',emoji:'🏫',name:'School Principal',sector:'School Leadership',desc:'Provides educational and administrative leadership to a school'},
  {id:'ed22',emoji:'🧑‍💼',name:'Deputy Principal',sector:'School Leadership',desc:'Supports the principal in governance and daily operations'},
  {id:'ed23',emoji:'🔍',name:'Education Inspector',sector:'School Leadership',desc:'Evaluates school quality and recommends improvements'},
  {id:'ed24',emoji:'📐',name:'Curriculum Designer',sector:'School Leadership',desc:'Develops learning programmes aligned to national standards'},
  {id:'ed25',emoji:'📊',name:'Educational Policy Analyst',sector:'School Leadership',desc:'Researches and shapes education reform and policy'},
  {id:'ed26',emoji:'📚',name:'School Librarian',sector:'Support Staff',desc:'Manages library collections and promotes reading culture'},
  {id:'ed27',emoji:'🔬',name:'Laboratory Supervisor',sector:'Support Staff',desc:'Manages science lab safety, equipment, and experiments'},
  {id:'ed28',emoji:'🧑‍🏫',name:'Teaching Assistant',sector:'Support Staff',desc:'Supports classroom instruction and individual learners'},
  {id:'ed29',emoji:'💰',name:'School Bursar',sector:'Support Staff',desc:'Manages school finances, fees collection, and expenditure'},
  {id:'ed30',emoji:'📋',name:'School Secretary',sector:'Support Staff',desc:'Handles administrative communications and school records'},
  {id:'ed31',emoji:'🤝',name:'Parent-Teacher Liaison',sector:'Support Staff',desc:'Bridges communication between families and the school'},
  {id:'ed32',emoji:'🏥',name:'School Nurse',sector:'Support Staff',desc:'Provides first aid and health monitoring for pupils'},
  {id:'ed33',emoji:'💬',name:'School Counsellor',sector:'Support Staff',desc:'Provides emotional support and guidance to students'},
  {id:'ed34',emoji:'⛪',name:'School Chaplain',sector:'Support Staff',desc:'Offers spiritual guidance and pastoral care to the community'},
  {id:'ed35',emoji:'🏋️',name:'School Sports Coach',sector:'Support Staff',desc:'Trains students in competitive and recreational sports'},
  {id:'ed36',emoji:'🛠️',name:'Vocational Trainer',sector:'Vocational & Adult',desc:'Teaches practical trade skills in workshops and labs'},
  {id:'ed37',emoji:'🏭',name:'Skills Centre Manager',sector:'Vocational & Adult',desc:'Runs a vocational training centre for youth empowerment'},
  {id:'ed38',emoji:'📖',name:'Adult Literacy Facilitator',sector:'Vocational & Adult',desc:'Teaches reading and writing skills to adult learners'},
  {id:'ed39',emoji:'📱',name:'Distance Learning Specialist',sector:'Vocational & Adult',desc:'Designs and delivers online and remote learning programs'},
  {id:'ed40',emoji:'💡',name:'EdTech Developer',sector:'Vocational & Adult',desc:'Builds digital tools and platforms for learning delivery'},
  {id:'ed41',emoji:'🚌',name:'Mobile School Coordinator',sector:'Vocational & Adult',desc:'Brings education to nomadic and hard-to-reach communities'},
  {id:'ed42',emoji:'🎓',name:'Scholarship Coordinator',sector:'Support Staff',desc:'Identifies and processes academic funding opportunities'},
  {id:'ed43',emoji:'📣',name:'Student Affairs Officer',sector:'Support Staff',desc:'Manages student welfare, activities, and campus engagement'},
  {id:'ed44',emoji:'✍️',name:'Textbook Author',sector:'Vocational & Adult',desc:'Writes curriculum-aligned educational materials and texts'},
  {id:'ed45',emoji:'📽️',name:'Educational Content Creator',sector:'Vocational & Adult',desc:'Produces videos and digital content for online learners'},
  {id:'ed46',emoji:'🔁',name:'After-School Programme Leader',sector:'Support Staff',desc:'Coordinates remedial, enrichment, and extra-curricular clubs'},
  {id:'ed47',emoji:'🌍',name:'STEM Programme Director',sector:'School Leadership',desc:'Leads science, technology, engineering, and maths initiatives'},
  {id:'ed48',emoji:'📜',name:'Examination Officer',sector:'School Leadership',desc:'Organises and administers internal and national examinations'},
  {id:'ed49',emoji:'📢',name:'Literacy Campaign Coordinator',sector:'Vocational & Adult',desc:'Runs community programmes to eliminate adult illiteracy'},
  {id:'ed50',emoji:'🎓',name:'University Admissions Officer',sector:'Tertiary',desc:'Manages applications and student enrolment for higher education'},
],

justice: [
  {id:'ju01',emoji:'⚖️',name:'Barrister / Advocate',sector:'Legal Practice',desc:'Represents clients and argues cases in courts of law'},
  {id:'ju02',emoji:'📜',name:'Solicitor / Lawyer',sector:'Legal Practice',desc:'Provides legal advice and handles client matters outside court'},
  {id:'ju03',emoji:'🏛️',name:'State Prosecutor',sector:'Legal Practice',desc:'Represents the government in bringing criminal charges'},
  {id:'ju04',emoji:'🛡️',name:'Public Defender',sector:'Legal Practice',desc:'Provides free legal representation to accused without means'},
  {id:'ju05',emoji:'⚖️',name:'Magistrate',sector:'Courts',desc:'Adjudicates lower court cases and preliminary hearings'},
  {id:'ju06',emoji:'👨‍⚖️',name:'High Court Judge',sector:'Courts',desc:'Presides over complex civil and serious criminal cases'},
  {id:'ju07',emoji:'🏛️',name:'Supreme Court Justice',sector:'Courts',desc:'Sits on the highest court interpreting constitutional law'},
  {id:'ju08',emoji:'📋',name:'Court Registrar',sector:'Courts',desc:'Manages court records, scheduling, and administrative functions'},
  {id:'ju09',emoji:'🗣️',name:'Court Interpreter',sector:'Courts',desc:'Translates court proceedings across different languages'},
  {id:'ju10',emoji:'🤝',name:'Legal Aid Officer',sector:'Legal Practice',desc:'Delivers free legal services to vulnerable and low-income clients'},
  {id:'ju11',emoji:'👮',name:'Police Officer',sector:'Law Enforcement',desc:'Enforces the law and maintains public order and safety'},
  {id:'ju12',emoji:'🔍',name:'Detective / Criminal Investigator',sector:'Law Enforcement',desc:'Investigates serious crimes through evidence collection'},
  {id:'ju13',emoji:'🚔',name:'Police Commissioner',sector:'Law Enforcement',desc:'Commands the national or state police service organisation'},
  {id:'ju14',emoji:'🔬',name:'Forensic Scientist',sector:'Law Enforcement',desc:'Analyses physical evidence to support criminal investigations'},
  {id:'ju15',emoji:'🧬',name:'Crime Scene Analyst',sector:'Law Enforcement',desc:'Documents and collects evidence at crime scene locations'},
  {id:'ju16',emoji:'🔒',name:'Correctional Officer',sector:'Corrections',desc:'Supervises incarcerated individuals in custodial facilities'},
  {id:'ju17',emoji:'🏢',name:'Prison Warden',sector:'Corrections',desc:'Manages the operations and security of a prison facility'},
  {id:'ju18',emoji:'📋',name:'Probation Officer',sector:'Corrections',desc:'Supervises offenders serving non-custodial sentences'},
  {id:'ju19',emoji:'📅',name:'Parole Officer',sector:'Corrections',desc:'Monitors offenders released early from prison sentences'},
  {id:'ju20',emoji:'🏘️',name:'Community Mediator',sector:'Alternative Justice',desc:'Resolves community disputes outside formal court processes'},
  {id:'ju21',emoji:'👑',name:'Traditional Chief / Arbitrator',sector:'Alternative Justice',desc:'Applies customary law to settle disputes among community members'},
  {id:'ju22',emoji:'🌍',name:'Land Dispute Resolver',sector:'Alternative Justice',desc:'Mediates and adjudicates conflicts over land ownership'},
  {id:'ju23',emoji:'❤️',name:'Human Rights Officer',sector:'Alternative Justice',desc:'Monitors and responds to civil and human rights violations'},
  {id:'ju24',emoji:'👶',name:'Child Protection Officer',sector:'Alternative Justice',desc:'Investigates child abuse and enforces child welfare laws'},
  {id:'ju25',emoji:'🕵️',name:'Anti-Corruption Investigator',sector:'Law Enforcement',desc:'Investigates bribery, fraud, and abuse of public office'},
  {id:'ju26',emoji:'🛂',name:'Immigration Officer',sector:'Law Enforcement',desc:'Controls entry and stay of foreign nationals at borders'},
  {id:'ju27',emoji:'🚢',name:'Customs Officer (Enforcement)',sector:'Law Enforcement',desc:'Prevents smuggling and enforces trade laws at ports'},
  {id:'ju28',emoji:'🧑‍💻',name:'Cybercrime Officer',sector:'Law Enforcement',desc:'Investigates online fraud, hacking, and digital crimes'},
  {id:'ju29',emoji:'💊',name:'Drug Enforcement Officer',sector:'Law Enforcement',desc:'Investigates narcotics trafficking and substance abuse crimes'},
  {id:'ju30',emoji:'💴',name:'Financial Crimes Investigator',sector:'Law Enforcement',desc:'Probes money laundering, embezzlement, and financial fraud'},
  {id:'ju31',emoji:'📝',name:'Paralegal',sector:'Legal Practice',desc:'Assists lawyers with research, drafting, and case management'},
  {id:'ju32',emoji:'🗂️',name:'Law Clerk',sector:'Courts',desc:'Researches case law and assists judges in writing opinions'},
  {id:'ju33',emoji:'📄',name:'Notary Public',sector:'Legal Practice',desc:'Authenticates documents and witnesses legal signatures'},
  {id:'ju34',emoji:'🔎',name:'Legal Researcher',sector:'Legal Practice',desc:'Analyses case precedents and prepares legal briefs'},
  {id:'ju35',emoji:'🏛️',name:'Court Bailiff',sector:'Courts',desc:'Maintains order and security within courtroom proceedings'},
  {id:'ju36',emoji:'👤',name:'Victim Support Officer',sector:'Courts',desc:'Provides emotional and practical support to crime victims'},
  {id:'ju37',emoji:'🕵️',name:'Criminal Profiler',sector:'Law Enforcement',desc:'Develops offender profiles to assist with criminal investigations'},
  {id:'ju38',emoji:'🛡️',name:'Witness Protection Officer',sector:'Law Enforcement',desc:'Safeguards witnesses and informants at risk of harm'},
  {id:'ju39',emoji:'🧒',name:'Juvenile Justice Officer',sector:'Corrections',desc:'Handles cases involving young offenders in the justice system'},
  {id:'ju40',emoji:'🧠',name:'Prison Psychologist',sector:'Corrections',desc:'Delivers mental health care and rehabilitation programmes in prison'},
  {id:'ju41',emoji:'🔁',name:'Restorative Justice Facilitator',sector:'Alternative Justice',desc:'Convenes dialogues between offenders and those they have harmed'},
  {id:'ju42',emoji:'🌍',name:'Refugee Law Specialist',sector:'Legal Practice',desc:'Provides legal representation and asylum support to refugees'},
  {id:'ju43',emoji:'📜',name:'Constitutional Lawyer',sector:'Legal Practice',desc:'Litigates and advises on fundamental rights and state powers'},
  {id:'ju44',emoji:'🌐',name:'International Law Specialist',sector:'Legal Practice',desc:'Handles cross-border legal matters and treaty obligations'},
  {id:'ju45',emoji:'💡',name:'Intellectual Property Lawyer',sector:'Legal Practice',desc:'Protects patents, trademarks, copyrights, and trade secrets'},
  {id:'ju46',emoji:'👨‍👩‍👧',name:'Family Law Specialist',sector:'Legal Practice',desc:'Handles divorce, custody, and domestic relations matters'},
  {id:'ju47',emoji:'🗣️',name:'Parliamentary Counsel',sector:'Legal Practice',desc:'Drafts and reviews legislation for parliament and government'},
  {id:'ju48',emoji:'📢',name:'Legal Aid Coordinator',sector:'Legal Practice',desc:'Manages the delivery of free legal services to communities'},
  {id:'ju49',emoji:'🏠',name:'Landlord-Tenant Mediator',sector:'Alternative Justice',desc:'Resolves rental disputes through mediation and arbitration'},
  {id:'ju50',emoji:'🔐',name:'Digital Rights Lawyer',sector:'Legal Practice',desc:'Defends privacy, data protection, and online civil liberties'},
],

finance: [
  {id:'fi01',emoji:'🏦',name:'Commercial Banker',sector:'Banking',desc:'Manages corporate and retail banking products and services'},
  {id:'fi02',emoji:'💳',name:'Retail Bank Teller',sector:'Banking',desc:'Processes deposits, withdrawals, and customer transactions'},
  {id:'fi03',emoji:'📋',name:'Loan Officer',sector:'Banking',desc:'Evaluates and approves credit applications for borrowers'},
  {id:'fi04',emoji:'📊',name:'Credit Analyst',sector:'Banking',desc:'Assesses the creditworthiness and risk profile of borrowers'},
  {id:'fi05',emoji:'💼',name:'Investment Banker',sector:'Investment',desc:'Structures capital markets deals, M&A, and IPO transactions'},
  {id:'fi06',emoji:'📈',name:'Stock Broker',sector:'Investment',desc:'Buys and sells securities on behalf of investor clients'},
  {id:'fi07',emoji:'🗂️',name:'Portfolio Manager',sector:'Investment',desc:'Manages investment portfolios to meet client financial goals'},
  {id:'fi08',emoji:'🔬',name:'Hedge Fund Analyst',sector:'Investment',desc:'Researches alternative investment strategies and opportunities'},
  {id:'fi09',emoji:'🎯',name:'Financial Planner',sector:'Investment',desc:'Creates comprehensive financial plans for individuals and families'},
  {id:'fi10',emoji:'💎',name:'Wealth Manager',sector:'Investment',desc:'Provides holistic financial services to high-net-worth clients'},
  {id:'fi11',emoji:'📝',name:'Insurance Underwriter',sector:'Insurance',desc:'Assesses risks and determines appropriate insurance terms'},
  {id:'fi12',emoji:'📋',name:'Insurance Claims Assessor',sector:'Insurance',desc:'Evaluates and settles policyholder insurance claims'},
  {id:'fi13',emoji:'🔢',name:'Actuary',sector:'Insurance',desc:'Uses statistics to assess financial risk in insurance and pensions'},
  {id:'fi14',emoji:'⚠️',name:'Risk Manager',sector:'Insurance',desc:'Identifies and mitigates financial and operational risks'},
  {id:'fi15',emoji:'🏘️',name:'Microfinance Officer',sector:'Banking',desc:'Delivers small loans and financial services to low-income clients'},
  {id:'fi16',emoji:'📱',name:'Mobile Money Agent',sector:'Banking',desc:'Facilitates digital cash transactions for unbanked communities'},
  {id:'fi17',emoji:'💸',name:'Payment Systems Specialist',sector:'Banking',desc:'Manages digital payment infrastructure and settlement networks'},
  {id:'fi18',emoji:'🔍',name:'Tax Inspector',sector:'Tax & Accounting',desc:'Audits individuals and businesses for tax compliance'},
  {id:'fi19',emoji:'💡',name:'Tax Consultant',sector:'Tax & Accounting',desc:'Advises clients on tax planning and legal compliance strategies'},
  {id:'fi20',emoji:'📒',name:'Chartered Accountant',sector:'Tax & Accounting',desc:'Prepares and certifies financial statements for organisations'},
  {id:'fi21',emoji:'🔎',name:'Auditor',sector:'Tax & Accounting',desc:'Independently examines financial records for accuracy and fraud'},
  {id:'fi22',emoji:'📊',name:'Financial Controller',sector:'Tax & Accounting',desc:'Oversees all accounting and financial reporting for an organisation'},
  {id:'fi23',emoji:'👔',name:'Chief Financial Officer',sector:'Tax & Accounting',desc:'Leads the financial strategy and operations of an organisation'},
  {id:'fi24',emoji:'🕌',name:'Islamic Finance Scholar',sector:'Islamic Finance',desc:'Certifies financial products for Sharia-compliance standards'},
  {id:'fi25',emoji:'🤝',name:'Takaful Officer',sector:'Islamic Finance',desc:'Administers cooperative Islamic insurance schemes and claims'},
  {id:'fi26',emoji:'🏠',name:'Mortgage Broker',sector:'Banking',desc:'Connects borrowers with appropriate home loan financing'},
  {id:'fi27',emoji:'💱',name:'Forex Trader',sector:'Investment',desc:'Buys and sells currencies in the foreign exchange market'},
  {id:'fi28',emoji:'🌾',name:'Commodity Trader',sector:'Investment',desc:'Trades raw materials like oil, gold, cocoa, and grains'},
  {id:'fi29',emoji:'📉',name:'Derivatives Analyst',sector:'Investment',desc:'Prices and structures complex financial derivative instruments'},
  {id:'fi30',emoji:'✅',name:'Compliance Officer',sector:'Banking',desc:'Ensures financial activities meet regulatory requirements'},
  {id:'fi31',emoji:'🚫',name:'Anti-Money Laundering Specialist',sector:'Banking',desc:'Detects and reports suspicious financial transactions'},
  {id:'fi32',emoji:'📣',name:'Financial Regulator',sector:'Tax & Accounting',desc:'Supervises financial institutions for systemic stability'},
  {id:'fi33',emoji:'🏛️',name:'Central Bank Officer',sector:'Banking',desc:'Implements monetary policy and oversees currency management'},
  {id:'fi34',emoji:'💰',name:'Treasury Manager',sector:'Tax & Accounting',desc:'Manages liquidity, cash flow, and funding for the business'},
  {id:'fi35',emoji:'📋',name:'Budget Analyst',sector:'Tax & Accounting',desc:'Prepares and monitors organisational financial plans and budgets'},
  {id:'fi36',emoji:'🔢',name:'Cost Accountant',sector:'Tax & Accounting',desc:'Tracks production and operational costs for management decisions'},
  {id:'fi37',emoji:'💼',name:'Payroll Officer',sector:'Tax & Accounting',desc:'Processes employee salaries, deductions, and tax submissions'},
  {id:'fi38',emoji:'📌',name:'Debt Recovery Agent',sector:'Banking',desc:'Pursues and recovers defaulted loans and overdue payments'},
  {id:'fi39',emoji:'🏢',name:'Credit Union Manager',sector:'Banking',desc:'Oversees member-owned cooperative financial institutions'},
  {id:'fi40',emoji:'🌾',name:'Agricultural Finance Specialist',sector:'Banking',desc:'Designs crop credit, insurance, and input financing products'},
  {id:'fi41',emoji:'💻',name:'Fintech Product Manager',sector:'Fintech',desc:'Designs and launches digital financial products and services'},
  {id:'fi42',emoji:'🔗',name:'Blockchain Developer (Finance)',sector:'Fintech',desc:'Builds decentralised financial applications and smart contracts'},
  {id:'fi43',emoji:'₿',name:'Cryptocurrency Analyst',sector:'Fintech',desc:'Evaluates and trades digital currencies and crypto assets'},
  {id:'fi44',emoji:'📡',name:'Financial Data Analyst',sector:'Fintech',desc:'Extracts insights from large financial datasets and models'},
  {id:'fi45',emoji:'🌱',name:'ESG Investment Analyst',sector:'Investment',desc:'Evaluates environmental, social, and governance criteria for funds'},
  {id:'fi46',emoji:'🏗️',name:'Infrastructure Finance Specialist',sector:'Investment',desc:'Structures long-term financing for large infrastructure projects'},
  {id:'fi47',emoji:'🌍',name:'Development Finance Officer',sector:'Banking',desc:'Mobilises capital for underserved markets and social impact'},
  {id:'fi48',emoji:'👴',name:'Pension Fund Manager',sector:'Investment',desc:'Oversees retirement savings investment pools and strategies'},
  {id:'fi49',emoji:'🤝',name:'Cooperative Finance Officer',sector:'Banking',desc:'Manages financial services for agricultural and worker cooperatives'},
  {id:'fi50',emoji:'🌐',name:'Remittance Services Manager',sector:'Banking',desc:'Oversees cross-border money transfer products and operations'},
],

builders: [
  {id:'bu01',emoji:'🏛️',name:'Architect',sector:'Architecture & Design',desc:'Designs buildings balancing aesthetics, function, and safety'},
  {id:'bu02',emoji:'🏙️',name:'Urban Planner',sector:'Architecture & Design',desc:'Develops land use plans for sustainable cities and communities'},
  {id:'bu03',emoji:'🛋️',name:'Interior Designer',sector:'Architecture & Design',desc:'Creates functional and aesthetic interior spaces and layouts'},
  {id:'bu04',emoji:'🌳',name:'Landscape Architect',sector:'Architecture & Design',desc:'Designs outdoor spaces, parks, and urban green environments'},
  {id:'bu05',emoji:'🏗️',name:'Civil Engineer',sector:'Civil Engineering',desc:'Plans and oversees construction of roads, bridges, and infrastructure'},
  {id:'bu06',emoji:'🔩',name:'Structural Engineer',sector:'Civil Engineering',desc:'Designs load-bearing systems to ensure safe buildings'},
  {id:'bu07',emoji:'⛰️',name:'Geotechnical Engineer',sector:'Civil Engineering',desc:'Studies soil and rock conditions for safe project foundations'},
  {id:'bu08',emoji:'🌿',name:'Environmental Engineer',sector:'Civil Engineering',desc:'Minimises the environmental impact of construction projects'},
  {id:'bu09',emoji:'💰',name:'Quantity Surveyor',sector:'Civil Engineering',desc:'Manages and controls construction project costs and contracts'},
  {id:'bu10',emoji:'🗺️',name:'Land Surveyor',sector:'Civil Engineering',desc:'Measures and maps land boundaries, topography, and ownership'},
  {id:'bu11',emoji:'📋',name:'Site Manager / Project Manager',sector:'Site Management',desc:'Coordinates day-to-day construction activities and teams'},
  {id:'bu12',emoji:'⚠️',name:'Construction Safety Officer',sector:'Site Management',desc:'Enforces workplace health and safety standards on sites'},
  {id:'bu13',emoji:'🔍',name:'Quality Control Inspector',sector:'Site Management',desc:'Ensures construction meets design specifications and standards'},
  {id:'bu14',emoji:'🏗️',name:'Site Foreman',sector:'Site Management',desc:'Supervises trade workers and coordinates daily site tasks'},
  {id:'bu15',emoji:'💡',name:'Estimator',sector:'Site Management',desc:'Calculates material and labour costs for construction bids'},
  {id:'bu16',emoji:'🧱',name:'Mason / Bricklayer',sector:'Trades',desc:'Lays bricks, blocks, and stone to construct walls and structures'},
  {id:'bu17',emoji:'🪵',name:'Carpenter / Joiner',sector:'Trades',desc:'Constructs and installs wooden frameworks, doors, and fixtures'},
  {id:'bu18',emoji:'⚡',name:'Electrician',sector:'Trades',desc:'Installs and maintains electrical wiring, panels, and systems'},
  {id:'bu19',emoji:'🚰',name:'Plumber',sector:'Trades',desc:'Installs and repairs water supply and drainage pipe systems'},
  {id:'bu20',emoji:'🔥',name:'Welder',sector:'Trades',desc:'Joins and fabricates metal components using heat and tools'},
  {id:'bu21',emoji:'🎨',name:'Painter & Decorator',sector:'Trades',desc:'Applies paint, wallpaper, and decorative finishes to interiors'},
  {id:'bu22',emoji:'🔲',name:'Tiler / Floor Layer',sector:'Trades',desc:'Fixes ceramic, marble, vinyl, and wooden floor and wall tiles'},
  {id:'bu23',emoji:'🏠',name:'Roofer',sector:'Trades',desc:'Installs and repairs roofing systems and weatherproofing'},
  {id:'bu24',emoji:'🪟',name:'Glazier / Window Fitter',sector:'Trades',desc:'Cuts, installs, and replaces glass panels in buildings'},
  {id:'bu25',emoji:'🏗️',name:'Scaffolder',sector:'Trades',desc:'Erects and dismantles temporary access structures on sites'},
  {id:'bu26',emoji:'🏗️',name:'Crane Operator',sector:'Trades',desc:'Operates cranes to lift and position heavy construction loads'},
  {id:'bu27',emoji:'🚜',name:'Excavator / Bulldozer Operator',sector:'Trades',desc:'Operates earthmoving machinery to prepare construction sites'},
  {id:'bu28',emoji:'🪨',name:'Concrete Mixer Operator',sector:'Trades',desc:'Mixes and pours concrete for foundations, floors, and walls'},
  {id:'bu29',emoji:'🔗',name:'Steel Fixer / Ironworker',sector:'Trades',desc:'Cuts, bends, and ties reinforcing steel bars for concrete'},
  {id:'bu30',emoji:'🪣',name:'Plasterer',sector:'Trades',desc:'Applies smooth plaster and render finishes to walls and ceilings'},
  {id:'bu31',emoji:'🏠',name:'Ceiling Fixer',sector:'Trades',desc:'Installs suspended ceilings, partitions, and drywall systems'},
  {id:'bu32',emoji:'🛤️',name:'Road Construction Worker',sector:'Trades',desc:'Builds and maintains roads, pavements, and car parks'},
  {id:'bu33',emoji:'🌉',name:'Bridge Engineer',sector:'Civil Engineering',desc:'Designs and supervises the construction of bridges and flyovers'},
  {id:'bu34',emoji:'💧',name:'Water & Sanitation Engineer',sector:'Specialty Trades',desc:'Designs water treatment, piping, and sanitation infrastructure'},
  {id:'bu35',emoji:'🔆',name:'Solar Panel Installer',sector:'Specialty Trades',desc:'Installs and commissions rooftop and ground-mount solar systems'},
  {id:'bu36',emoji:'❄️',name:'HVAC Technician',sector:'Specialty Trades',desc:'Installs and maintains heating, ventilation, and air conditioning'},
  {id:'bu37',emoji:'🔥',name:'Fire Safety Engineer',sector:'Specialty Trades',desc:'Designs sprinkler systems and fire protection for buildings'},
  {id:'bu38',emoji:'🏠',name:'Facilities Manager',sector:'Specialty Trades',desc:'Oversees building maintenance, services, and operations'},
  {id:'bu39',emoji:'🧑‍💻',name:'BIM / CAD Technician',sector:'Architecture & Design',desc:'Produces digital building models and technical drawings'},
  {id:'bu40',emoji:'🏢',name:'Building Inspector',sector:'Site Management',desc:'Verifies buildings comply with safety codes and regulations'},
  {id:'bu41',emoji:'🌍',name:'Housing Developer',sector:'Site Management',desc:'Develops affordable and commercial residential housing projects'},
  {id:'bu42',emoji:'🏗️',name:'Real Estate Developer',sector:'Site Management',desc:'Acquires land and manages large-scale property development'},
  {id:'bu43',emoji:'🔌',name:'Smart Building Technician',sector:'Specialty Trades',desc:'Installs automation, IoT, and energy management systems'},
  {id:'bu44',emoji:'🌱',name:'Eco-Housing Designer',sector:'Architecture & Design',desc:'Creates energy-efficient, low-carbon, and sustainable homes'},
  {id:'bu45',emoji:'🏺',name:'Traditional Adobe Builder',sector:'Trades',desc:'Constructs with compressed earth and traditional African materials'},
  {id:'bu46',emoji:'🧱',name:'Compressed Earth Block Specialist',sector:'Trades',desc:'Builds with stabilised compressed earth block technology'},
  {id:'bu47',emoji:'🧑‍🔧',name:'Maintenance Engineer',sector:'Specialty Trades',desc:'Carries out preventive and corrective maintenance on buildings'},
  {id:'bu48',emoji:'⚡',name:'Generator & Power Systems Technician',sector:'Specialty Trades',desc:'Installs and services standby generators and power systems'},
  {id:'bu49',emoji:'🗺️',name:'Topographic Survey Technician',sector:'Civil Engineering',desc:'Collects field data and produces topographic survey maps'},
  {id:'bu50',emoji:'🌊',name:'Dam & Waterway Engineer',sector:'Civil Engineering',desc:'Designs dams, spillways, and channelised water infrastructure'},
],

technology: [
  {id:'te01',emoji:'👨‍💻',name:'Software Engineer',sector:'Software Development',desc:'Designs and builds software systems and applications'},
  {id:'te02',emoji:'🖥️',name:'Frontend Developer',sector:'Software Development',desc:'Creates user interfaces and client-side web applications'},
  {id:'te03',emoji:'⚙️',name:'Backend Developer',sector:'Software Development',desc:'Builds server-side logic, APIs, and database integrations'},
  {id:'te04',emoji:'🔀',name:'Full Stack Developer',sector:'Software Development',desc:'Develops both frontend and backend components of applications'},
  {id:'te05',emoji:'📱',name:'Mobile App Developer',sector:'Software Development',desc:'Builds applications for Android and iOS mobile platforms'},
  {id:'te06',emoji:'🚀',name:'DevOps Engineer',sector:'Infrastructure',desc:'Automates deployment pipelines and manages cloud infrastructure'},
  {id:'te07',emoji:'☁️',name:'Cloud Architect',sector:'Infrastructure',desc:'Designs scalable and secure cloud computing environments'},
  {id:'te08',emoji:'🗄️',name:'Database Administrator',sector:'Infrastructure',desc:'Manages, optimises, and secures database systems'},
  {id:'te09',emoji:'🌐',name:'Network Engineer',sector:'Infrastructure',desc:'Designs and maintains communications network infrastructure'},
  {id:'te10',emoji:'🖥️',name:'Systems Administrator',sector:'Infrastructure',desc:'Manages servers, access controls, and IT systems operations'},
  {id:'te11',emoji:'🔬',name:'Data Scientist',sector:'Data & AI',desc:'Extracts insights and builds predictive models from data'},
  {id:'te12',emoji:'🤖',name:'Machine Learning Engineer',sector:'Data & AI',desc:'Builds, trains, and deploys machine learning models at scale'},
  {id:'te13',emoji:'🧠',name:'AI Researcher',sector:'Data & AI',desc:'Advances artificial intelligence theory and applications'},
  {id:'te14',emoji:'🔧',name:'Data Engineer',sector:'Data & AI',desc:'Builds data pipelines, lakes, and processing infrastructure'},
  {id:'te15',emoji:'📊',name:'Business Intelligence Analyst',sector:'Data & AI',desc:'Translates data into dashboards and actionable business reports'},
  {id:'te16',emoji:'🛡️',name:'Cybersecurity Analyst',sector:'Security',desc:'Monitors systems and defends against cyber threats and attacks'},
  {id:'te17',emoji:'🕵️',name:'Ethical Hacker / Penetration Tester',sector:'Security',desc:'Tests systems by simulating real-world cyberattack scenarios'},
  {id:'te18',emoji:'🔐',name:'Security Architect',sector:'Security',desc:'Designs secure systems and enterprise security frameworks'},
  {id:'te19',emoji:'🖥️',name:'SOC Analyst',sector:'Security',desc:'Monitors alerts in a Security Operations Centre in real time'},
  {id:'te20',emoji:'🔎',name:'Digital Forensics Expert',sector:'Security',desc:'Recovers and analyses digital evidence from devices and networks'},
  {id:'te21',emoji:'🎨',name:'UI / UX Designer',sector:'Product & Design',desc:'Creates intuitive, accessible digital interfaces and experiences'},
  {id:'te22',emoji:'📌',name:'Product Manager',sector:'Product & Design',desc:'Defines product vision, roadmap, and delivery priorities'},
  {id:'te23',emoji:'🔄',name:'Scrum Master / Agile Coach',sector:'Product & Design',desc:'Facilitates agile workflows and removes team blockers'},
  {id:'te24',emoji:'✅',name:'QA Engineer',sector:'Product & Design',desc:'Tests software to identify defects and ensure quality standards'},
  {id:'te25',emoji:'📝',name:'Technical Writer',sector:'Product & Design',desc:'Produces documentation, user guides, and API references'},
  {id:'te26',emoji:'🔗',name:'Blockchain Developer',sector:'Software Development',desc:'Builds decentralised applications and distributed ledger systems'},
  {id:'te27',emoji:'📜',name:'Smart Contract Developer',sector:'Software Development',desc:'Writes self-executing contracts on blockchain platforms'},
  {id:'te28',emoji:'🌐',name:'IoT Engineer',sector:'Infrastructure',desc:'Connects and manages internet-of-things devices and sensors'},
  {id:'te29',emoji:'🤖',name:'Robotics Engineer',sector:'Software Development',desc:'Designs and programs automated robotic systems and machines'},
  {id:'te30',emoji:'👁️',name:'Computer Vision Engineer',sector:'Data & AI',desc:'Builds systems that interpret and process visual image data'},
  {id:'te31',emoji:'🗣️',name:'NLP Engineer',sector:'Data & AI',desc:'Develops natural language processing and understanding systems'},
  {id:'te32',emoji:'💡',name:'Technology Consultant',sector:'Product & Design',desc:'Advises organisations on IT strategy and digital transformation'},
  {id:'te33',emoji:'📋',name:'IT Project Manager',sector:'Product & Design',desc:'Plans and delivers technology projects on time and within budget'},
  {id:'te34',emoji:'🏭',name:'ERP Implementation Specialist',sector:'Infrastructure',desc:'Configures and deploys enterprise resource planning systems'},
  {id:'te35',emoji:'🛍️',name:'E-commerce Developer',sector:'Software Development',desc:'Builds online retail platforms and digital marketplace solutions'},
  {id:'te36',emoji:'🔌',name:'API Developer',sector:'Software Development',desc:'Designs and maintains application programming interfaces'},
  {id:'te37',emoji:'🔧',name:'Firmware Engineer',sector:'Infrastructure',desc:'Develops low-level embedded software for hardware devices'},
  {id:'te38',emoji:'🛠️',name:'Hardware Engineer',sector:'Infrastructure',desc:'Designs electronic circuits and physical computing components'},
  {id:'te39',emoji:'📡',name:'Telecommunications Engineer',sector:'Infrastructure',desc:'Builds and manages mobile, broadband, and satellite networks'},
  {id:'te40',emoji:'🛰️',name:'Satellite Communications Specialist',sector:'Infrastructure',desc:'Operates satellite links for remote broadband and broadcasting'},
  {id:'te41',emoji:'🌿',name:'AgriTech Developer',sector:'Software Development',desc:'Builds technology solutions for farming and food systems'},
  {id:'te42',emoji:'🏥',name:'Health Tech Specialist',sector:'Software Development',desc:'Develops digital health platforms and telemedicine systems'},
  {id:'te43',emoji:'📚',name:'EdTech Developer',sector:'Software Development',desc:'Builds e-learning platforms and educational technology tools'},
  {id:'te44',emoji:'🎮',name:'Game Developer',sector:'Software Development',desc:'Designs and builds interactive digital games and experiences'},
  {id:'te45',emoji:'🥽',name:'AR / VR Developer',sector:'Software Development',desc:'Creates augmented and virtual reality immersive experiences'},
  {id:'te46',emoji:'🚁',name:'Drone Software Developer',sector:'Software Development',desc:'Programs autonomous flight systems and drone data applications'},
  {id:'te47',emoji:'🔑',name:'IT Support Technician',sector:'Infrastructure',desc:'Resolves hardware, software, and connectivity issues for users'},
  {id:'te48',emoji:'📊',name:'Technology Policy Analyst',sector:'Product & Design',desc:'Researches and shapes regulation for emerging technologies'},
  {id:'te49',emoji:'🌍',name:'Digital Transformation Consultant',sector:'Product & Design',desc:'Guides organisations adopting digital technology and processes'},
  {id:'te50',emoji:'🌐',name:'Open Source Contributor',sector:'Software Development',desc:'Develops and maintains publicly available software for the community'},
],

arts: [
  {id:'ar01',emoji:'🎨',name:'Painter / Visual Artist',sector:'Visual Arts',desc:'Creates original paintings and visual artworks across media'},
  {id:'ar02',emoji:'🗿',name:'Sculptor',sector:'Visual Arts',desc:'Shapes stone, wood, metal, and clay into three-dimensional art'},
  {id:'ar03',emoji:'📸',name:'Photographer',sector:'Visual Arts',desc:'Captures images for art, journalism, and commercial purposes'},
  {id:'ar04',emoji:'✏️',name:'Graphic Designer',sector:'Visual Arts',desc:'Creates visual content for print, digital, and brand communication'},
  {id:'ar05',emoji:'🖌️',name:'Illustrator',sector:'Visual Arts',desc:'Creates drawings and illustrations for books, media, and brands'},
  {id:'ar06',emoji:'💻',name:'Digital Artist',sector:'Visual Arts',desc:'Creates art using digital software, tablets, and generative tools'},
  {id:'ar07',emoji:'🖼️',name:'Muralist',sector:'Visual Arts',desc:'Paints large-scale public murals on buildings and urban walls'},
  {id:'ar08',emoji:'🖨️',name:'Printmaker',sector:'Visual Arts',desc:'Creates art through etching, lithography, and screen-printing'},
  {id:'ar09',emoji:'🏺',name:'Ceramicist / Potter',sector:'Visual Arts',desc:'Shapes and fires clay into functional and sculptural ceramic works'},
  {id:'ar10',emoji:'🎀',name:'Textile / Adinkra Artist',sector:'Craft & Heritage',desc:'Creates symbolic cloth designs rooted in African visual traditions'},
  {id:'ar11',emoji:'🎭',name:'Mask Maker',sector:'Craft & Heritage',desc:'Carves ceremonial and artistic masks for cultural and ritual use'},
  {id:'ar12',emoji:'📿',name:'Bead Artisan',sector:'Craft & Heritage',desc:'Designs and crafts jewellery and accessories using traditional beads'},
  {id:'ar13',emoji:'🎋',name:'Calabash Carver',sector:'Craft & Heritage',desc:'Carves decorative and functional patterns on dried gourds'},
  {id:'ar14',emoji:'👘',name:'Batik / Tie-Dye Designer',sector:'Craft & Heritage',desc:'Creates fabric patterns through wax-resist and bound dyeing techniques'},
  {id:'ar15',emoji:'🧶',name:'Kente / Aso-Oke Weaver',sector:'Craft & Heritage',desc:'Weaves traditional prestige cloth using handloom techniques'},
  {id:'ar16',emoji:'🎭',name:'Actor / Performer',sector:'Performing Arts',desc:'Portrays characters in theatre, film, television, and digital media'},
  {id:'ar17',emoji:'🎬',name:'Stage Director',sector:'Performing Arts',desc:'Directs and coordinates theatrical productions from script to stage'},
  {id:'ar18',emoji:'✍️',name:'Playwright / Dramatist',sector:'Performing Arts',desc:'Writes scripts and plays for stage and screen performance'},
  {id:'ar19',emoji:'💃',name:'Contemporary Dancer',sector:'Performing Arts',desc:'Performs and choreographs modern and fusion dance styles'},
  {id:'ar20',emoji:'🥁',name:'Traditional Dancer',sector:'Performing Arts',desc:'Preserves and performs ceremonial and cultural dance traditions'},
  {id:'ar21',emoji:'🎵',name:'Choreographer',sector:'Performing Arts',desc:'Designs and rehearses dance sequences for productions'},
  {id:'ar22',emoji:'🎸',name:'Musician / Instrumentalist',sector:'Performing Arts',desc:'Performs on instruments across classical, folk, and contemporary genres'},
  {id:'ar23',emoji:'🎤',name:'Singer / Vocalist',sector:'Performing Arts',desc:'Performs vocal music across genres from highlife to gospel'},
  {id:'ar24',emoji:'🗣️',name:'Griot / Oral Historian',sector:'Literary Arts',desc:'Preserves and transmits history and wisdom through storytelling'},
  {id:'ar25',emoji:'🎙️',name:'Spoken Word Poet',sector:'Literary Arts',desc:'Performs original poetry blending verse with performance art'},
  {id:'ar26',emoji:'📚',name:'Novelist',sector:'Literary Arts',desc:'Writes long-form fiction exploring African life and experience'},
  {id:'ar27',emoji:'📄',name:'Short Story Writer',sector:'Literary Arts',desc:'Crafts short fiction for journals, anthologies, and digital media'},
  {id:'ar28',emoji:'🎞️',name:'Screenwriter',sector:'Literary Arts',desc:'Writes scripts for film, television, and digital streaming platforms'},
  {id:'ar29',emoji:'📝',name:'Poet',sector:'Literary Arts',desc:'Composes poetry exploring identity, culture, and the human experience'},
  {id:'ar30',emoji:'🎬',name:'Film Director',sector:'Film & Production',desc:'Leads the creative vision and execution of film productions'},
  {id:'ar31',emoji:'🎥',name:'Cinematographer / DOP',sector:'Film & Production',desc:'Designs and captures the visual language of film and video'},
  {id:'ar32',emoji:'✂️',name:'Film / Video Editor',sector:'Film & Production',desc:'Assembles and cuts footage into a coherent final film'},
  {id:'ar33',emoji:'🖥️',name:'Animator',sector:'Film & Production',desc:'Creates 2D and 3D animated content for film and digital media'},
  {id:'ar34',emoji:'👗',name:'Costume Designer',sector:'Film & Production',desc:'Designs and sources period and contemporary costumes for production'},
  {id:'ar35',emoji:'🎭',name:'Set Designer',sector:'Film & Production',desc:'Creates the physical environment and scenery for productions'},
  {id:'ar36',emoji:'💡',name:'Lighting Designer',sector:'Film & Production',desc:'Plans and operates stage and studio lighting for productions'},
  {id:'ar37',emoji:'🔊',name:'Sound Designer',sector:'Film & Production',desc:'Creates and mixes audio landscapes for film and theatre'},
  {id:'ar38',emoji:'🖼️',name:'Art Curator',sector:'Arts Management',desc:'Selects and presents artworks for galleries and exhibitions'},
  {id:'ar39',emoji:'🏛️',name:'Gallery Manager',sector:'Arts Management',desc:'Manages gallery operations, exhibitions, and artist relationships'},
  {id:'ar40',emoji:'🎪',name:'Arts Festival Organiser',sector:'Arts Management',desc:'Plans and coordinates arts festivals and cultural events'},
  {id:'ar41',emoji:'🎓',name:'Art Educator / Lecturer',sector:'Arts Management',desc:'Teaches studio art, art history, and creative practice'},
  {id:'ar42',emoji:'🌍',name:'Cultural Heritage Officer',sector:'Arts Management',desc:'Safeguards intangible and tangible cultural heritage assets'},
  {id:'ar43',emoji:'🏛️',name:'Museum Curator',sector:'Arts Management',desc:'Manages and interprets museum collections and public displays'},
  {id:'ar44',emoji:'📦',name:'Archivist',sector:'Arts Management',desc:'Preserves and provides access to historical and artistic records'},
  {id:'ar45',emoji:'💰',name:'Arts Grant Writer',sector:'Arts Management',desc:'Researches and writes funding applications for arts organisations'},
  {id:'ar46',emoji:'📢',name:'Arts Publicist',sector:'Arts Management',desc:'Promotes artists and cultural events through media outreach'},
  {id:'ar47',emoji:'🎚️',name:'Music Producer',sector:'Film & Production',desc:'Directs the creative and technical aspects of music recording'},
  {id:'ar48',emoji:'🎛️',name:'Recording Engineer',sector:'Film & Production',desc:'Operates recording equipment and mixes audio in music studios'},
  {id:'ar49',emoji:'🌍',name:'Cultural Ambassador',sector:'Arts Management',desc:'Represents African creative culture on regional and global stages'},
  {id:'ar50',emoji:'🎭',name:'Drama Therapist',sector:'Arts Management',desc:'Uses theatrical techniques to support mental health and healing'},
],

media: [
  {id:'me01',emoji:'📺',name:'News Anchor / TV Presenter',sector:'Broadcast',desc:'Presents news bulletins and live television programming'},
  {id:'me02',emoji:'📻',name:'Radio DJ / Presenter',sector:'Broadcast',desc:'Hosts radio programmes across music, talk, and news formats'},
  {id:'me03',emoji:'🎙️',name:'Podcast Host',sector:'Broadcast',desc:'Creates and presents audio podcast content on various topics'},
  {id:'me04',emoji:'🎥',name:'TV Field Reporter / Correspondent',sector:'Broadcast',desc:'Reports live from news locations for television broadcast'},
  {id:'me05',emoji:'📰',name:'Print Journalist',sector:'Print & Digital',desc:'Writes news, feature stories, and analysis for newspaper publications'},
  {id:'me06',emoji:'🔍',name:'Investigative Journalist',sector:'Print & Digital',desc:'Uncovers wrongdoing and corruption through in-depth research'},
  {id:'me07',emoji:'📸',name:'Photojournalist',sector:'Print & Digital',desc:'Captures news events and tells stories through photography'},
  {id:'me08',emoji:'🎬',name:'Video Journalist / VJ',sector:'Broadcast',desc:'Films, records, and edits their own broadcast news stories'},
  {id:'me09',emoji:'🎞️',name:'Documentary Film Maker',sector:'Production',desc:'Creates long-form films exploring social and cultural issues'},
  {id:'me10',emoji:'✍️',name:'News Editor',sector:'Print & Digital',desc:'Oversees story selection, quality, and editorial direction'},
  {id:'me11',emoji:'🖊️',name:'Sub-Editor / Copy Editor',sector:'Print & Digital',desc:'Edits and refines articles for accuracy, grammar, and style'},
  {id:'me12',emoji:'💻',name:'Content Creator / Influencer',sector:'Print & Digital',desc:'Produces engaging digital content for social media audiences'},
  {id:'me13',emoji:'📱',name:'Social Media Manager',sector:'PR & Communications',desc:'Manages brand and media presence across social platforms'},
  {id:'me14',emoji:'🌐',name:'Digital Editor / Web Editor',sector:'Print & Digital',desc:'Manages online news content, SEO, and digital publishing'},
  {id:'me15',emoji:'🎬',name:'News Producer',sector:'Production',desc:'Plans, sources, and coordinates news broadcast packages'},
  {id:'me16',emoji:'📡',name:'Broadcast Engineer',sector:'Tech & Data',desc:'Maintains transmission systems, studio equipment, and signals'},
  {id:'me17',emoji:'🎥',name:'Camera Operator',sector:'Production',desc:'Operates broadcast cameras for studio and field productions'},
  {id:'me18',emoji:'🔊',name:'Sound Recordist',sector:'Production',desc:'Captures and monitors audio quality during media production'},
  {id:'me19',emoji:'✂️',name:'Video Editor',sector:'Production',desc:'Assembles raw footage into polished broadcast-ready content'},
  {id:'me20',emoji:'🖥️',name:'Motion Graphics Designer',sector:'Production',desc:'Creates animated graphics and visual effects for broadcast media'},
  {id:'me21',emoji:'🎤',name:'Voiceover Artist',sector:'Production',desc:'Provides narration and voice characterisation for media content'},
  {id:'me22',emoji:'⚽',name:'Sports Commentator / Analyst',sector:'Broadcast',desc:'Provides live commentary and expert analysis for sports events'},
  {id:'me23',emoji:'🌤️',name:'Weather Presenter / Meteorologist',sector:'Broadcast',desc:'Presents weather forecasts for television and radio audiences'},
  {id:'me24',emoji:'📡',name:'Continuity Announcer',sector:'Broadcast',desc:'Links television programmes and delivers promotional announcements'},
  {id:'me25',emoji:'💼',name:'Advertising Executive',sector:'PR & Communications',desc:'Develops and manages advertising campaigns across media channels'},
  {id:'me26',emoji:'📊',name:'Media Buyer',sector:'PR & Communications',desc:'Plans and purchases advertising placements across media types'},
  {id:'me27',emoji:'📣',name:'Public Relations Officer',sector:'PR & Communications',desc:'Manages client reputation and relationships with the media'},
  {id:'me28',emoji:'🗣️',name:'Communications Director',sector:'PR & Communications',desc:'Leads strategic communications for an organisation or brand'},
  {id:'me29',emoji:'🤝',name:'Spokesperson / Media Liaison',sector:'PR & Communications',desc:'Represents an organisation in media interactions and briefings'},
  {id:'me30',emoji:'🏷️',name:'Brand Manager (Media)',sector:'PR & Communications',desc:'Develops and protects media organisation and client brand identity'},
  {id:'me31',emoji:'📊',name:'Audience Insight Analyst',sector:'Tech & Data',desc:'Tracks and analyses audience behaviour, ratings, and trends'},
  {id:'me32',emoji:'📅',name:'Media Planner',sector:'PR & Communications',desc:'Develops placement strategies to reach target media audiences'},
  {id:'me33',emoji:'✅',name:'Fact-Checker',sector:'Print & Digital',desc:'Verifies the accuracy of information before publication'},
  {id:'me34',emoji:'📈',name:'Data Journalist',sector:'Print & Digital',desc:'Uses datasets and analysis to uncover and tell data-driven stories'},
  {id:'me35',emoji:'🌐',name:'Media Ethicist',sector:'Print & Digital',desc:'Advises on editorial integrity, bias, and media responsibility'},
  {id:'me36',emoji:'📦',name:'Media Archivist',sector:'Tech & Data',desc:'Catalogues and preserves audio, video, and print media records'},
  {id:'me37',emoji:'💬',name:'Subtitles / Captioning Specialist',sector:'Production',desc:'Creates accurate subtitles and captions for accessibility and export'},
  {id:'me38',emoji:'📢',name:'Media Trainer',sector:'PR & Communications',desc:'Coaches public figures in effective media communication skills'},
  {id:'me39',emoji:'⚖️',name:'Broadcast Lawyer',sector:'PR & Communications',desc:'Advises on defamation, intellectual property, and broadcast law'},
  {id:'me40',emoji:'📋',name:'Rights Manager',sector:'PR & Communications',desc:'Manages intellectual property licensing and content distribution rights'},
  {id:'me41',emoji:'🏢',name:'Studio Manager',sector:'Production',desc:'Oversees studio operations, bookings, and technical facilities'},
  {id:'me42',emoji:'📡',name:'Transmission / Uplink Engineer',sector:'Tech & Data',desc:'Manages satellite uplinks and signal transmission for broadcast'},
  {id:'me43',emoji:'🌐',name:'Streaming Platform Engineer',sector:'Tech & Data',desc:'Builds and maintains digital live and on-demand streaming systems'},
  {id:'me44',emoji:'💰',name:'Media Sales Executive',sector:'PR & Communications',desc:'Sells advertising space and sponsorship packages to clients'},
  {id:'me45',emoji:'🎙️',name:'Radio Producer',sector:'Production',desc:'Plans and produces radio programmes, packages, and features'},
  {id:'me46',emoji:'🎬',name:'TV Show Producer',sector:'Production',desc:'Manages all creative and logistic aspects of a television production'},
  {id:'me47',emoji:'📐',name:'Market Research Analyst (Media)',sector:'Tech & Data',desc:'Studies consumer behaviour to inform media product development'},
  {id:'me48',emoji:'🖊️',name:'Copywriter (Advertising)',sector:'PR & Communications',desc:'Writes persuasive advertising and marketing copy for campaigns'},
  {id:'me49',emoji:'🤖',name:'AI Content Strategist',sector:'Tech & Data',desc:'Uses artificial intelligence tools to optimise content and publishing'},
  {id:'me50',emoji:'🌍',name:'Cultural Correspondent',sector:'Print & Digital',desc:'Reports on African arts, culture, heritage, and social movements'},
],

commerce: [
  {id:'co01',emoji:'🛒',name:'Market Trader',sector:'Retail',desc:'Buys and sells goods at local markets and trading posts'},
  {id:'co02',emoji:'🏪',name:'Retail Store Manager',sector:'Retail',desc:'Manages store operations, staff, and customer experience'},
  {id:'co03',emoji:'💵',name:'Shop Assistant / Cashier',sector:'Retail',desc:'Serves customers and processes retail sales transactions'},
  {id:'co04',emoji:'🖼️',name:'Visual Merchandiser',sector:'Retail',desc:'Designs product displays to maximise sales and appeal'},
  {id:'co05',emoji:'🤝',name:'Wholesale Distributor',sector:'Wholesale & Trade',desc:'Sources and distributes goods in bulk to retail businesses'},
  {id:'co06',emoji:'✈️',name:'Import / Export Agent',sector:'Wholesale & Trade',desc:'Coordinates the movement of goods across international borders'},
  {id:'co07',emoji:'📝',name:'Customs Broker',sector:'Wholesale & Trade',desc:'Handles customs documentation and duty payments for importers'},
  {id:'co08',emoji:'🚢',name:'Freight Forwarder',sector:'Wholesale & Trade',desc:'Arranges shipment of cargo via sea, air, road, and rail'},
  {id:'co09',emoji:'🗺️',name:'Shipping Coordinator',sector:'Wholesale & Trade',desc:'Tracks and manages cargo shipments through the supply chain'},
  {id:'co10',emoji:'🌍',name:'Cross-Border Trader',sector:'Wholesale & Trade',desc:'Operates in formal and informal trade markets across borders'},
  {id:'co11',emoji:'🖥️',name:'E-commerce Manager',sector:'E-Commerce',desc:'Manages online store operations, listings, and digital sales'},
  {id:'co12',emoji:'🛍️',name:'Marketplace Platform Operator',sector:'E-Commerce',desc:'Connects buyers and sellers on a digital marketplace platform'},
  {id:'co13',emoji:'📦',name:'Dropshipping Operator',sector:'E-Commerce',desc:'Sells products online without holding physical inventory stock'},
  {id:'co14',emoji:'📱',name:'Social Commerce Seller',sector:'E-Commerce',desc:'Sells products and services through social media platforms'},
  {id:'co15',emoji:'📲',name:'Mobile Money Agent',sector:'Finance & Admin',desc:'Facilitates digital cash-in and cash-out for community customers'},
  {id:'co16',emoji:'💳',name:'Point-of-Sale Technician',sector:'Finance & Admin',desc:'Installs and maintains electronic payment terminal systems'},
  {id:'co17',emoji:'📋',name:'Inventory Controller',sector:'Supply Chain',desc:'Manages stock levels, reconciliation, and inventory records'},
  {id:'co18',emoji:'🏭',name:'Warehouse Manager',sector:'Supply Chain',desc:'Oversees receiving, storage, and dispatch of goods in warehouses'},
  {id:'co19',emoji:'📦',name:'Stock Clerk',sector:'Supply Chain',desc:'Receives deliveries, organises shelving, and manages stock'},
  {id:'co20',emoji:'❄️',name:'Cold Chain Logistics Operator',sector:'Supply Chain',desc:'Manages temperature-controlled transport for perishable goods'},
  {id:'co21',emoji:'📊',name:'Supply Chain Analyst',sector:'Supply Chain',desc:'Optimises the flow of goods from supplier to end customer'},
  {id:'co22',emoji:'🤝',name:'Procurement Officer',sector:'Supply Chain',desc:'Sources and negotiates purchasing contracts with suppliers'},
  {id:'co23',emoji:'🛒',name:'Purchasing Agent',sector:'Supply Chain',desc:'Buys materials and goods on behalf of an organisation'},
  {id:'co24',emoji:'🏷️',name:'Category Manager',sector:'Retail',desc:'Develops product range strategy for specific retail categories'},
  {id:'co25',emoji:'💻',name:'Retail Technology Specialist',sector:'Retail',desc:'Implements POS, inventory, and e-commerce technology systems'},
  {id:'co26',emoji:'📈',name:'Revenue Manager',sector:'Finance & Admin',desc:'Optimises pricing and availability to maximise business revenue'},
  {id:'co27',emoji:'📉',name:'Pricing Analyst',sector:'Finance & Admin',desc:'Develops competitive pricing models and market benchmarks'},
  {id:'co28',emoji:'💰',name:'Trade Finance Officer',sector:'Finance & Admin',desc:'Structures letters of credit and import-export financing instruments'},
  {id:'co29',emoji:'🌾',name:'Agricultural Market Agent',sector:'Wholesale & Trade',desc:'Connects farmers to buyers in regional commodity markets'},
  {id:'co30',emoji:'🐄',name:'Livestock Trader',sector:'Wholesale & Trade',desc:'Buys and sells cattle, goats, and poultry across markets'},
  {id:'co31',emoji:'🌽',name:'Grain Trader',sector:'Wholesale & Trade',desc:'Trades bulk staple grains including maize, rice, and millet'},
  {id:'co32',emoji:'📦',name:'Commodity Broker',sector:'Wholesale & Trade',desc:'Facilitates raw material contracts between buyers and producers'},
  {id:'co33',emoji:'🌍',name:'Trade Commissioner',sector:'Wholesale & Trade',desc:'Promotes bilateral trade and investment between countries'},
  {id:'co34',emoji:'🏛️',name:'Commercial Attaché',sector:'Wholesale & Trade',desc:'Represents national trade interests at embassies abroad'},
  {id:'co35',emoji:'💼',name:'Business Development Manager',sector:'Retail',desc:'Identifies new markets and partners to drive business growth'},
  {id:'co36',emoji:'🤝',name:'Sales Representative',sector:'Retail',desc:'Builds client relationships and drives product sales revenue'},
  {id:'co37',emoji:'🏷️',name:'Brand Ambassador',sector:'Retail',desc:'Represents and promotes a product brand to target audiences'},
  {id:'co38',emoji:'📊',name:'Consumer Insights Analyst',sector:'Finance & Admin',desc:'Researches customer behaviour to inform retail strategy'},
  {id:'co39',emoji:'🤲',name:'Cooperative Manager',sector:'Wholesale & Trade',desc:'Leads and governs member-owned trading cooperative societies'},
  {id:'co40',emoji:'🌿',name:'Fair Trade Officer',sector:'Wholesale & Trade',desc:'Ensures ethical sourcing and fair pricing in trade relationships'},
  {id:'co41',emoji:'✅',name:'Quality Assurance Inspector (Retail)',sector:'Supply Chain',desc:'Verifies product quality and compliance before retail distribution'},
  {id:'co42',emoji:'🏢',name:'Franchise Manager',sector:'Retail',desc:'Manages franchise agreements and supports franchisee operations'},
  {id:'co43',emoji:'🔨',name:'Auction Coordinator',sector:'Wholesale & Trade',desc:'Organises live and online auctions for goods and commodities'},
  {id:'co44',emoji:'👑',name:'Market Queen / Iyaloja',sector:'Wholesale & Trade',desc:'Governs market operations through traditional authority and trust'},
  {id:'co45',emoji:'🍽️',name:'Street Food Vendor',sector:'Retail',desc:'Prepares and sells cooked meals and snacks in public spaces'},
  {id:'co46',emoji:'🌾',name:'Market Stall Owner',sector:'Retail',desc:'Operates a dedicated stall in an open or covered local market'},
  {id:'co47',emoji:'📦',name:'Vendor Manager',sector:'Supply Chain',desc:'Manages supplier performance, contracts, and relationships'},
  {id:'co48',emoji:'🔗',name:'Barcode & Systems Operator',sector:'Supply Chain',desc:'Manages item tracking, barcode scanning, and inventory systems'},
  {id:'co49',emoji:'🌐',name:'Cross-border E-commerce Specialist',sector:'E-Commerce',desc:'Manages international online sales and customs compliance'},
  {id:'co50',emoji:'🎯',name:'Product Manager (Retail)',sector:'Retail',desc:'Oversees the lifecycle of retail products from sourcing to sale'},
],

}
