'use client'
import * as React from 'react'

const C = {
  border: '#1e3a20', text: '#f0f7f0', sub: '#7da882', green: '#1a7c3e',
  gold: '#d4a017', muted: 'rgba(255,255,255,.06)',
}

const TEMPLATES = ['Daily Report', 'Weekly Summary', 'Client Report', 'Financial Report', 'Project Status']

const genContent = (tpl: string, from: string, to: string) => `
## ${tpl}
**Period:** ${from || 'N/A'} to ${to || 'N/A'}
**Generated by:** Griot AI · Viewdicon Platform
**Village:** Commerce Village

### Summary
This ${tpl.toLowerCase()} covers all activities and transactions within the selected period. Data has been sourced from your village tools including invoices, inventory logs, and session records.

### Key Metrics
- Total Transactions: 47
- Revenue Earned: ₡12,450
- New Clients: 8
- Sessions Opened: 14
- Top Activity: Quick Invoice (23 uses)

### Recommendations
1. Inventory stock for Palm Oil is below threshold — reorder recommended
2. Revenue trend is +12% vs previous period
3. 3 invoices are overdue — follow up required

### Conclusion
Overall performance for this period shows positive growth. Continue leveraging village tools for maximum Cowrie flow.

*Report sealed with AfroID: NG-YOR-••••-••••*
`

export default function ReportGenerator() {
  const [tpl, setTpl] = React.useState(TEMPLATES[0])
  const [from, setFrom] = React.useState('')
  const [to, setTo] = React.useState('')
  const [preview, setPreview] = React.useState(false)
  const [toast, setToast] = React.useState('')

  const showToast = (msg: string) => { setToast(msg); setTimeout(() => setToast(''), 3000) }

  return (
    <div>
      {toast && (
        <div style={{ position: 'fixed', bottom: 80, left: '50%', transform: 'translateX(-50%)', background: C.green, color: '#fff', borderRadius: 99, padding: '10px 20px', fontSize: 12, fontWeight: 700, zIndex: 999 }}>
          {toast}
        </div>
      )}

      {!preview ? (
        <div>
          <div style={{ marginBottom: 14 }}>
            <label style={{ fontSize: 10, fontWeight: 700, color: C.sub, display: 'block', marginBottom: 6, textTransform: 'uppercase', letterSpacing: '.06em' }}>Template</label>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
              {TEMPLATES.map(t => (
                <button key={t} onClick={() => setTpl(t)} style={{ padding: '10px 14px', borderRadius: 10, textAlign: 'left', cursor: 'pointer', border: `1px solid ${tpl === t ? C.green : C.border}`, background: tpl === t ? 'rgba(26,124,62,.15)' : C.muted, color: tpl === t ? '#4ade80' : C.text, fontSize: 13, fontWeight: tpl === t ? 700 : 400 }}>
                  {t}
                </button>
              ))}
            </div>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, marginBottom: 16 }}>
            {[['From', from, setFrom], ['To', to, setTo]].map(([lbl, val, setter]) => (
              <div key={String(lbl)}>
                <label style={{ fontSize: 10, fontWeight: 700, color: C.sub, display: 'block', marginBottom: 4 }}>{String(lbl)}</label>
                <input type="date" value={String(val)} onChange={e => (setter as (v: string) => void)(e.target.value)} style={{ width: '100%', background: C.muted, border: `1px solid ${C.border}`, borderRadius: 8, padding: '9px 10px', color: C.text, fontSize: 12, outline: 'none', boxSizing: 'border-box' }} />
              </div>
            ))}
          </div>

          <button onClick={() => setPreview(true)} style={{ width: '100%', padding: 12, borderRadius: 10, background: 'linear-gradient(90deg, #1a7c3e, #065f46)', color: '#fff', fontSize: 13, fontWeight: 700, border: 'none', cursor: 'pointer' }}>
            ✦ Auto-Generate Report
          </button>
        </div>
      ) : (
        <div>
          <div style={{ background: C.muted, border: `1px solid ${C.border}`, borderRadius: 12, padding: 16, marginBottom: 14 }}>
            <pre style={{ color: C.text, fontSize: 11, lineHeight: 1.6, whiteSpace: 'pre-wrap', fontFamily: 'inherit', margin: 0 }}>
              {genContent(tpl, from, to).trim()}
            </pre>
          </div>
          <div style={{ display: 'flex', gap: 8 }}>
            <button onClick={() => showToast('✓ PDF downloaded')} style={{ flex: 1, padding: 11, borderRadius: 10, background: C.green, color: '#fff', fontWeight: 700, fontSize: 12, border: 'none', cursor: 'pointer' }}>Download PDF</button>
            <button onClick={() => showToast('✓ Shared')} style={{ flex: 1, padding: 11, borderRadius: 10, background: C.muted, color: C.text, fontWeight: 700, fontSize: 12, border: `1px solid ${C.border}`, cursor: 'pointer' }}>Share</button>
            <button onClick={() => setPreview(false)} style={{ padding: '11px 14px', borderRadius: 10, background: C.muted, color: C.sub, fontSize: 12, border: `1px solid ${C.border}`, cursor: 'pointer' }}>← Edit</button>
          </div>
        </div>
      )}
    </div>
  )
}
