// ============================================================
// Mock posts — extracted from page.tsx for reuse
// Used as fallback when soro-soke-feed API is unreachable
// ============================================================
import type { Post } from './feedTypes'
import { drumFromType, heatStageFromScore } from './feedTypes'

/** Convert the old inline mock format to canonical Post */
function m(p: {
  id:string; type:string; skin:'ise'|'egbe'|'idile'
  authorName:string; village:string; av:string; avBg:string; avBorder:string
  crest?:string; verified?:boolean; time:string; heat:number
  content?:string; duration?:string; translation?:string
  productName?:string; price?:string; productEmoji?:string; pricePos?:number
  marketLow?:string; marketMid?:string; marketHigh?:string; location?:string
  proverbRoot?:string; proverbLang?:string
  oracleContent?:string; oracleAgree?:number
  tradeProduct?:string; tradeLocation?:string; tradeAmount?:string; tradeBuyer?:string; tradeSeller?:string
  noticeContent?:string; eventPayload?:string
  kila:number; stir:number; drum:number; ubuntu?:number; spray?:number
  scope:'village'|'region'|'nation'
  geoMin: 'village'|'state'|'country'|'continent'|'global'
}): Post {
  const typeMap: Record<string,string> = { text:'TEXT_DRUM', voice:'VOICE_STORY', market:'MARKET_LISTING', proverb:'PROVERB_CHAIN', oracle:'ORACLE_SESSION', proof:'TRADE_PROOF', notice:'VILLAGE_NOTICE', event:'EVENT_DRUM' }
  const postType = (typeMap[p.type] || 'TEXT_DRUM') as Post['type']
  return {
    id: p.id,
    type: postType,
    drum: drumFromType(postType, p.skin),
    author: p.authorName,
    afroId: '',
    avatarColor: p.avBg,
    village: p.village,
    villageEmoji: p.av,
    role: '',
    skinContext: p.skin,
    content: p.content || p.oracleContent || p.noticeContent || p.translation || '',
    tags: [],
    time: p.time,
    kilaCount: p.kila,
    stirCount: p.stir,
    ubuntuCount: p.ubuntu ?? 0,
    sprayTotal: p.spray ?? 0,
    commentCount: 0,
    drumScope: p.scope === 'nation' ? 3 : p.scope === 'region' ? 2 : 1,
    heatScore: p.heat,
    stage: heatStageFromScore(p.heat),
    crestTier: p.crest ? (p.crest === 'V' ? 5 : p.crest === 'IV' ? 4 : p.crest === 'III' ? 3 : p.crest === 'II' ? 2 : 1) : 0,
    nkisi: 'GREEN',
    geoMin: p.geoMin,
    scope: p.scope,
    // Optional fields
    productName: p.productName,
    productPrice: p.price ? parseFloat(p.price.replace(/[₡,\s]/g, '')) : undefined,
    productImageEmoji: p.productEmoji,
    location: p.location,
    proverbOrigin: p.proverbRoot,
    proverbLang: p.proverbLang,
    oracleTopic: p.oracleContent,
    oracleAgree: p.oracleAgree,
    tradePartner: p.tradeBuyer || p.tradeSeller,
    tradeAmount: p.tradeAmount ? parseFloat(p.tradeAmount.replace(/,/g, '')) : undefined,
    duration: p.duration,
    translation: p.translation,
    noticeContent: p.noticeContent,
    eventPayload: p.eventPayload,
  }
}

// ── All mock posts (28) ─────────────────────────────────────
export const MOCK_POSTS: Post[] = [
  // ── ISE skin ──
  m({ id:'td1',type:'text',skin:'ise',authorName:'Mama Ngozi',village:'🧺 Ìlú Oníṣòwò',av:'🧺',avBg:'rgba(224,123,0,.15)',avBorder:'rgba(224,123,0,.4)',crest:'IV',verified:true,time:'38m ago',heat:72,content:'Good morning traders! Tomato price at Mile 12: ₡3,200/bag. Farm gate ₡2,400 — excellent margin. Who has stock ready for Friday market?',kila:47,stir:12,drum:8,scope:'region',geoMin:'village' }),
  m({ id:'ml1',type:'market',skin:'ise',authorName:'Chioma Obi',village:'🧺 Ìlú Oníṣòwò',av:'🧺',avBg:'rgba(224,123,0,.15)',avBorder:'rgba(224,123,0,.4)',crest:'II',verified:true,time:'1h ago',heat:58,productName:'Fresh Tomatoes · 5 bags',price:'₡ 2,400',productEmoji:'🍅',pricePos:38,marketLow:'2,200',marketMid:'2,500',marketHigh:'2,800',location:'Lagos, Oshodi',kila:23,stir:5,drum:3,scope:'village',geoMin:'village' }),
  m({ id:'tp1',type:'proof',skin:'ise',authorName:'SYSTEM',village:'🧺 Ìlú Oníṣòwò',av:'✅',avBg:'rgba(74,222,128,.15)',avBorder:'rgba(74,222,128,.4)',crest:'',time:'3h ago',heat:88,tradeProduct:'50 bags Fresh Tomatoes',tradeLocation:'Lagos → Abuja',tradeAmount:'120,000',tradeBuyer:'Chioma O.',tradeSeller:'Kofi M.',kila:89,stir:0,drum:24,scope:'village',geoMin:'village' }),
  m({ id:'td2',type:'text',skin:'ise',authorName:'Kwame Mensah',village:'🌾 Ìlú Àgbẹ̀',av:'🌾',avBg:'rgba(26,124,62,.15)',avBorder:'rgba(26,124,62,.4)',crest:'III',verified:true,time:'4h ago',heat:65,content:'Cocoa harvest ready — 200 bags dried and graded. Looking for Commerce Village buyers. Export price: $2,580/MT. Village members get priority.',kila:34,stir:8,drum:15,scope:'region',geoMin:'village' }),
  m({ id:'ise-st1',type:'market',skin:'ise',authorName:'Bola Akins',village:'🧺 Ìlú Oníṣòwò · Ibadan',av:'🏙',avBg:'rgba(224,123,0,.15)',avBorder:'rgba(224,123,0,.3)',crest:'III',verified:true,time:'2h ago',heat:63,productName:'Cassava Flour · 80 bags premium grade',price:'₡ 1,850',productEmoji:'🌾',pricePos:30,marketLow:'1,600',marketMid:'1,900',marketHigh:'2,200',location:'Ibadan, Oyo State',kila:41,stir:7,drum:9,scope:'region',geoMin:'state' }),
  m({ id:'ise-st2',type:'text',skin:'ise',authorName:'Yetunde Falola',village:'🧺 Ìlú Oníṣòwò · Abeokuta',av:'🧺',avBg:'rgba(224,123,0,.15)',avBorder:'rgba(224,123,0,.4)',crest:'II',verified:true,time:'5h ago',heat:51,content:'State-wide price alert: Garri (white) is up 18% across Ogun and Lagos. Arbitrage opportunity — buy in Abeokuta at ₡800 and sell in Lagos at ₡1,050. Traders — move fast before others spot this.',kila:28,stir:14,drum:6,scope:'region',geoMin:'state' }),
  m({ id:'ise-st3',type:'proof',skin:'ise',authorName:'SYSTEM',village:'🏙 Lagos–Ogun Trade Corridor',av:'✅',avBg:'rgba(74,222,128,.15)',avBorder:'rgba(74,222,128,.4)',crest:'',time:'1h ago',heat:74,tradeProduct:'200 bags Cassava',tradeLocation:'Abeokuta → Lagos Island',tradeAmount:'370,000',tradeBuyer:'Mama Folake',tradeSeller:'Adewale Farms',kila:55,stir:0,drum:12,scope:'region',geoMin:'state' }),
  m({ id:'ise-ng1',type:'oracle',skin:'ise',authorName:'Commerce Elder Council',village:'🌍 National Trade Forum',av:'⚡',avBg:'rgba(212,160,23,.15)',avBorder:'rgba(212,160,23,.4)',crest:'V',time:'LIVE',heat:88,oracleContent:'Motion before the Nation: Should Viewdicon adopt a unified price index for all 20 villages?',oracleAgree:72,kila:634,stir:201,drum:143,scope:'nation',geoMin:'country' }),
  m({ id:'ise-ng2',type:'text',skin:'ise',authorName:'Griot Orunmila · Nigeria',village:'🌍 Nation Drum',av:'🦅',avBg:'rgba(212,160,23,.15)',avBorder:'rgba(212,160,23,.4)',crest:'V',verified:true,time:'1h ago',heat:84,content:'🇳🇬 National Market Report: Tomatoes surging 22% across South-West. Cocoa export receipts hit ₡14.2M this week.',kila:312,stir:18,drum:89,scope:'nation',geoMin:'country' }),
  m({ id:'ise-af1',type:'proverb',skin:'ise',authorName:'Pan-African Elder Circle',village:'🌐 Africa Drum',av:'🌍',avBg:'rgba(212,160,23,.12)',avBorder:'rgba(212,160,23,.35)',crest:'V',time:'3h ago',heat:79,proverbRoot:'"Nchi bila watu ni msitu — A land without people is a forest"',proverbLang:'🇹🇿 Swahili · Shared across 6 nations',kila:891,stir:44,drum:267,scope:'nation',geoMin:'continent' }),
  m({ id:'ise-af2',type:'market',skin:'ise',authorName:'Kofi Asante · Ghana',village:'🌾 Ìlú Àgbẹ̀ · Kumasi',av:'🌾',avBg:'rgba(26,124,62,.15)',avBorder:'rgba(26,124,62,.4)',crest:'IV',verified:true,time:'4h ago',heat:70,productName:'Premium Cocoa · 500MT export grade',price:'₡ 28,400',productEmoji:'🫘',pricePos:42,marketLow:'26,000',marketMid:'28,000',marketHigh:'31,000',location:'Kumasi, Ghana',kila:178,stir:23,drum:54,scope:'nation',geoMin:'continent' }),
  m({ id:'ise-gl1',type:'text',skin:'ise',authorName:'Diaspora Commerce Hub',village:'⭐ Global Village',av:'⭐',avBg:'rgba(255,215,0,.1)',avBorder:'rgba(255,215,0,.3)',crest:'V',verified:true,time:'6h ago',heat:91,content:'🌍 Diaspora Bridge: UK-based traders seeking genuine West African cocoa and shea butter directly from farm.',kila:1240,stir:67,drum:389,scope:'nation',geoMin:'global' }),
  // ── EGBE skin ──
  m({ id:'pc1',type:'proverb',skin:'egbe',authorName:'Elder Adaeze',village:'🧺 Ìlú Oníṣòwò',av:'👵',avBg:'rgba(212,160,23,.15)',avBorder:'rgba(212,160,23,.4)',crest:'V',time:'5h ago',heat:91,proverbRoot:'"Agbado tí a bá jẹ papọ̀ ní dun"',proverbLang:'🇳🇬 Yoruba · Shared by Elder Adaeze',kila:112,stir:8,drum:44,scope:'nation',geoMin:'village' }),
  m({ id:'vs1',type:'voice',skin:'egbe',authorName:'Griot Seun',village:'🎙 Ìlú Ìtàn',av:'🎙',avBg:'rgba(79,70,229,.15)',avBorder:'rgba(79,70,229,.4)',crest:'IV',verified:true,time:'2h ago',heat:95,duration:'3:00',translation:'"I tell you today the story of the first market at Ile-Ife..."',kila:203,stir:0,drum:67,spray:45,scope:'nation',geoMin:'village' }),
  m({ id:'or1',type:'oracle',skin:'egbe',authorName:'Oracle Council',village:'🏛 Ìlú Ìgbìmọ',av:'⚡',avBg:'rgba(212,160,23,.15)',avBorder:'rgba(212,160,23,.4)',crest:'III',time:'LIVE',heat:96,oracleContent:'Should the Agriculture Village set a minimum price floor for cocoa farmers in West Africa?',oracleAgree:68,kila:450,stir:180,drum:89,scope:'nation',geoMin:'village' }),
  m({ id:'egbe-st1',type:'voice',skin:'egbe',authorName:'Griot Yemi · Ogun',village:'🎙 Ìlú Ìtàn · Abeokuta',av:'🎙',avBg:'rgba(79,70,229,.15)',avBorder:'rgba(79,70,229,.4)',crest:'III',verified:true,time:'3h ago',heat:77,duration:'2:14',translation:'"The masquerade that dances for the whole state must know the language of every town."',kila:89,stir:12,drum:27,scope:'region',geoMin:'state' }),
  m({ id:'egbe-ng1',type:'proverb',skin:'egbe',authorName:'National Griot Assembly',village:'🌍 Nation Drum',av:'🦅',avBg:'rgba(212,160,23,.15)',avBorder:'rgba(212,160,23,.4)',crest:'V',time:'2h ago',heat:89,proverbRoot:'"Onye wetara oji wetara ndụ" — He who brings kola brings life',proverbLang:'🇳🇬 Igbo · National Proverb · 12 villages agreed',kila:445,stir:27,drum:132,scope:'nation',geoMin:'country' }),
  m({ id:'egbe-af1',type:'oracle',skin:'egbe',authorName:'Pan-African Oracle',village:'🌐 Africa Drum',av:'🌍',avBg:'rgba(212,160,23,.1)',avBorder:'rgba(212,160,23,.35)',crest:'V',time:'LIVE',heat:93,oracleContent:'Pan-African Motion: Should Viewdicon expand to all 54 African nations by 2027 or focus on West Africa first?',oracleAgree:61,kila:2340,stir:890,drum:560,scope:'nation',geoMin:'continent' }),
  m({ id:'egbe-gl1',type:'voice',skin:'egbe',authorName:'Griot Diaspora · London',village:'⭐ Global Village',av:'🌍',avBg:'rgba(255,215,0,.1)',avBorder:'rgba(255,215,0,.3)',crest:'IV',verified:true,time:'8h ago',heat:88,duration:'4:22',translation:'"To all our brothers and sisters in the diaspora — your homeland speaks to you through these drums."',kila:3201,stir:144,drum:891,spray:234,scope:'nation',geoMin:'global' }),
  // ── IDILE skin ──
  m({ id:'td3',type:'text',skin:'idile',authorName:'Papa Emeka',village:'🌳 Family Circle',av:'🧔',avBg:'rgba(124,58,237,.15)',avBorder:'rgba(124,58,237,.4)',crest:'IV',time:'1h ago',heat:55,content:'My children — the Okonkwo compound land title has been uploaded to the Ancestral Vault. Five signatures required.',kila:12,stir:0,drum:2,ubuntu:8,scope:'village',geoMin:'village' }),
  m({ id:'vn1',type:'notice',skin:'idile',authorName:'Elder Council',village:'🏛 Village Council',av:'📯',avBg:'rgba(212,160,23,.15)',avBorder:'rgba(212,160,23,.4)',crest:'V',time:'30m ago',heat:78,noticeContent:'VILLAGE NOTICE: The Night Market opens at 6PM today. Crest III+ market vendors may pin products to Jollof TV streams.',kila:56,stir:0,drum:18,scope:'village',geoMin:'village' }),
  m({ id:'idile-st1',type:'notice',skin:'idile',authorName:'Oyo State Family Council',village:'🏙 Àgbájọ Ìdílé · Oyo',av:'📯',avBg:'rgba(124,58,237,.15)',avBorder:'rgba(124,58,237,.4)',crest:'IV',time:'4h ago',heat:62,noticeContent:'STATE FAMILY NOTICE: The Oyo State naming ceremony registry is now live.',kila:34,stir:0,drum:8,scope:'region',geoMin:'state' }),
  m({ id:'idile-ng1',type:'text',skin:'idile',authorName:'National Ancestral Council',village:'🌍 Ìdílé Nigeria',av:'🌍',avBg:'rgba(124,58,237,.1)',avBorder:'rgba(124,58,237,.35)',crest:'V',verified:true,time:'6h ago',heat:81,content:'🇳🇬 National Family Registry milestone: 50,000 verified family trees across Nigeria.',kila:892,stir:23,drum:201,ubuntu:340,scope:'nation',geoMin:'country' }),
  m({ id:'idile-af1',type:'proverb',skin:'idile',authorName:'African Elders Collective',village:'🌐 Pan-African Elders',av:'👑',avBg:'rgba(212,160,23,.12)',avBorder:'rgba(212,160,23,.35)',crest:'V',time:'12h ago',heat:85,proverbRoot:'"Mtu ni watu — A person is people"',proverbLang:'🌍 Pan-African · 6 language translations active',kila:4120,stir:89,drum:1240,scope:'nation',geoMin:'continent' }),
  m({ id:'idile-gl1',type:'text',skin:'idile',authorName:'Diaspora Family Network',village:'⭐ Global Ìdílé',av:'⭐',avBg:'rgba(255,215,0,.1)',avBorder:'rgba(255,215,0,.3)',crest:'V',verified:true,time:'1d ago',heat:90,content:'🌍 To African families scattered across the globe — your roots are not lost. The Ancestral Vault crosses borders.',kila:5670,stir:234,drum:1890,ubuntu:2100,scope:'nation',geoMin:'global' }),
  // ── Events ──
  m({ id:'ev-001',type:'event',skin:'ise',authorName:'AfriTech Lagos',village:'⚡ Technology Village',av:'⚡',avBg:'rgba(59,130,246,.15)',avBorder:'rgba(59,130,246,.4)',crest:'V',verified:true,time:'2h ago',heat:88,kila:412,stir:67,drum:189,scope:'nation',geoMin:'country',eventPayload:'{"__type":"event_drum","eventId":"evt-001","title":"AfriTech Summit 2026","eventType":"CONFERENCE"}' }),
  m({ id:'ev-002',type:'event',skin:'egbe',authorName:'Arts Village Connector',village:'🎨 Arts Village',av:'🎨',avBg:'rgba(139,92,246,.15)',avBorder:'rgba(139,92,246,.4)',crest:'IV',verified:true,time:'5h ago',heat:82,kila:289,stir:54,drum:98,scope:'nation',geoMin:'country',eventPayload:'{"__type":"event_drum","eventId":"evt-003","title":"Moonrise Music Festival","eventType":"FESTIVAL"}' }),
  m({ id:'ev-003',type:'event',skin:'idile',authorName:'Sports Village',village:'🏅 Sports Village',av:'🏅',avBg:'rgba(239,68,68,.15)',avBorder:'rgba(239,68,68,.4)',crest:'III',verified:true,time:'8h ago',heat:79,kila:334,stir:45,drum:122,scope:'village',geoMin:'village',eventPayload:'{"__type":"event_drum","eventId":"evt-006","title":"Pan-African Football Day","eventType":"SPORTS"}' }),
]

// ── Gallery mock posts — IMAGE_JOURNAL cards for gallery lens ──
export const MOCK_GALLERY_POSTS: Post[] = [
  { id:'g1', type:'IMAGE_JOURNAL', drum:'aworan', author:'Zara Fashions', afroId:'AFR-NGA-FSH-010567', avatarColor:'rgba(236,72,153,.3)', village:'Fashion', villageEmoji:'👗', role:'Designer', skinContext:'ise', content:'New Ankara collection — hand-stitched Aso-oke border detail, 100% original. Thread imported from Kano 🧵', tags:['fashion','ankara','aso-oke'], time:'1h ago', kilaCount:678, stirCount:145, ubuntuCount:89, sprayTotal:0, commentCount:92, drumScope:2, heatScore:84, stage:'FEAST', crestTier:3, nkisi:'GREEN', imageUrls:['🧵','👗','🪡'], captionLocale:'en' },
  { id:'g2', type:'IMAGE_JOURNAL', drum:'aworan', author:'Chef Amara Nwosu', afroId:'AFR-NGA-HSP-010452', avatarColor:'rgba(178,34,34,.3)', village:'Hospitality', villageEmoji:'🍽', role:'Master Chef', skinContext:'egbe', content:'Traditional Ofe Akwu — palm nut soup made from fresh-squeezed nuts, recipe passed 4 generations 🍲', tags:['food','palmnut','tradition'], time:'3h ago', kilaCount:445, stirCount:89, ubuntuCount:67, sprayTotal:0, commentCount:56, drumScope:1, heatScore:77, stage:'FEAST', crestTier:2, nkisi:'GREEN', imageUrls:['🍲','🌴','🫙'], captionLocale:'en' },
  { id:'g3', type:'IMAGE_JOURNAL', drum:'aworan', author:'Kemi Adeola · Lagosian Lens', afroId:'AFR-NGA-ART-010334', avatarColor:'rgba(124,58,237,.3)', village:'Arts', villageEmoji:'🎨', role:'Visual Storyteller', skinContext:'egbe', content:'30 days of Adinkra — Day 22: Dwennimmen (🐏 horns) means strength through humility. Study in ink 🖌', tags:['art','adinkra','visual'], time:'5h ago', kilaCount:312, stirCount:78, ubuntuCount:44, sprayTotal:0, commentCount:38, drumScope:2, heatScore:71, stage:'BOIL', crestTier:3, nkisi:'GREEN', imageUrls:['🖼','🎨','🪶'], captionLocale:'en' },
  { id:'g4', type:'IMAGE_JOURNAL', drum:'aworan', author:'Kofi Mensah · Accra', afroId:'AFR-GHA-BLD-010123', avatarColor:'rgba(26,124,62,.3)', village:'Builders', villageEmoji:'🏗', role:'Architect', skinContext:'ise', content:'Completed — 8-unit affordable housing in Accra Nima. All locally-sourced laterite block, zero imports 🏘', tags:['builders','affordable','ghana'], time:'8h ago', kilaCount:891, stirCount:234, ubuntuCount:345, sprayTotal:0, commentCount:167, drumScope:3, heatScore:88, stage:'FEAST', crestTier:4, nkisi:'GREEN', imageUrls:['🏗','🏘','🪵'], captionLocale:'en' },
  { id:'g5', type:'IMAGE_JOURNAL', drum:'aworan', author:'Dr. Amaka Osei', afroId:'AFR-NGA-HLT-050078', avatarColor:'rgba(3,105,161,.3)', village:'Health', villageEmoji:'⚕', role:'Village Doctor', skinContext:'ise', content:'Community vaccination day — 847 villagers reached across 3 settlements in Anambra ⚕️🌿', tags:['health','vaccination','community'], time:'12h ago', kilaCount:567, stirCount:23, ubuntuCount:412, sprayTotal:0, commentCount:45, drumScope:2, heatScore:76, stage:'BOIL', crestTier:4, nkisi:'GREEN', imageUrls:['⚕️','💉','🌿'], captionLocale:'en' },
  { id:'g6', type:'MARKET_LISTING', drum:'aworan', author:'Adunni Textiles', afroId:'AFR-NGA-COM-220445', avatarColor:'rgba(224,123,0,.15)', village:'Commerce', villageEmoji:'🧺', role:'Market Vendor', skinContext:'ise', content:'Premium Kente cloth direct from Kumasi artisans — 12 yards, museum-quality ashanti weave', tags:['kente','fashion','commerce'], time:'2h ago', kilaCount:234, stirCount:56, ubuntuCount:12, sprayTotal:0, commentCount:34, drumScope:1, heatScore:68, stage:'SIMMER', crestTier:2, nkisi:'GREEN', productName:'Premium Kente Cloth · 12 yards', productPrice:18500, productImageEmoji:'🧢', location:'Lagos Island', imageUrls:['🧢','🎨','✨'], captionLocale:'en' },
]

// ── Discover mock posts — cross-village, all skins, react-only ──
export const MOCK_DISCOVER_POSTS: Post[] = [
  { id:'dsc1', type:'VOICE_STORY', drum:'soro_soke', author:'Griot Yemi · Ogun State', afroId:'AFR-NGA-MED-00431', avatarColor:'rgba(79,70,229,.3)', village:'Media', villageEmoji:'🎙', role:'Griot', skinContext:'egbe', content:'"The masquerade that dances for the whole state must learn the language of every town." — In Yoruba, Igbo, Hausa, French 🌍', tags:['griot','diaspora','voice'], time:'34m ago', kilaCount:534, stirCount:12, ubuntuCount:201, sprayTotal:0, commentCount:89, drumScope:3, heatScore:91, stage:'FEAST', crestTier:4, nkisi:'GREEN', duration:'2:14', translation:'"Masquerade narị n\'ụlọ obodo gbọọ asụsụ obodo ya"', audioDurationSec:134, spiritVoiceEnabled:true },
  { id:'dsc2', type:'MARKET_LISTING', drum:'aworan', author:'Kofi Asante · Kumasi', afroId:'AFR-GHA-AGR-00112', avatarColor:'rgba(26,124,62,.2)', village:'Agriculture', villageEmoji:'🌾', role:'Cocoa Farmer', skinContext:'ise', content:'Harvest season — premium grade A dried cocoa beans direct from Ashanti Region. Exporters contact me.', tags:['cocoa','agriculture','export'], time:'1h ago', kilaCount:178, stirCount:23, ubuntuCount:45, sprayTotal:0, commentCount:34, drumScope:3, heatScore:74, stage:'BOIL', crestTier:3, nkisi:'GREEN', productName:'Grade A Cocoa · 500MT', productPrice:28400, productImageEmoji:'🫘', location:'Kumasi, Ghana' },
  { id:'dsc3', type:'ORACLE_SESSION', drum:'soro_soke', author:'Commerce Elder Council', afroId:'AFR-NGA-COM-00001', avatarColor:'rgba(212,160,23,.15)', village:'Commerce', villageEmoji:'🧺', role:'Elder', skinContext:'ise', content:'Should Viewdicon adopt a unified Cowrie price index across all 20 villages?', tags:['oracle','policy','commerce'], time:'LIVE', kilaCount:634, stirCount:201, ubuntuCount:143, sprayTotal:0, commentCount:87, drumScope:3, heatScore:88, stage:'FEAST', crestTier:5, nkisi:'GREEN', oracleTopic:'Unified Cowrie price index across villages?', oracleAgree:72 },
  { id:'dsc4', type:'IMAGE_JOURNAL', drum:'aworan', author:'Sports Village · Abuja', afroId:'AFR-NGA-SPT-00889', avatarColor:'rgba(239,68,68,.2)', village:'Sports', villageEmoji:'🏅', role:'Coach', skinContext:'ise', content:'Under-17 Pan-African Football Camp — Day 3 drills. 24 nations represented on this pitch 🏟', tags:['football','panAfrican','youth'], time:'2h ago', kilaCount:1240, stirCount:67, ubuntuCount:389, sprayTotal:0, commentCount:201, drumScope:3, heatScore:91, stage:'FEAST', crestTier:3, nkisi:'GREEN', imageUrls:['🏟','⚽','🏅'] },
  { id:'dsc5', type:'PROVERB_CHAIN', drum:'soro_soke', author:'Pan-Africa Elders', afroId:'AFR-PAN-SPR-00001', avatarColor:'rgba(212,160,23,.12)', village:'Spirituality', villageEmoji:'🕯', role:'Elder', skinContext:'idile', content:'"Mtu ni watu — A person is people." Shared in 6 nations, 14 proverb branches added.', tags:['proverb','ubuntu','wisdom'], time:'4h ago', kilaCount:4120, stirCount:89, ubuntuCount:1240, sprayTotal:0, commentCount:445, drumScope:3, heatScore:96, stage:'FEAST', crestTier:5, nkisi:'GREEN', proverbOrigin:'"Mtu ni watu — A person is people"', proverbLang:'🌍 Swahili · 6 nations · 14 branches' },
  { id:'dsc6', type:'TEXT_DRUM', drum:'soro_soke', author:'Tech Village · Lagos', afroId:'AFR-NGA-TEC-00567', avatarColor:'rgba(59,130,246,.2)', village:'Technology', villageEmoji:'⚡', role:'Engineer', skinContext:'ise', content:'Live deployment: Viewdicon\'s Afrikonnect event bus just processed its 1,000,000th message 🎉 #milestone #afrotech @BuildersVillage @CommerceVillage', tags:['tech','milestone','afrotech'], time:'20m ago', kilaCount:2340, stirCount:890, ubuntuCount:560, sprayTotal:0, commentCount:312, drumScope:3, heatScore:97, stage:'FEAST', crestTier:4, nkisi:'GREEN' },
  { id:'dsc7', type:'VOICE_STORY', drum:'idile_circle', author:'Diaspora Griot · London', afroId:'AFR-GBR-MED-00234', avatarColor:'rgba(255,215,0,.1)', village:'Media', villageEmoji:'🎙', role:'Griot Diaspora', skinContext:'idile', content:'"To all our brothers and sisters scattered across oceans — your homeland speaks through these drums."', tags:['diaspora','voice','homecoming'], time:'6h ago', kilaCount:3201, stirCount:144, ubuntuCount:891, sprayTotal:0, commentCount:234, drumScope:3, heatScore:95, stage:'FEAST', crestTier:4, nkisi:'GREEN', duration:'4:22', audioDurationSec:262, spiritVoiceEnabled:true },
  { id:'dsc8', type:'MARKET_LISTING', drum:'aworan', author:'Mama Ngozi · Oshodi', afroId:'AFR-NGA-HSP-00201', avatarColor:'rgba(224,123,0,.15)', village:'Hospitality', villageEmoji:'🍽', role:'Master Chef', skinContext:'egbe', content:'Launching: Artisanal jollof spice blend — stone-ground, no preservatives, ships nationwide 🫙', tags:['food','spice','jollof'], time:'45m ago', kilaCount:892, stirCount:178, ubuntuCount:67, sprayTotal:0, commentCount:124, drumScope:2, heatScore:82, stage:'FEAST', crestTier:3, nkisi:'GREEN', productName:'Authentic Jollof Spice Blend · 500g', productPrice:3200, productImageEmoji:'🫙', location:'Lagos, Oshodi' },
  { id:'dsc9', type:'PROVERB_CHAIN', drum:'soro_soke', author:'Education Village', afroId:'AFR-NGA-EDU-00099', avatarColor:'rgba(79,70,229,.2)', village:'Education', villageEmoji:'📚', role:'Teacher', skinContext:'egbe', content:'"Akwukwo n\'azu n\'ihu" — One who does not look forward and backward will walk into trees. 7 language proverb chain now active.', tags:['education','proverb','wisdom'], time:'3h ago', kilaCount:667, stirCount:44, ubuntuCount:222, sprayTotal:0, commentCount:89, drumScope:3, heatScore:79, stage:'FEAST', crestTier:3, nkisi:'GREEN', proverbOrigin:'"Akwukwo n\'azu n\'ihu" — Look forward and backward', proverbLang:'🇳🇬 Igbo · 7 language chain' },
  { id:'dsc10', type:'TEXT_DRUM', drum:'soro_soke', author:'National Griot Assembly', afroId:'AFR-NGA-GOV-00003', avatarColor:'rgba(212,160,23,.15)', village:'Government', villageEmoji:'🏛', role:'Elder Speaker', skinContext:'idile', content:'🇳🇬 National milestone: 50,000 verified family trees across all 36 states now in the Ancestral Vault. #ìdílé #heritage #AfricaRemembers', tags:['idile','heritage','milestone'], time:'1h ago', kilaCount:5670, stirCount:234, ubuntuCount:2100, sprayTotal:0, commentCount:890, drumScope:3, heatScore:99, stage:'FEAST', crestTier:5, nkisi:'GREEN' },
]

// ── Motion mock posts (8) ───────────────────────────────────
export const MOCK_MOTION_POSTS: Post[] = [
  { id:'m1', type:'VIDEO_STORY', drum:'oriki', author:'Mama Kemi', afroId:'AFR-NGA-COM-010201', avatarColor:'rgba(224,123,0,.3)', village:'Commerce', villageEmoji:'🧺', role:'Market Queen', skinContext:'ise', content:'Fresh tomatoes arriving at Mile 12 market — watch the quality check live! 🍅', tags:['market','tomatoes','commerce'], time:'2m ago', kilaCount:142, stirCount:33, ubuntuCount:18, sprayTotal:0, commentCount:27, drumScope:1, heatScore:88, stage:'FEAST', crestTier:4, nkisi:'GREEN', videoUrl:'', videoDurationSec:45 },
  { id:'m2', type:'IMAGE_JOURNAL', drum:'aworan', author:'Adaeze Obi', afroId:'AFR-NGA-ART-010334', avatarColor:'rgba(124,58,237,.3)', village:'Arts', villageEmoji:'🎨', role:'Visual Storyteller', skinContext:'egbe', content:'My journey through 30 days of Adinkra pattern design 🖌', tags:['art','adinkra','design'], time:'18m ago', kilaCount:289, stirCount:67, ubuntuCount:44, sprayTotal:0, commentCount:51, drumScope:2, heatScore:95, stage:'FEAST', crestTier:3, nkisi:'GREEN', imageUrls:[], captionLocale:'en' },
  { id:'m3', type:'AUDIO_LETTER', drum:'soro_soke', author:'Griot Seun Kuti', afroId:'AFR-NGA-MED-010089', avatarColor:'rgba(79,70,229,.3)', village:'Media', villageEmoji:'🎙', role:'Griot Storyteller', skinContext:'egbe', content:'A letter to the diaspora — "Your roots run deeper than the ocean that separates us." 🌍', tags:['griot','diaspora','heritage'], time:'1h ago', kilaCount:534, stirCount:12, ubuntuCount:201, sprayTotal:0, commentCount:89, drumScope:3, heatScore:96, stage:'FEAST', crestTier:5, nkisi:'GREEN', audioDurationSec:180, spiritVoiceEnabled:true },
  { id:'m4', type:'VIDEO_STORY', drum:'oriki', author:'Chef Tolu', afroId:'AFR-NGA-HSP-010452', avatarColor:'rgba(178,34,34,.3)', village:'Hospitality', villageEmoji:'🍽', role:'Master Chef', skinContext:'ise', content:'Making Jollof Rice the traditional way — fire, iron pot, wooden spoon. 🍚🔥', tags:['jollof','cooking','tradition'], time:'3h ago', kilaCount:891, stirCount:234, ubuntuCount:67, sprayTotal:0, commentCount:156, drumScope:2, heatScore:92, stage:'FEAST', crestTier:3, nkisi:'GREEN', videoUrl:'', videoDurationSec:120 },
  { id:'m5', type:'TEXT_DRUM', drum:'soro_soke', author:'Elder Council', afroId:'AFR-NGA-GOV-010001', avatarColor:'rgba(212,160,23,.3)', village:'Government', villageEmoji:'🏛', role:'Elder Speaker', skinContext:'egbe', content:'"Ẹni tó ń ta ìbon sókè, ìbẹ̀ ni ó ti bọ̀ sílẹ̀" — He who shoots bullets into the sky will have them rain down.\n\nLet us build, not destroy.', tags:['proverb','wisdom','governance'], time:'5h ago', kilaCount:1247, stirCount:34, ubuntuCount:456, sprayTotal:0, commentCount:201, drumScope:3, heatScore:97, stage:'FEAST', crestTier:5, nkisi:'GREEN' },
  { id:'m6', type:'IMAGE_JOURNAL', drum:'aworan', author:'Zara Fashions', afroId:'AFR-NGA-FSH-010567', avatarColor:'rgba(236,72,153,.3)', village:'Fashion', villageEmoji:'👗', role:'Designer', skinContext:'ise', content:'New Ankara collection dropping this week 🧵', tags:['fashion','ankara','heritage'], time:'6h ago', kilaCount:678, stirCount:145, ubuntuCount:89, sprayTotal:0, commentCount:92, drumScope:2, heatScore:84, stage:'FEAST', crestTier:2, nkisi:'GREEN', imageUrls:[], captionLocale:'en' },
  { id:'m7', type:'AUDIO_LETTER', drum:'idile_circle', author:'DJ Blackstar', afroId:'AFR-GHA-ART-010789', avatarColor:'rgba(26,124,62,.3)', village:'Arts', villageEmoji:'🎨', role:'Sound Architect', skinContext:'idile', content:'Pan-African beats mixtape — blending Afrobeats, Highlife, Amapiano 🥁🎶', tags:['music','panAfrican','mix'], time:'8h ago', kilaCount:423, stirCount:89, ubuntuCount:167, sprayTotal:0, commentCount:45, drumScope:3, heatScore:79, stage:'FEAST', crestTier:3, nkisi:'GREEN', audioDurationSec:240, spiritVoiceEnabled:false },
  { id:'m8', type:'VIDEO_STORY', drum:'oriki', author:'Kwame Builder', afroId:'AFR-GHA-BLD-010123', avatarColor:'rgba(26,124,62,.3)', village:'Builders', villageEmoji:'🏗', role:'Architect', skinContext:'ise', content:'Building Africa\'s first 3D-printed school in Kumasi 🏫', tags:['building','innovation','education'], time:'12h ago', kilaCount:1034, stirCount:278, ubuntuCount:345, sprayTotal:0, commentCount:187, drumScope:3, heatScore:99, stage:'FEAST', crestTier:4, nkisi:'GREEN', videoUrl:'', videoDurationSec:90 },
]
