// UI Component exports — single import point
export { Avatar, VILLAGE_COLORS }       from './Avatar'
export { Badge }                         from './Badge'
export type { BadgeVariant, BadgeSize }  from './Badge'
export { Button }                        from './Button'
export type { ButtonProps }              from './Button'
export { Card, CardHeader, CardContent, CardFooter } from './Card'
export { DrumPulse, DrumPulseScreen, DrumPulseInline } from './DrumPulse'
export type { DrumSpeed }               from './DrumPulse'
export { HeatBar }                       from './HeatBar'
export { Input }                         from './Input'
export { NkisiShield }                   from './NkisiShield'
export { Skeleton, SkeletonCard, SkeletonPost, SkeletonProfile, SkeletonVillage } from './Skeleton'
export { OfflineBanner, useNetworkStatus } from './OfflineBanner'
export { SkinSwitcher }                  from './SkinSwitcher'
export { PinGate }                       from './PinGate'
export { ViewdiconLogo, ViewdiconMini, ViewdiconIcon } from './ViewdiconLogo'

// Design system additions
export { RealmGate }                     from './RealmGate'
export { RealmNav }                      from './RealmNav'
export { SectionHeader }                from './SectionHeader'
export { Stat }                          from './Stat'
export { Stars }                         from './Stars'
export { REALM }                         from './tokens'
export type { RealmKey }                from './tokens'
export { default as UnderConstruction } from './UnderConstruction'
