import type { RoleDefinition } from '../role-registry'

export const AGRICULTURE_ROLES: RoleDefinition[] = [
  { key: 'crop_farmer', name: 'Crop Farmer', desc: 'Grows and sells food and cash crops, tracking inventory, market prices, and cold-chain logistics to buyers.', tools: ["price_checker","forecast_share","community_board","alert_system","inventory_tracker","quick_invoice","cold_chain_tracker","delivery_tracker"], moneyFlow: 'Harvest sales → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'goods' },
  { key: 'livestock', name: 'Pastoralist / Livestock Farmer', desc: 'Raises and trades livestock, managing herd health, routes to market, and animal welfare alerts.', tools: ["alert_system","delivery_tracker","quick_invoice","route_planner","community_board","price_checker","inventory_tracker","health_log"], moneyFlow: 'Livestock sales → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'goods' },
  { key: 'fisher', name: 'Artisanal Fisher', desc: 'Catches and sells fish through local and regional markets, managing cold-chain preservation and delivery routes.', tools: ["cold_chain_tracker","route_planner","forecast_share","inventory_tracker","price_checker","quick_invoice","delivery_tracker","community_board"], moneyFlow: 'Catch sales → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'goods' },
  { key: 'agro_processor', name: 'Agro-Processor', desc: 'Transforms raw agricultural products into processed goods, managing quality, compliance, and distribution.', tools: ["quality_log","bulk_order_manager","inventory_tracker","compliance_checker","delivery_tracker","price_checker","analytics_report","staff_manager"], moneyFlow: 'Processed goods sales → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'goods' },
  { key: 'irrigation', name: 'Irrigation Engineer', desc: 'Designs, installs, and maintains irrigation systems to improve agricultural water management and crop yields.', tools: ["site_survey","maintenance_log","territory_map","technical_docs","safety_checklist","project_tracker","grant_tracker","community_connect"], moneyFlow: 'Project fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'seed_guardian', name: 'Seed Bank Guardian', desc: 'Conserves and distributes indigenous seed varieties, documenting biodiversity and supporting community food sovereignty.', tools: ["conservation_log","document_vault","grant_tracker","publication_vault","inventory_tracker","community_board","alert_system","analytics_report"], moneyFlow: 'Grants and seed sales → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'rain_watcher', name: 'Rain Watcher', desc: 'Monitors weather and rainfall patterns to generate forecasts and early warnings for farming communities.', tools: ["forecast_share","alert_system","analytics_report","community_board","daily_target_tracker","territory_map","community_connect","report_generator"], moneyFlow: 'Advisory fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'farm_logistics', name: 'Farm-to-Market Coordinator', desc: 'Coordinates the movement of agricultural produce from farms to markets, managing cold chain, routing, and bulk orders.', tools: ["runner_dispatch","cold_chain_tracker","daily_settlement","route_planner","delivery_tracker","price_checker","bulk_order_manager","analytics_report"], moneyFlow: 'Logistics fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'delivery' },
]
