import type { RoleDefinition } from '../role-registry'

export const ARTS_ROLES: RoleDefinition[] = [
  {
    key: 'musician',
    name: 'Musician / Griot',
    desc: 'Performs original music across genres from highlife to afrobeats, records and distributes through digital platforms, and preserves oral traditions as a modern Griot.',
    tools: ['portfolio_vault', 'content_calendar', 'payment_link', 'analytics_report', 'social_shop', 'review_tracker', 'recording_vault', 'community_board'],
    moneyFlow: 'Performance fees and streaming royalties → Cowrie wallet.',
    crestPath: 'Release 3 albums. Reach 10,000 streams. Earn 100 reviews.',
    businessSessionType: 'creative',
  },
  {
    key: 'visual_artist',
    name: 'Visual Artist',
    desc: 'Creates original paintings, sculptures, and mixed-media works rooted in African visual traditions, sells through digital storefronts, and builds a gallery portfolio.',
    tools: ['portfolio_vault', 'social_shop', 'design_brief', 'client_tracker', 'content_calendar', 'review_tracker', 'payment_link', 'analytics_report'],
    moneyFlow: 'Artwork sales and commissions → Cowrie wallet.',
    crestPath: 'Sell 50 artworks. Complete 20 commissions. Maintain 4.5+ rating.',
    businessSessionType: 'creative',
  },
  {
    key: 'author',
    name: 'Author / Poet',
    desc: 'Writes novels, poetry collections, and literary works that explore African identity and experience, publishes digitally and in print, and engages reading communities.',
    tools: ['article_vault', 'publication_vault', 'content_calendar', 'community_board', 'review_tracker', 'payment_link', 'analytics_report', 'grant_tracker'],
    moneyFlow: 'Book sales and royalties → Cowrie wallet.',
    crestPath: 'Publish 3 books. Earn 500 reader reviews. Secure 2 literary grants.',
    businessSessionType: 'creative',
  },
  {
    key: 'filmmaker',
    name: 'Filmmaker',
    desc: 'Directs and produces short films, documentaries, and features that tell authentic African stories, managing production budgets and building an industry client network.',
    tools: ['project_tracker', 'portfolio_vault', 'billing_dashboard', 'equipment_log', 'client_tracker', 'content_calendar', 'analytics_report', 'community_board'],
    moneyFlow: 'Production contracts and distribution revenue → Cowrie wallet.',
    crestPath: 'Complete 5 films. Screen at 3 festivals. Build 20-client portfolio.',
    businessSessionType: 'creative',
  },
  {
    key: 'performer',
    name: 'Dancer / Performer',
    desc: 'Performs and choreographs contemporary and traditional dance, books live shows and workshops, and grows an audience through social media and community engagement.',
    tools: ['appointment_book', 'payment_link', 'review_tracker', 'content_calendar', 'portfolio_vault', 'community_board', 'social_shop', 'analytics_report'],
    moneyFlow: 'Show fees and workshop bookings → Cowrie wallet.',
    crestPath: 'Perform 100 shows. Teach 500 students. Earn 4.8+ rating.',
    businessSessionType: 'creative',
  },
  {
    key: 'master_artisan',
    name: 'Master Artisan',
    desc: 'Crafts and sells high-quality traditional and contemporary African artworks including beadwork, weaving, and carving through online storefronts and direct delivery.',
    tools: ['inventory_tracker', 'social_shop', 'delivery_tracker', 'portfolio_vault', 'client_tracker', 'quick_invoice', 'review_tracker', 'product_listing'],
    moneyFlow: 'Craft sales and wholesale orders → Cowrie wallet.',
    crestPath: 'Sell 200 pieces. Ship to 10 countries. Maintain 4.7+ rating.',
    businessSessionType: 'goods',
  },
  {
    key: 'fashion_designer_arts',
    name: 'Fashion Designer',
    desc: 'Designs wearable art collections inspired by African heritage, manages client commissions, and sells through social commerce and curated product listings.',
    tools: ['design_brief', 'product_listing', 'client_tracker', 'portfolio_vault', 'social_shop', 'review_tracker', 'payment_link', 'content_calendar'],
    moneyFlow: 'Custom orders and collection sales → Cowrie wallet.',
    crestPath: 'Launch 5 collections. Complete 100 commissions. Build 500-follower shop.',
    businessSessionType: 'creative',
  },
  {
    key: 'cultural_educator',
    name: 'Cultural Educator',
    desc: 'Teaches African cultural arts, history, and heritage to communities and institutions, runs outreach programmes, and publishes educational cultural content.',
    tools: ['community_board', 'grant_tracker', 'impact_tracker', 'content_calendar', 'attendance_tracker', 'outreach_planner', 'report_generator', 'publication_vault'],
    moneyFlow: 'Programme fees and grants → Cowrie wallet.',
    crestPath: 'Reach 1,000 learners. Secure 3 grants. Publish 5 cultural guides.',
    businessSessionType: 'community',
  },
]
