import type { RoleDefinition } from '../role-registry'

export const BUILDERS_ROLES: RoleDefinition[] = [
  {
    key: 'architect',
    name: 'Architect',
    desc: 'Designs buildings that balance aesthetics, function, and structural safety, managing client briefs, technical documentation, compliance approvals, and project delivery.',
    tools: ['site_survey', 'project_tracker', 'technical_docs', 'blueprint_vault', 'compliance_checker', 'client_tracker', 'billing_dashboard', 'portfolio_vault'],
    moneyFlow: 'Design fees and project contracts → Cowrie wallet.',
    crestPath: 'Complete 20 projects. Achieve full compliance record. Build 5-star portfolio.',
    businessSessionType: 'professional',
  },
  {
    key: 'civil_engineer',
    name: 'Civil Engineer',
    desc: 'Plans and oversees construction of roads, bridges, drainage, and infrastructure, ensuring quality standards, safety compliance, and accurate project reporting.',
    tools: ['safety_checklist', 'quality_log', 'maintenance_log', 'technical_docs', 'site_survey', 'project_tracker', 'compliance_checker', 'analytics_report'],
    moneyFlow: 'Engineering contracts and consulting fees → Cowrie wallet.',
    crestPath: 'Complete 10 infrastructure projects. Zero safety incidents for 24 months.',
    businessSessionType: 'professional',
  },
  {
    key: 'mason',
    name: 'Mason',
    desc: 'Lays bricks, blocks, and stone to build walls, foundations, and structural elements, tracking daily output, inventory, and quality on every work order.',
    tools: ['work_order', 'daily_target_tracker', 'safety_checklist', 'inventory_tracker', 'quick_invoice', 'attendance_tracker', 'quality_log', 'maintenance_log'],
    moneyFlow: 'Per-job and daily labour fees → Cowrie wallet.',
    crestPath: 'Complete 500 work orders. Maintain zero structural defect reports.',
    businessSessionType: 'goods',
  },
  {
    key: 'electrician',
    name: 'Electrician',
    desc: 'Installs and repairs electrical wiring, panels, and systems for residential and commercial clients, managing repair queues, parts sourcing, and compliance certificates.',
    tools: ['repair_queue', 'parts_finder', 'maintenance_log', 'safety_checklist', 'work_order', 'client_tracker', 'quick_invoice', 'compliance_checker'],
    moneyFlow: 'Service and installation fees → Cowrie wallet.',
    crestPath: 'Complete 300 jobs. Maintain zero electrical fault callbacks. Get certified.',
    businessSessionType: 'service',
  },
  {
    key: 'plumber',
    name: 'Plumber',
    desc: 'Installs and repairs water supply, drainage, and sanitation systems, managing work orders, parts sourcing, client relationships, and safety on every project.',
    tools: ['repair_queue', 'work_order', 'client_tracker', 'parts_finder', 'maintenance_log', 'safety_checklist', 'quick_invoice', 'review_tracker'],
    moneyFlow: 'Plumbing service fees → Cowrie wallet.',
    crestPath: 'Complete 200 jobs. Earn 4.5+ rating. Zero leak-back complaints.',
    businessSessionType: 'service',
  },
  {
    key: 'carpenter',
    name: 'Carpenter / Welder',
    desc: 'Constructs and installs wooden frameworks, furniture, and metal fabrications, managing custom client orders, inventory, and delivery of finished pieces.',
    tools: ['work_order', 'portfolio_vault', 'inventory_tracker', 'client_tracker', 'quick_invoice', 'review_tracker', 'parts_finder', 'daily_target_tracker'],
    moneyFlow: 'Custom fabrication and installation fees → Cowrie wallet.',
    crestPath: 'Complete 100 custom builds. Ship 50 products. Maintain 4.6+ rating.',
    businessSessionType: 'goods',
  },
  {
    key: 'surveyor',
    name: 'Surveyor',
    desc: 'Measures and maps land boundaries, topography, and site conditions, producing technical reports and blueprints that underpin legal, engineering, and development decisions.',
    tools: ['site_survey', 'territory_map', 'technical_docs', 'blueprint_vault', 'compliance_checker', 'project_tracker', 'analytics_report', 'report_generator'],
    moneyFlow: 'Survey and mapping fees → Cowrie wallet.',
    crestPath: 'Survey 200 plots. Deliver 50 technical reports. Zero boundary disputes.',
    businessSessionType: 'professional',
  },
  {
    key: 'heavy_machinery',
    name: 'Heavy Machinery Operator',
    desc: 'Operates excavators, bulldozers, and cranes on construction sites, maintaining equipment logs, fuel records, safety checklists, and daily work schedules.',
    tools: ['maintenance_log', 'fuel_tracker', 'safety_checklist', 'work_order', 'parts_finder', 'repair_queue', 'daily_target_tracker', 'compliance_checker'],
    moneyFlow: 'Daily hire fees and project contracts → Cowrie wallet.',
    crestPath: 'Log 2,000 operating hours. Zero incident record. Pass annual certification.',
    businessSessionType: 'service',
  },
]
