import type { RoleDefinition } from '../role-registry'

export const COMMERCE_ROLES: RoleDefinition[] = [
  { key: 'market_vendor', name: 'Market Vendor', desc: 'Sells goods directly to customers at local markets and trading posts, managing daily inventory and payments.', tools: ["quick_invoice","price_checker","pos_dashboard","stock_tracker","runner_dispatch","bulk_order_manager","review_tracker","community_board"], moneyFlow: 'Daily sales → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'goods' },
  { key: 'import_export', name: 'Import/Export Agent', desc: 'Facilitates cross-border trade by managing documentation, compliance, and logistics for imported and exported goods.', tools: ["forex_rate_display","delivery_tracker","compliance_checker","document_vault","quick_invoice","booking_calendar","analytics_report","route_planner"], moneyFlow: 'Trade margins → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'mobile_money', name: 'Mobile Money Agent', desc: 'Provides cash-in and cash-out mobile money services to customers in underserved communities.', tools: ["mobile_payment_collect","daily_settlement","cash_tracker","transaction_log","fraud_alert","queue_manager","client_tracker","pos_dashboard"], moneyFlow: 'Commission per transaction → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'wholesale', name: 'Wholesaler', desc: 'Sources goods in bulk from suppliers and distributes them at wholesale prices to retailers and businesses.', tools: ["bulk_order_manager","stock_tracker","supplier_connect","invoice_batch","delivery_tracker","price_checker","escrow_monitor","quality_log"], moneyFlow: 'Bulk sales → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'goods' },
  { key: 'ecommerce', name: 'E-Commerce Seller', desc: 'Runs an online storefront across social and digital platforms, managing product listings, orders, and customer reviews.', tools: ["social_shop","product_listing","review_tracker","payment_link","content_calendar","portfolio_vault","analytics_report","delivery_tracker"], moneyFlow: 'Online sales → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'forex', name: 'Forex Trader', desc: 'Trades foreign currencies and manages currency exchange risk for individuals and businesses across African markets.', tools: ["cowrie_exchange","risk_calculator","settlement_tracker","compliance_checker","daily_pnl","analytics_report","transaction_log","alert_system"], moneyFlow: 'Spread and margin → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'second_hand', name: 'Second-Hand Dealer', desc: 'Buys, values, and resells pre-owned goods including electronics, clothing, and household items.', tools: ["barter_match","value_calculator","price_checker","social_shop","inventory_tracker","product_listing","review_tracker","quick_invoice"], moneyFlow: 'Resale margin → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'goods' },
  { key: 'auctioneer', name: 'Auctioneer', desc: 'Hosts live auctions for goods, manages bidding, escrow, and delivery coordination for buyers and sellers.', tools: ["live_auction","bid_tracker","escrow_release","timer_board","community_board","quick_invoice","analytics_report","delivery_tracker"], moneyFlow: 'Auction commission → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
]
