import type { RoleDefinition } from '../role-registry'

export const EDUCATION_ROLES: RoleDefinition[] = [
  {
    key: 'classroom_teacher',
    name: 'Classroom Teacher',
    desc: 'Delivers structured lessons to primary and secondary students, tracks attendance, assigns projects, and reports learner progress to parents and administrators.',
    tools: ['attendance_tracker', 'content_calendar', 'report_generator', 'project_tracker', 'community_board', 'client_tracker', 'daily_target_tracker', 'alert_system'],
    moneyFlow: 'Service sessions → Cowrie wallet.',
    crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.',
    businessSessionType: 'service',
  },
  {
    key: 'lecturer',
    name: 'University Lecturer',
    desc: 'Teaches tertiary-level courses, supervises research, publishes academic work, and mentors students through scholarly and professional development.',
    tools: ['publication_vault', 'grant_tracker', 'project_tracker', 'report_generator', 'client_tracker', 'appointment_book', 'analytics_report', 'content_calendar'],
    moneyFlow: 'Consultancy and course fees → Cowrie wallet.',
    crestPath: 'Publish 10 papers. Secure 3 grants.',
    businessSessionType: 'professional',
  },
  {
    key: 'tutor',
    name: 'Community Tutor',
    desc: 'Provides one-on-one and small-group tutoring sessions, tracks learner progress through session logs, and builds an accessible community learning portfolio.',
    tools: ['appointment_book', 'billing_dashboard', 'review_tracker', 'session_log', 'daily_target_tracker', 'content_calendar', 'community_connect', 'portfolio_vault'],
    moneyFlow: 'Tutoring sessions → Cowrie wallet.',
    crestPath: 'Complete 200 sessions. Earn 50 five-star reviews.',
    businessSessionType: 'service',
  },
  {
    key: 'school_admin',
    name: 'School Administrator',
    desc: 'Manages school operations including staff scheduling, budget oversight, community communications, and compliance with educational standards.',
    tools: ['staff_manager', 'daily_settlement', 'community_board', 'attendance_tracker', 'budget_tracker', 'report_generator', 'alert_system', 'document_vault'],
    moneyFlow: 'Administrative fees and school income → Cowrie wallet.',
    crestPath: 'Manage 5+ staff. Maintain full compliance for 12 months.',
    businessSessionType: 'service',
  },
  {
    key: 'vocational_trainer',
    name: 'Vocational Trainer',
    desc: 'Delivers hands-on skills training in trades and crafts, tracks learner attendance and daily targets, and builds a community portfolio of certified graduates.',
    tools: ['project_tracker', 'quick_invoice', 'daily_target_tracker', 'attendance_tracker', 'equipment_log', 'portfolio_vault', 'community_connect', 'review_tracker'],
    moneyFlow: 'Training fees → Cowrie wallet.',
    crestPath: 'Train 50 learners. Achieve 90% course completion rate.',
    businessSessionType: 'service',
  },
  {
    key: 'language_keeper',
    name: 'Language Keeper',
    desc: 'Preserves and teaches indigenous African languages through documentation, community classes, recorded oral traditions, and published learning materials.',
    tools: ['document_vault', 'publication_vault', 'content_calendar', 'community_board', 'recording_vault', 'grant_tracker', 'translation_log', 'analytics_report'],
    moneyFlow: 'Grants and community contributions → Cowrie wallet.',
    crestPath: 'Document 3 languages. Reach 1,000 community learners.',
    businessSessionType: 'community',
  },
  {
    key: 'edtech_developer',
    name: 'EdTech Developer',
    desc: 'Builds and maintains educational technology platforms, APIs, and digital tools that support learning across African schools and communities.',
    tools: ['analytics_report', 'ticket_system', 'code_project', 'api_tester', 'client_tracker', 'content_calendar', 'project_tracker', 'community_board'],
    moneyFlow: 'Platform licenses and development contracts → Cowrie wallet.',
    crestPath: 'Deploy 3 live EdTech products. Serve 500+ active users.',
    businessSessionType: 'professional',
  },
  {
    key: 'cultural_historian',
    name: 'Cultural Historian',
    desc: 'Researches, archives, and publishes African cultural and historical knowledge, connecting communities to their heritage through reports and public outreach.',
    tools: ['publication_vault', 'grant_tracker', 'report_generator', 'archive_log', 'document_vault', 'community_board', 'content_calendar', 'analytics_report'],
    moneyFlow: 'Research grants and publication royalties → Cowrie wallet.',
    crestPath: 'Publish 5 research works. Archive 100 cultural records.',
    businessSessionType: 'professional',
  },
]
