import type { RoleDefinition } from '../role-registry'

export const ENERGY_ROLES: RoleDefinition[] = [
  {
    key: 'solar_installer',
    name: 'Solar Installer',
    desc: 'Installs rooftop and ground-mount solar PV systems for homes and businesses, conducting site surveys, sourcing parts, and delivering compliant commissioned installations.',
    tools: ['work_order', 'site_survey', 'parts_finder', 'safety_checklist', 'client_tracker', 'quick_invoice', 'maintenance_log', 'review_tracker'],
    moneyFlow: 'Installation fees and maintenance contracts → Cowrie wallet.',
    crestPath: 'Install 200 solar systems. Maintain zero faulty installation reports.',
    businessSessionType: 'service',
  },
  {
    key: 'electrical_engineer',
    name: 'Electrical Engineer',
    desc: 'Designs and oversees power distribution systems, substations, and grid infrastructure, ensuring safety compliance, quality assurance, and accurate technical documentation.',
    tools: ['infrastructure_log', 'safety_checklist', 'technical_docs', 'compliance_checker', 'project_tracker', 'quality_log', 'analytics_report', 'maintenance_log'],
    moneyFlow: 'Engineering contracts and consulting fees → Cowrie wallet.',
    crestPath: 'Complete 15 engineering projects. Zero safety incidents for 24 months.',
    businessSessionType: 'professional',
  },
  {
    key: 'petroleum_engineer',
    name: 'Petroleum Engineer',
    desc: 'Plans and oversees oil and gas extraction and processing operations, managing safety protocols, regulatory compliance, fuel tracking, and technical documentation.',
    tools: ['safety_checklist', 'compliance_checker', 'fuel_tracker', 'technical_docs', 'project_tracker', 'analytics_report', 'audit_log', 'document_vault'],
    moneyFlow: 'Engineering contracts and advisory fees → Cowrie wallet.',
    crestPath: 'Complete 10 field projects. Pass all regulatory audits. Zero HSE incidents.',
    businessSessionType: 'professional',
  },
  {
    key: 'renewable_consultant',
    name: 'Renewable Energy Consultant',
    desc: 'Advises governments, businesses, and communities on renewable energy strategy, feasibility, and grant funding, publishing research and connecting clients to solutions.',
    tools: ['project_tracker', 'grant_tracker', 'analytics_report', 'technical_docs', 'client_tracker', 'community_connect', 'report_generator', 'publication_vault'],
    moneyFlow: 'Consulting fees and grant advisory → Cowrie wallet.',
    crestPath: 'Complete 50 engagements. Secure 10 grants for clients. Publish 5 reports.',
    businessSessionType: 'professional',
  },
  {
    key: 'utility_worker',
    name: 'Utility Worker',
    desc: 'Operates and maintains electricity distribution infrastructure, responds to outages and faults along assigned routes, and alerts communities to planned interruptions.',
    tools: ['billing_dashboard', 'infrastructure_log', 'alert_system', 'maintenance_log', 'route_planner', 'daily_target_tracker', 'compliance_checker', 'community_alert'],
    moneyFlow: 'Salary and service fees → Cowrie wallet.',
    crestPath: 'Complete 1,000 maintenance tasks. Zero electrocution incidents. Stay certified.',
    businessSessionType: 'service',
  },
  {
    key: 'biomass_practitioner',
    name: 'Biomass Practitioner',
    desc: 'Develops and manages biomass energy projects converting organic waste into clean cooking fuel and power, connecting rural communities to sustainable energy solutions.',
    tools: ['quality_log', 'site_survey', 'community_connect', 'inventory_tracker', 'grant_tracker', 'project_tracker', 'technical_docs', 'analytics_report'],
    moneyFlow: 'Project fees and grant funding → Cowrie wallet.',
    crestPath: 'Deliver 20 biomass projects. Serve 500 households. Secure 5 grants.',
    businessSessionType: 'professional',
  },
  {
    key: 'nuclear_specialist',
    name: 'Nuclear Specialist',
    desc: 'Provides expert oversight on nuclear energy policy, safety protocols, and facility compliance, contributing to Africa\'s long-term clean energy research and development.',
    tools: ['safety_checklist', 'compliance_checker', 'technical_docs', 'document_vault', 'audit_log', 'publication_vault', 'project_tracker', 'analytics_report'],
    moneyFlow: 'Advisory fees and research grants → Cowrie wallet.',
    crestPath: 'Complete 10 safety audits. Publish 8 technical papers. Pass all certifications.',
    businessSessionType: 'professional',
  },
  {
    key: 'minigrid_operator',
    name: 'Mini-Grid Operator',
    desc: 'Runs solar or hybrid mini-grids serving rural and peri-urban communities, managing billing, maintenance, inventory, client accounts, and community energy access.',
    tools: ['billing_dashboard', 'community_connect', 'alert_system', 'maintenance_log', 'inventory_tracker', 'daily_settlement', 'analytics_report', 'client_tracker'],
    moneyFlow: 'Energy sales and connection fees → Cowrie wallet.',
    crestPath: 'Operate for 24 months. Serve 500 connections. Maintain 95% uptime.',
    businessSessionType: 'service',
  },
]
