import type { RoleDefinition } from '../role-registry'

export const FAMILY_ROLES: RoleDefinition[] = [
  // ── COUNSELLING & THERAPY ──────────────────────────────────
  { key: 'marriage_counsellor', name: 'Marriage Counsellor / Relationship Advisor', desc: 'Provides professional counselling for couples navigating marital challenges — from practices in Ikeja Lagos to Westlands Nairobi to Sandton Johannesburg', tools: ['appointment_book', 'service_session', 'client_tracker', 'session_notes', 'mobile_payment_collect'], moneyFlow: 'Per-session counselling fee via Cowrie service session. Package deals for 6 or 12 sessions with upfront Cowrie payment at discount. Couples retreat fees via escrow.', crestPath: 'Complete 300 counselling sessions. Maintain 85% client retention over 6 sessions. Get 50 five-star Kila reviews. Achieve professional certification.', businessSessionType: 'professional' },
  { key: 'family_therapist', name: 'Family Therapist / Family Systems Counsellor', desc: 'Works with entire family units on communication, conflict, and healing — from family clinics in Lekki Lagos to Karen Nairobi to Rosebank Johannesburg', tools: ['appointment_book', 'service_session', 'client_tracker', 'session_notes', 'mobile_payment_collect', 'referral_tracker'], moneyFlow: 'Family session fee via Cowrie — higher rate than individual. Multi-session packages with 20% upfront discount. Referral bonuses from partnering schools and churches.', crestPath: 'Complete 200 family therapy sessions. Work with 50 unique families. Maintain active license renewal. Get 30 referrals from institutions.', businessSessionType: 'professional' },
  // ── CHILDCARE ──────────────────────────────────────────────
  { key: 'childcare_provider', name: 'Childcare Provider / Nanny / Au Pair', desc: 'Provides daily childcare in home or at small centres — from live-in nannies in Ikoyi Lagos to day nannies in Lavington Nairobi to au pairs in Constantia Cape Town', tools: ['service_session', 'daily_log', 'mobile_payment_collect', 'schedule_manager', 'emergency_contact'], moneyFlow: 'Monthly salary via Cowrie auto-transfer. Overtime paid per-hour through service session. Live-in arrangements include deducted housing value.', crestPath: 'Complete 12 months continuous childcare. Get first-aid certification. Maintain zero incident reports. Get 20 parent endorsements.', businessSessionType: 'service' },
  { key: 'elder_care_provider', name: 'Elder Care Provider / Home Health Aide', desc: 'Provides daily care, companionship, and medical support for elderly family members — from home care in Abuja to elder care services in Kumasi Ghana to retirement homes in Durban', tools: ['service_session', 'daily_log', 'mobile_payment_collect', 'emergency_contact', 'medication_tracker'], moneyFlow: 'Monthly care fee via Cowrie auto-transfer from family pot. Daily rate for temporary care via service session. Medical supply purchases reimbursed through Cowrie receipt.', crestPath: 'Provide 2,000 hours of elder care. Maintain zero medication errors. Get geriatric care certification. Serve 15 families.', businessSessionType: 'service' },
  // ── EVENTS & CELEBRATIONS ──────────────────────────────────
  { key: 'family_event_planner', name: 'Family Event Planner / Celebration Coordinator', desc: 'Organises naming ceremonies, birthdays, anniversaries, and family reunions — from lavish owambe parties in Lagos to harusi celebrations in Mombasa Kenya', tools: ['event_planner', 'vendor_manager', 'invoice_generator', 'escrow_release', 'client_tracker', 'budget_tracker'], moneyFlow: 'Planning fee via Cowrie escrow — 30% on booking, 40% at vendor confirmation, 30% post-event. Vendor payments channelled through Cowrie escrow. Commission on vendor referrals.', crestPath: 'Plan 50 family events. Manage budgets totalling 5M Cowrie. Maintain zero vendor no-shows. Get 40 five-star Kila reviews.', businessSessionType: 'service' },
  { key: 'traditional_matchmaker', name: 'Traditional Matchmaker / Alarina / Marriage Broker', desc: 'Facilitates introductions between families for marriage — from Yoruba alarina tradition in Ibadan to Igbo ndi inyom matchmakers to Kikuyu ruracio negotiators in Central Kenya', tools: ['client_tracker', 'service_session', 'appointment_book', 'mobile_payment_collect', 'referral_tracker'], moneyFlow: 'Introduction fee via Cowrie on first meeting arrangement. Success fee on engagement — held in escrow until both families confirm. Consultation fees per session.', crestPath: 'Facilitate 30 successful introductions. Achieve 20 confirmed engagements. Maintain confidentiality record. Get 50 family endorsements.', businessSessionType: 'community' },
  // ── DOMESTIC & HOME ────────────────────────────────────────
  { key: 'adoption_counsellor', name: 'Adoption Counsellor / Child Welfare Advisor', desc: 'Guides families through adoption processes and post-adoption support — working with agencies in Abuja, Nairobi Child Welfare Society, and Cape Town adoption services', tools: ['service_session', 'client_tracker', 'session_notes', 'document_vault', 'appointment_book', 'referral_tracker'], moneyFlow: 'Consultation fee via Cowrie per session. Full adoption support package via escrow with milestone releases. Post-adoption follow-up sessions billed monthly.', crestPath: 'Support 20 families through adoption. Complete 100 counselling sessions. Maintain social worker certification. Get 15 successful placement endorsements.', businessSessionType: 'professional' },
  { key: 'domestic_worker', name: 'Domestic Worker / Housekeeper / House Manager', desc: 'Manages households — cooking, cleaning, laundry, and home organisation — from live-in helpers in Victoria Island Lagos to domestic workers in Runda Nairobi', tools: ['service_session', 'daily_log', 'mobile_payment_collect', 'schedule_manager', 'task_checklist'], moneyFlow: 'Monthly salary via Cowrie auto-transfer from employer. Overtime billed per-hour through service session. Bonus payments via Kila tips.', crestPath: 'Complete 24 months continuous service. Get household management certification. Maintain zero breakage incidents for 6 months. Get 10 employer endorsements.', businessSessionType: 'service' },
  { key: 'home_cook', name: 'Home Cook / Private Chef / Meal Prep Specialist', desc: 'Prepares home-cooked meals for families, meal prep services, and special dietary catering — from private kitchens in Banana Island Lagos to meal prep in Karen Nairobi', tools: ['daily_menu_board', 'service_session', 'mobile_payment_collect', 'food_order_chat', 'customer_list'], moneyFlow: 'Weekly meal plan subscription via Cowrie auto-debit. One-off catering via service session. Ingredient purchases reimbursed through Cowrie receipt. Tips via Kila.', crestPath: 'Serve 100 weekly meal plans. Build subscriber list of 30 families. Maintain food safety certification. Get 60 five-star food reviews.', businessSessionType: 'service' },
  // ── FINANCIAL & LEGAL ──────────────────────────────────────
  { key: 'family_financial_planner', name: 'Family Financial Planner / Household Budget Advisor', desc: 'Helps families plan budgets, savings, investments, and insurance — from financial advisory firms in Ikoyi Lagos to wealth managers in Upperhill Nairobi', tools: ['service_session', 'client_tracker', 'budget_tracker', 'appointment_book', 'invoice_generator', 'document_vault'], moneyFlow: 'Consultation fee via Cowrie per session. Monthly retainer for ongoing advisory via auto-debit. Commission on referred financial products tracked transparently.', crestPath: 'Advise 50 families. Manage combined budgets of 10M Cowrie. Achieve CFP certification. Maintain 90% client retention over 12 months.', businessSessionType: 'professional' },
  // ── MATERNAL & CHILD ───────────────────────────────────────
  { key: 'doula', name: 'Doula / Birth Companion / Traditional Birth Attendant', desc: 'Provides emotional and physical support during pregnancy, birth, and postpartum — from birth centres in Surulere Lagos to maternity homes in Kisumu Kenya to midwife clinics in Accra', tools: ['appointment_book', 'service_session', 'client_tracker', 'emergency_contact', 'session_notes'], moneyFlow: 'Birth package via Cowrie escrow — prenatal visits, birth attendance, postnatal follow-up. Individual session fees for consultations. Postnatal meal prep as add-on service.', crestPath: 'Attend 50 births. Complete 200 prenatal sessions. Get doula certification from recognized body. Maintain zero adverse incident reports.', businessSessionType: 'service' },
  { key: 'breastfeeding_consultant', name: 'Breastfeeding Consultant / Lactation Specialist', desc: 'Supports new mothers with breastfeeding techniques, latch issues, and milk supply — from Lagos University Teaching Hospital to Kenyatta National Hospital Nairobi', tools: ['appointment_book', 'service_session', 'client_tracker', 'session_notes', 'mobile_payment_collect'], moneyFlow: 'Per-consultation fee via Cowrie. Home visit premium rate. Hospital partnership referral fees. Group class fees collected upfront.', crestPath: 'Complete 200 lactation consultations. Achieve IBCLC certification. Support 100 mothers to 6-month exclusive breastfeeding. Host 20 group classes.', businessSessionType: 'professional' },
  { key: 'parenting_coach', name: 'Parenting Coach / Family Life Educator', desc: 'Guides parents on child development, discipline, and family dynamics — from parenting workshops in Lekki Lagos to family centres in Lavington Nairobi to community halls in Soweto', tools: ['service_session', 'workshop_scheduler', 'client_tracker', 'content_planner', 'mobile_payment_collect', 'student_tracker'], moneyFlow: 'Coaching session fee via Cowrie. Workshop fees collected upfront. Online course subscriptions via monthly auto-debit. Corporate parenting program contracts via escrow.', crestPath: 'Coach 100 parents. Host 30 workshops with 20+ attendees each. Publish 50 parenting content pieces. Get 60 five-star reviews.', businessSessionType: 'service' },
  { key: 'child_psychologist', name: 'Child Psychologist / Paediatric Therapist', desc: 'Provides psychological assessment and therapy for children — from clinics in Victoria Island Lagos to Nairobi Hospital child unit to Red Cross Children Hospital Cape Town', tools: ['appointment_book', 'service_session', 'session_notes', 'client_tracker', 'referral_tracker', 'document_vault'], moneyFlow: 'Per-session therapy fee via Cowrie. Assessment packages via escrow with report delivery milestone. School consultation contracts billed monthly.', crestPath: 'Complete 500 child therapy sessions. Conduct 50 psychological assessments. Maintain clinical psychology license. Get 20 school partnership contracts.', businessSessionType: 'professional' },
  // ── MEDIATION & LEGAL ──────────────────────────────────────
  { key: 'family_mediator', name: 'Family Mediator / Dispute Resolver', desc: 'Mediates family disputes — inheritance, custody, property — from community mediation centres in Ikeja Lagos to family courts in Milimani Nairobi', tools: ['service_session', 'session_notes', 'client_tracker', 'document_vault', 'appointment_book', 'escrow_release'], moneyFlow: 'Mediation session fee via Cowrie — split between parties. Multi-session packages with upfront deposit. Successful resolution bonus held in escrow.', crestPath: 'Mediate 100 family disputes. Achieve 80% resolution rate. Complete mediation certification. Handle 20 inheritance cases.', businessSessionType: 'professional' },
  { key: 'estate_planner', name: 'Estate Planner / Will Drafter / Succession Advisor', desc: 'Helps families plan estates, draft wills, and manage succession — critical in African extended family contexts from law offices in Ikoyi Lagos to Upperhill Nairobi', tools: ['service_session', 'document_vault', 'client_tracker', 'invoice_generator', 'appointment_book', 'escrow_release'], moneyFlow: 'Will drafting fee via Cowrie. Estate planning retainer via monthly auto-debit. Probate administration fees as percentage of estate via escrow milestone releases.', crestPath: 'Draft 100 wills. Complete 30 estate plans. Handle 20 probate cases. Maintain legal practice certification. Get 50 client endorsements.', businessSessionType: 'professional' },
  // ── END-OF-LIFE & GRIEF ────────────────────────────────────
  { key: 'funeral_planner', name: 'Funeral Planner / Burial Coordinator', desc: 'Organises funerals, burials, and memorial services respecting cultural traditions — from elaborate Ghanaian fantasy coffin funerals in Accra to Igbo burial rites in Owerri to Zulu ceremonies in KwaZulu-Natal', tools: ['event_planner', 'vendor_manager', 'escrow_release', 'invoice_generator', 'client_tracker', 'budget_tracker'], moneyFlow: 'Planning fee via Cowrie escrow — released at service completion. Vendor payments channelled through escrow. Family contribution collection via Cowrie pot.', crestPath: 'Coordinate 50 funeral services. Manage vendor network of 30 providers. Handle budgets totalling 3M Cowrie. Maintain zero-complaint record.', businessSessionType: 'service' },
  { key: 'grief_counsellor', name: 'Grief Counsellor / Bereavement Support', desc: 'Provides emotional support and counselling after loss — from hospital chaplaincy programs in Korle Bu Accra to community grief groups in Kigali Rwanda to hospice services in Johannesburg', tools: ['appointment_book', 'service_session', 'session_notes', 'client_tracker', 'referral_tracker'], moneyFlow: 'Per-session counselling fee via Cowrie. Support group facilitation fees collected from participants. Institutional contracts with hospitals and churches via monthly invoice.', crestPath: 'Complete 200 grief counselling sessions. Facilitate 30 support groups. Get bereavement counselling certification. Support 100 families through loss.', businessSessionType: 'professional' },
  // ── EDUCATION & TUTORING ───────────────────────────────────
  { key: 'home_tutor', name: 'Home Tutor / Private Lesson Teacher', desc: 'Provides one-on-one academic tutoring at home — from WAEC and JAMB prep tutors in Surulere Lagos to KCSE tutors in Eastlands Nairobi to matric tutors in Soweto', tools: ['appointment_book', 'service_session', 'student_tracker', 'mobile_payment_collect', 'schedule_manager'], moneyFlow: 'Per-session tutoring fee via Cowrie. Monthly packages with upfront payment at 10% discount. Exam season premium rates. Group tutoring splits fee among students.', crestPath: 'Tutor 50 students. Achieve 80% pass rate improvement. Complete 500 sessions. Get 30 parent endorsements.', businessSessionType: 'service' },
  { key: 'homework_centre', name: 'Homework Centre / After-School Program Operator', desc: 'Runs after-school study centres where children do homework with supervision — from lesson centres in Ikotun Lagos to homework hubs in Kibera Nairobi to study rooms in Tembisa Johannesburg', tools: ['student_tracker', 'service_session', 'mobile_payment_collect', 'schedule_manager', 'daily_log', 'ajo_circle'], moneyFlow: 'Monthly subscription per child via Cowrie auto-debit. Sibling discounts applied automatically. Exam prep intensive packages sold seasonally. Ajo circle for centre expansion savings.', crestPath: 'Enrol 50 children. Maintain 90% daily attendance. Operate for 12 consecutive months. Achieve measurable grade improvement in 70% of students.', businessSessionType: 'service' },
  // ── CARE FACILITIES ────────────────────────────────────────
  { key: 'daycare_owner', name: 'Daycare Owner / Creche Operator', desc: 'Operates a licensed daycare facility for infants and toddlers — from creches in Lekki Phase 1 Lagos to daycares in Kilimani Nairobi to Montessori centres in East Legon Accra', tools: ['student_tracker', 'daily_log', 'mobile_payment_collect', 'emergency_contact', 'schedule_manager', 'invoice_generator'], moneyFlow: 'Monthly tuition via Cowrie auto-debit per child. Registration fees upfront. Feeding fees separate line item. Late pickup penalty charges auto-applied.', crestPath: 'Care for 30 children simultaneously. Operate for 24 months incident-free. Get state licensing certification. Maintain 3:1 child-to-staff ratio.', businessSessionType: 'service' },
  { key: 'senior_home_operator', name: 'Senior Home Operator / Retirement Residence Manager', desc: 'Manages residential care for elderly Africans — from Wheatbaker Senior Living Lagos to Fairmile Retirement Nairobi to Oude Molen Eco Village Cape Town', tools: ['daily_log', 'medication_tracker', 'invoice_generator', 'emergency_contact', 'schedule_manager', 'client_tracker'], moneyFlow: 'Monthly residence fee via Cowrie auto-transfer from family pot. Medical care add-ons billed separately. Activity program fees included. Emergency fund held in escrow.', crestPath: 'House 20 residents. Maintain zero abuse incidents. Get government care certification. Operate for 36 continuous months.', businessSessionType: 'service' },
  // ── PHOTOGRAPHY & MEMORY ───────────────────────────────────
  { key: 'family_photographer', name: 'Family Photographer / Portrait Specialist', desc: 'Captures family portraits, baby shoots, and milestone photos — from TY Bello-inspired studios in Victoria Island Lagos to family photography in Westlands Nairobi', tools: ['appointment_book', 'service_session', 'design_portfolio', 'mobile_payment_collect', 'client_tracker'], moneyFlow: 'Session fee via Cowrie with 50% booking deposit. Print and album packages as add-ons. Yearly family portrait subscriptions via auto-debit. Rush editing premium.', crestPath: 'Shoot 200 family sessions. Build portfolio of 500 images. Maintain 48hr delivery turnaround. Get 80 five-star Kila reviews.', businessSessionType: 'creative' },
  // ── WEDDING & CEREMONY ─────────────────────────────────────
  { key: 'wedding_planner', name: 'Wedding Planner / Owambe Coordinator', desc: 'Plans and executes weddings from traditional ceremonies to white weddings — from destination weddings in Zanzibar to grand receptions at Eko Hotel Lagos to garden weddings in Karen Nairobi', tools: ['event_planner', 'vendor_manager', 'escrow_release', 'budget_tracker', 'client_tracker', 'invoice_generator'], moneyFlow: 'Planning fee 10-15% of wedding budget via Cowrie escrow — milestone releases at vendor booking, rehearsal, and post-wedding. Vendor payments all channelled through Cowrie.', crestPath: 'Plan 30 weddings. Manage combined budgets of 20M Cowrie. Build vendor network of 50 providers. Achieve zero day-of-event failures.', businessSessionType: 'service' },
  { key: 'ceremony_coordinator', name: 'Ceremony Coordinator / Traditional Rites Officiant', desc: 'Coordinates traditional ceremonies — Igba Nkwu, Yoruba engagement, Kikuyu ruracio, Zulu umembeso — from community halls in Enugu to cultural centres in Nairobi', tools: ['event_planner', 'service_session', 'client_tracker', 'vendor_manager', 'mobile_payment_collect'], moneyFlow: 'Coordination fee via Cowrie service session. Cultural item procurement fees via escrow. Family contribution collection through Cowrie pot. Officiating fee paid on ceremony day.', crestPath: 'Coordinate 40 traditional ceremonies. Master 5 different cultural rite formats. Get 50 family endorsements. Maintain zero cultural protocol violations.', businessSessionType: 'community' },
  { key: 'naming_officiant', name: 'Naming Ceremony Officiant / Christening Coordinator', desc: 'Officiates baby naming ceremonies across cultural traditions — from Yoruba naming on the 8th day in Ibadan to Akan outdooring in Kumasi to Zulu imbeleko in Durban', tools: ['service_session', 'event_planner', 'client_tracker', 'mobile_payment_collect', 'appointment_book'], moneyFlow: 'Officiating fee via Cowrie service session. Ceremony planning package with deposit. Cultural item procurement billed separately. Guest coordination as add-on service.', crestPath: 'Officiate 60 naming ceremonies. Master 4 different cultural naming traditions. Get 40 family endorsements. Coordinate ceremonies with 100+ guests.', businessSessionType: 'community' },
  // ── HERITAGE & HISTORY ─────────────────────────────────────
  { key: 'clan_historian', name: 'Clan Historian / Oral History Keeper', desc: 'Preserves and transmits family and clan histories through oral tradition — from Griot traditions in Bamako Mali to clan elders in Igboland to izibongo praise poets in KwaZulu-Natal', tools: ['content_planner', 'service_session', 'document_vault', 'client_tracker', 'mobile_payment_collect'], moneyFlow: 'Family history documentation fee via Cowrie. Audio and video recording sessions billed per hour. Published family history book projects via escrow milestone payments.', crestPath: 'Document 30 family histories. Record 100 hours of oral history. Trace 20 lineages back 5+ generations. Publish 10 family history documents.', businessSessionType: 'community' },
  { key: 'genealogy_researcher', name: 'Genealogy Researcher / Ancestry Tracer', desc: 'Traces family lineages using records, DNA, and oral histories — from National Archives Ibadan to Kenya National Archives Nairobi to Cape Town Archives Repository', tools: ['document_vault', 'service_session', 'client_tracker', 'invoice_generator', 'referral_tracker', 'appointment_book'], moneyFlow: 'Research package fee via Cowrie escrow — milestone releases at initial findings, full report, and family tree delivery. Per-hour research rate for ongoing projects.', crestPath: 'Complete 40 genealogy research projects. Trace 25 lineages across 4+ generations. Access records in 5 African archives. Achieve genealogy certification.', businessSessionType: 'professional' },
  // ── NUTRITION & WELLNESS ───────────────────────────────────
  { key: 'child_nutrition_advisor', name: 'Child Nutrition Advisor / Paediatric Dietitian', desc: 'Guides families on child nutrition, weaning, and dietary needs — from nutrition clinics in Ikeja Lagos to child wellness centres in Kilimani Nairobi to paediatric units in Groote Schuur Cape Town', tools: ['appointment_book', 'service_session', 'client_tracker', 'session_notes', 'mobile_payment_collect', 'referral_tracker'], moneyFlow: 'Consultation fee via Cowrie per session. Meal plan packages with upfront payment. School nutrition program contracts billed monthly. Workshop fees collected per attendee.', crestPath: 'Consult for 100 families. Create 200 child meal plans. Get registered dietitian certification. Partner with 10 schools for nutrition programs.', businessSessionType: 'professional' },
  { key: 'family_law_consultant', name: 'Family Law Consultant / Custody & Maintenance Advisor', desc: 'Advises on custody, maintenance, divorce, and family legal matters — from law chambers in Ikoyi Lagos to family court advocates in Milimani Nairobi to Cape Town family law firms', tools: ['service_session', 'document_vault', 'client_tracker', 'appointment_book', 'invoice_generator', 'escrow_release'], moneyFlow: 'Consultation fee via Cowrie per session. Case retainer via escrow with milestone billing. Document preparation fees billed per document. Court representation daily rate.', crestPath: 'Handle 50 family law cases. Achieve 75% favourable outcomes. Maintain bar association good standing. Get 30 client endorsements.', businessSessionType: 'professional' },
]
