import type { RoleDefinition } from '../role-registry'

export const FAMILY_ROLES: RoleDefinition[] = [
  { key: 'family_elder', name: 'Family Elder', desc: 'Leads and arbitrates family matters, preserving cultural traditions, lineage records, and community harmony', tools: ['community_board','document_vault','alert_system','community_connect','session_log','outreach_planner','impact_tracker','report_generator'], moneyFlow: 'Community contributions → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'marriage_coordinator', name: 'Marriage Coordinator', desc: 'Plans and coordinates traditional and civil wedding ceremonies, managing families and logistics', tools: ['appointment_book','document_vault','community_connect','client_tracker','billing_dashboard','review_tracker','quick_invoice','community_board'], moneyFlow: 'Coordination fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'child_welfare', name: 'Child Welfare Worker', desc: 'Protects vulnerable children, manages casework, and connects families with social support services', tools: ['client_tracker','alert_system','attendance_tracker','report_generator','community_connect','impact_tracker','outreach_planner','case_log'], moneyFlow: 'NGO salary → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'genealogist', name: 'Genealogist', desc: 'Researches family histories, documents lineage, and preserves ancestral records for African families', tools: ['document_vault','publication_vault','portfolio_vault','recording_vault','community_board','analytics_report','report_generator','outreach_planner'], moneyFlow: 'Research fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'family_mediator', name: 'Family Mediator', desc: 'Resolves family disputes through counselling and mediation, restoring relationships within African families', tools: ['appointment_book','client_tracker','community_connect','session_log','case_log','report_generator','impact_tracker','community_board'], moneyFlow: 'Mediation fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'adoption_officer', name: 'Adoption Officer', desc: 'Manages adoption processes, child placement, and family integration with full legal and welfare compliance', tools: ['document_vault','compliance_checker','report_generator','client_tracker','case_log','alert_system','community_connect','queue_manager'], moneyFlow: 'Government salary → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'homemaker', name: 'Homemaker', desc: 'Manages household operations, family budgeting, and home-based enterprise while nurturing family life', tools: ['daily_target_tracker','inventory_tracker','price_checker','community_board','quick_invoice','community_connect','alert_system','budget_tracker'], moneyFlow: 'Home business → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'youth_mentor', name: 'Youth Mentor', desc: 'Guides young people through education, career choices, and life challenges using community-based mentoring', tools: ['community_board','attendance_tracker','outreach_planner','impact_tracker','community_connect','content_calendar','report_generator','daily_target_tracker'], moneyFlow: 'Program grants → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
]
