import type { RoleDefinition } from '../role-registry'

export const FASHION_ROLES: RoleDefinition[] = [
  { key: 'fashion_designer', name: 'Fashion Designer', desc: 'Creates original clothing and fashion collections, managing client briefs, production, and sales', tools: ['design_brief','portfolio_vault','product_listing','client_tracker','social_shop','review_tracker','payment_link','content_calendar'], moneyFlow: 'Design fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'creative' },
  { key: 'tailor', name: 'Tailor / Seamstress', desc: 'Sews bespoke garments and alterations, serving individual clients for traditional and contemporary wear', tools: ['client_tracker','appointment_book','review_tracker','quick_invoice','inventory_tracker','daily_target_tracker','social_shop','billing_dashboard'], moneyFlow: 'Tailoring fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'goods' },
  { key: 'model', name: 'Model', desc: 'Represents fashion brands on the runway, in campaigns, and across social media platforms', tools: ['portfolio_vault','social_shop','content_calendar','payment_link','booking_calendar','review_tracker','analytics_report','community_board'], moneyFlow: 'Modelling fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'creative' },
  { key: 'hair_stylist', name: 'Hair Stylist / Beauty Technician', desc: 'Provides hair styling, braiding, and beauty services to individual clients', tools: ['appointment_book','client_tracker','social_shop','quick_invoice','inventory_tracker','review_tracker','pos_dashboard','daily_target_tracker'], moneyFlow: 'Service fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'fabric_merchant', name: 'Fabric Merchant', desc: 'Trades and distributes textiles including Ankara, Kente, aso-oke, and imported fabrics across markets', tools: ['inventory_tracker','bulk_order_manager','delivery_tracker','price_checker','quick_invoice','social_shop','product_listing','analytics_report'], moneyFlow: 'Sales margins → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'goods' },
  { key: 'beauty_practitioner', name: 'Beauty Practitioner', desc: 'Provides makeup, skincare, nail art, and beauty therapy services for individuals and events', tools: ['appointment_book','inventory_tracker','pos_dashboard','client_tracker','review_tracker','social_shop','quick_invoice','daily_target_tracker'], moneyFlow: 'Service fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'shoe_maker', name: 'Shoe Maker', desc: 'Crafts bespoke leather and fabric shoes using traditional techniques, selling locally and online', tools: ['product_listing','social_shop','value_calculator','portfolio_vault','quick_invoice','client_tracker','review_tracker','inventory_tracker'], moneyFlow: 'Product sales → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'goods' },
  { key: 'jewellery_designer', name: 'Jewellery Designer', desc: 'Creates handcrafted jewellery using gold, beads, and traditional African materials for local and export markets', tools: ['inventory_tracker','social_shop','value_calculator','portfolio_vault','product_listing','quick_invoice','client_tracker','review_tracker'], moneyFlow: 'Jewellery sales → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'goods' },
]
