import type { RoleDefinition } from '../role-registry'

export const FASHION_ROLES: RoleDefinition[] = [
  // ── TAILORING & BESPOKE ────────────────────────────────────
  { key: 'tailor', name: 'Tailor / Stitching Master', desc: 'Cuts and sews everyday clothing, school uniforms, and traditional wear — from the Aba tailoring clusters in Abia State Nigeria to Eastleigh sewing shops of Nairobi, Kenya', tools: ['service_session', 'measurement_book', 'fabric_calculator', 'appointment_book', 'mobile_payment_collect'], moneyFlow: 'Clients pay 50% deposit via Cowrie to open service session, balance on pickup. Bulk school uniform contracts settled monthly via escrow.', crestPath: 'Complete 300 sealed garment sessions. Maintain 95% on-time delivery for 60 days. Get 100 five-star Kila reviews.', businessSessionType: 'service' },
  { key: 'fashion_designer', name: 'Fashion Designer / Creative Director', desc: 'Designs original collections blending African aesthetics with global trends — from Adama Paris studios in Dakar, Senegal to Lisa Folawiyo atelier in Victoria Island, Lagos', tools: ['design_portfolio', 'collection_planner', 'trade_session', 'social_shop', 'client_tracker', 'mood_board'], moneyFlow: 'Design fees via Cowrie service session. Collection pre-orders through social shop with 40% deposit escrow. Runway show ticket sales via event booking.', crestPath: 'Launch 4 seasonal collections. Dress 10 verified public figures. Sell 500 pieces through social shop. Hit 1,000 portfolio views.', businessSessionType: 'creative' },
  { key: 'fabric_seller', name: 'Fabric Seller / Textile Merchant', desc: 'Sells ankara, kente, aso-oke, kitenge, shweshwe, and imported fabrics — from Balogun Market Lagos to Makola Market Accra to Kariakoo Market Dar es Salaam, Tanzania', tools: ['inventory_tracker', 'trade_session', 'price_checker', 'bulk_order_manager', 'runner_dispatch', 'social_shop'], moneyFlow: 'Wholesale and retail fabric sales via Cowrie. Bulk orders from tailors settled through trade session with escrow. Runner dispatches for delivery within city.', crestPath: 'Stock 200 unique fabric patterns. Complete 500 trade sessions. Supply 50 verified tailors. Maintain zero counterfeit complaints.', businessSessionType: 'goods' },
  { key: 'shoe_maker', name: 'Shoe Maker / Cobbler / Footwear Artisan', desc: 'Handcrafts leather shoes, sandals, and repairs footwear — from Aba shoe clusters in Abia State Nigeria to the leather artisans of Marrakech, Morocco', tools: ['service_session', 'product_listing', 'measurement_book', 'trade_session', 'mobile_payment_collect'], moneyFlow: 'Custom orders via Cowrie service session with 50% deposit. Ready-made pairs listed on social shop. Repair jobs paid on completion.', crestPath: 'Craft 200 custom pairs. Maintain 48hr repair turnaround. Get 80 five-star reviews. Export 20 pairs outside home city.', businessSessionType: 'goods' },
  { key: 'bag_maker', name: 'Bag Maker / Leather Goods Artisan', desc: 'Designs and crafts handbags, clutches, briefcases, and travel bags — from the leather tanneries of Kano Nigeria to Arusha Tanzania workshops', tools: ['product_listing', 'trade_session', 'social_shop', 'design_portfolio', 'runner_dispatch'], moneyFlow: 'Direct sales via social shop with Cowrie payment. Custom orders through trade session with escrow. Wholesale to boutiques via bulk order.', crestPath: 'List 50 unique bag designs. Complete 150 trade sessions. Get featured in 5 Voice Stories. Export to 3 different countries.', businessSessionType: 'goods' },
  // ── JEWELLERY & ACCESSORIES ────────────────────────────────
  { key: 'jewellery_maker', name: 'Jewellery Maker / Goldsmith / Beadwork Artisan', desc: 'Creates gold, silver, brass, and beaded jewellery — from the goldsmiths of Omdurman Sudan to bead artisans of Koforidua Ghana and Maasai beadworkers of Arusha Tanzania', tools: ['product_listing', 'trade_session', 'social_shop', 'design_portfolio', 'escrow_release', 'weight_calculator'], moneyFlow: 'Custom commissions via Cowrie escrow — client deposits gold value upfront. Ready pieces sold through social shop. Wholesale to boutiques via trade session.', crestPath: 'Create 100 unique pieces. Process 50 gold commissions via escrow. Achieve 200 social shop sales. Get verified artisan badge.', businessSessionType: 'creative' },
  // ── HAIR & BEAUTY ─────────────────────────────────────────
  { key: 'hair_stylist', name: 'Hair Stylist / Braider / Loctician', desc: 'Braids, weaves, locks, and styles African hair — from salon strips in Surulere Lagos to Kigali beauty parlours to Sandton Johannesburg salons', tools: ['appointment_book', 'service_session', 'style_portfolio', 'mobile_payment_collect', 'customer_list', 'ajo_circle'], moneyFlow: 'Per-session fees via Cowrie — booking deposit holds appointment. Walk-ins pay on completion. Tips via Kila. Product upsells tracked separately.', crestPath: 'Complete 500 styling sessions. Build client list of 150 regulars. Maintain 4.8+ rating. Post 50 style portfolio photos.', businessSessionType: 'service' },
  { key: 'makeup_artist', name: 'Makeup Artist / MUA / Beauty Consultant', desc: 'Professional makeup for weddings, photoshoots, events, and editorial — from Tara Fela-Durotoye trained artists in Lagos to Addis Ababa bridal specialists', tools: ['appointment_book', 'service_session', 'style_portfolio', 'mobile_payment_collect', 'client_tracker'], moneyFlow: 'Booking deposit via Cowrie locks appointment. Full payment on session completion. Bridal packages use escrow for multi-day events. Product sales as add-on.', crestPath: 'Complete 200 bridal sessions. Build portfolio of 100 looks. Get 80 five-star Kila reviews. Train 5 apprentices.', businessSessionType: 'service' },
  { key: 'nail_technician', name: 'Nail Technician / Nail Artist', desc: 'Manicures, pedicures, gel nails, acrylics, and nail art — from beauty hubs in Westlands Nairobi to Lekki Lagos to Sandton City Johannesburg', tools: ['appointment_book', 'service_session', 'style_portfolio', 'mobile_payment_collect', 'customer_list'], moneyFlow: 'Per-service Cowrie payment on completion. Subscription packages for regular clients — monthly auto-debit. Product add-ons tracked per session.', crestPath: 'Complete 400 nail sessions. Build subscription list of 50 regulars. Post 80 nail art designs. Maintain zero infection reports.', businessSessionType: 'service' },
  // ── TEXTILE CRAFT ──────────────────────────────────────────
  { key: 'textile_dyer', name: 'Textile Dyer / Adire Maker / Batik Artist', desc: 'Creates hand-dyed fabrics using adire, batik, and tie-dye techniques — from the indigo pits of Abeokuta Nigeria to batik workshops in Kumasi Ghana', tools: ['product_listing', 'trade_session', 'social_shop', 'design_portfolio', 'workshop_scheduler'], moneyFlow: 'Finished fabric sold per yard via Cowrie. Wholesale orders through trade session with escrow. Workshop fees collected upfront via service session.', crestPath: 'Produce 500 yards of hand-dyed fabric. Complete 100 trade sessions. Host 10 dyeing workshops. Get UNESCO craft recognition nomination.', businessSessionType: 'creative' },
  { key: 'fashion_model', name: 'Fashion Model / Runway Model', desc: 'Professional model for runway shows, lookbooks, and brand campaigns — from Lagos Fashion Week to Dakar Fashion Week to AFI Johannesburg', tools: ['model_portfolio', 'appointment_book', 'service_session', 'client_tracker', 'rate_calculator'], moneyFlow: 'Booking fees via Cowrie service session — half upfront, half on shoot completion. Runway fees settled within 48hrs post-show. Usage rights negotiated per campaign.', crestPath: 'Walk 20 runway shows. Complete 50 brand campaigns. Build portfolio of 200 professional shots. Get featured in 3 major fashion publications.', businessSessionType: 'creative' },
  // ── FASHION MEDIA ──────────────────────────────────────────
  { key: 'fashion_photographer', name: 'Fashion Photographer / Lookbook Specialist', desc: 'Shoots fashion editorials, lookbooks, and campaign imagery — from Studio 24 Lagos to creative studios in Accra, Nairobi, and Johannesburg', tools: ['service_session', 'appointment_book', 'design_portfolio', 'invoice_generator', 'client_tracker', 'escrow_release'], moneyFlow: 'Session fee via Cowrie — 50% booking deposit, balance on delivery of edited images. Usage licensing as separate Cowrie payment. Escrow for large brand contracts.', crestPath: 'Shoot 100 fashion sessions. Build portfolio of 500 published images. Work with 30 different designers. Maintain 48hr edit turnaround.', businessSessionType: 'creative' },
  { key: 'fashion_blogger', name: 'Fashion Blogger / Style Influencer', desc: 'Creates fashion content, reviews, and style guides — from Noble Igwe in Lagos to Nancie Mwai in Nairobi to Sarah Langa in Johannesburg', tools: ['social_shop', 'content_planner', 'brand_collab_tracker', 'mobile_payment_collect', 'analytics_dashboard'], moneyFlow: 'Brand collaboration fees via Cowrie trade session. Affiliate commissions on social shop sales. Sponsored content settled via escrow on publication.', crestPath: 'Publish 200 fashion posts. Complete 30 brand collaborations. Drive 1,000 social shop referral sales. Hit 10,000 content views.', businessSessionType: 'creative' },
  // ── RETAIL & BOUTIQUE ──────────────────────────────────────
  { key: 'boutique_owner', name: 'Boutique Owner / Fashion Retail Shop', desc: 'Runs a curated clothing store — from high-end boutiques on Victoria Island Lagos to Osu Oxford Street Accra to Melrose Arch Johannesburg', tools: ['inventory_tracker', 'trade_session', 'social_shop', 'pos_dashboard', 'customer_list', 'supplier_connect'], moneyFlow: 'In-store and online sales via Cowrie POS. Supplier restocking via trade session with credit terms. Social shop for nationwide delivery orders.', crestPath: 'Stock 300 unique items. Complete 1,000 sales transactions. Build customer list of 200 regulars. Maintain 15% monthly growth for 6 months.', businessSessionType: 'goods' },
  { key: 'bridal_consultant', name: 'Bridal Consultant / Wedding Stylist', desc: 'Curates complete bridal looks including gown, aso-ebi coordination, accessories — from Yemi Osunkoya Kosibah in London-Lagos to Johannesburg bridal houses', tools: ['appointment_book', 'service_session', 'client_tracker', 'supplier_connect', 'escrow_release', 'mood_board'], moneyFlow: 'Consultation fee via Cowrie. Full bridal package in escrow — released in stages: fitting, final adjustment, delivery day. Aso-ebi coordination commission from fabric sellers.', crestPath: 'Style 50 brides. Coordinate 20 aso-ebi groups of 30+ people. Maintain 100% on-time delivery. Get 40 five-star reviews.', businessSessionType: 'service' },
  // ── MANUFACTURING ──────────────────────────────────────────
  { key: 'uniform_manufacturer', name: 'Uniform Manufacturer / Corporate Wear Producer', desc: 'Mass-produces school uniforms, corporate wear, and security uniforms — from Aba garment factories Nigeria to Thika industrial area Kenya', tools: ['bulk_order_manager', 'trade_session', 'escrow_release', 'inventory_tracker', 'invoice_generator', 'measurement_book'], moneyFlow: 'Institutional contracts via Cowrie escrow — 30% deposit on order, 40% on production start, 30% on delivery. School uniform seasonal bulk orders.', crestPath: 'Deliver 50 institutional contracts. Produce 10,000 uniform pieces. Maintain 98% quality pass rate. Supply 20 schools or companies.', businessSessionType: 'goods' },
  { key: 'leather_goods_maker', name: 'Leather Goods Maker / Belt & Wallet Artisan', desc: 'Crafts leather belts, wallets, watch straps, and small accessories — from Kano tannery artisans Nigeria to Fez leather craftsmen Morocco', tools: ['product_listing', 'trade_session', 'social_shop', 'design_portfolio', 'runner_dispatch'], moneyFlow: 'Direct sales via social shop with Cowrie. Custom orders through trade session — full payment before dispatch. Wholesale to shops via bulk order.', crestPath: 'List 80 unique products. Complete 200 trade sessions. Get 50 repeat customers. Export to 5 cities outside home base.', businessSessionType: 'goods' },
  { key: 'hat_maker', name: 'Hat Maker / Milliner / Cap Artisan', desc: 'Creates traditional and modern headwear — fila from Ibadan, kufi caps from Kano, fascinators in Nairobi, doeks in Cape Town South Africa', tools: ['product_listing', 'social_shop', 'trade_session', 'design_portfolio', 'measurement_book'], moneyFlow: 'Custom hats via Cowrie service session with deposit. Ready-made pieces on social shop. Wholesale to boutiques via trade session with escrow.', crestPath: 'Craft 150 custom headpieces. List 60 ready-made designs. Supply 15 boutiques. Get featured in 3 fashion editorials.', businessSessionType: 'goods' },
  // ── SPECIALISED CRAFT ──────────────────────────────────────
  { key: 'embroidery_specialist', name: 'Embroidery Specialist / Agbada Embellisher', desc: 'Hand and machine embroidery on agbada, babban riga, boubou, and kaftan — from the master embroiderers of Zaria Nigeria to Saint-Louis Senegal artisans', tools: ['service_session', 'design_portfolio', 'appointment_book', 'measurement_book', 'mobile_payment_collect'], moneyFlow: 'Per-garment embroidery fee via Cowrie — deposit on drop-off, balance on collection. Rush orders carry 50% premium. Bulk embroidery contracts for fashion houses via escrow.', crestPath: 'Embroider 300 garments. Master 10 distinct embroidery patterns. Build portfolio of 50 signature designs. Maintain 5-day turnaround on standard orders.', businessSessionType: 'service' },
  { key: 'fashion_event_organiser', name: 'Fashion Event Organiser / Show Producer (Planning)', desc: 'Plans and coordinates fashion exhibitions, pop-up shops, and trunk shows — from GTBank Fashion Weekend Lagos to Swahili Fashion Week Dar es Salaam', tools: ['event_planner', 'vendor_manager', 'ticket_sales', 'invoice_generator', 'client_tracker', 'escrow_release'], moneyFlow: 'Event management fee via Cowrie escrow — milestone releases at planning, execution, and post-event. Vendor booth fees collected and held in escrow until event day.', crestPath: 'Organise 20 fashion events. Host 200 vendor booths total. Sell 5,000 event tickets. Maintain zero vendor disputes.', businessSessionType: 'service' },
  // ── BUYING & SOURCING ──────────────────────────────────────
  { key: 'fashion_buyer', name: 'Fashion Buyer / Retail Sourcing Agent', desc: 'Sources fashion merchandise from designers and manufacturers for retail stores — buying trips to Guangzhou China, Istanbul Turkey, and across West Africa', tools: ['supplier_connect', 'trade_session', 'escrow_release', 'price_checker', 'inventory_tracker', 'document_vault'], moneyFlow: 'Commission on sourced merchandise via Cowrie — 8-15% of order value. Escrow protects both boutique and supplier. International sourcing uses Cowrie forex bridge.', crestPath: 'Source for 30 boutiques. Complete 200 international sourcing orders. Maintain 95% quality acceptance rate. Build supplier network of 50 verified vendors.', businessSessionType: 'professional' },
  { key: 'textile_printer', name: 'Textile Printer / Screen Print Operator', desc: 'Prints custom designs on fabric using screen printing, sublimation, and digital methods — from Aswani Market Lagos to Eastleigh Nairobi printing houses', tools: ['service_session', 'bulk_order_manager', 'design_portfolio', 'trade_session', 'invoice_generator'], moneyFlow: 'Per-metre or per-unit printing fee via Cowrie. Bulk orders through trade session with 40% deposit. Rush jobs carry premium rates. Monthly contracts for fashion houses.', crestPath: 'Print 10,000 metres of fabric. Complete 300 print jobs. Build client list of 40 fashion brands. Maintain zero misprint rate for 90 days.', businessSessionType: 'service' },
  { key: 'pattern_maker', name: 'Pattern Maker / Garment Technician', desc: 'Creates paper and digital patterns for garment production — from fashion houses in Yaba Lagos to garment factories in Thika Kenya to Cape Town design studios', tools: ['design_portfolio', 'service_session', 'measurement_book', 'client_tracker', 'invoice_generator'], moneyFlow: 'Per-pattern fee via Cowrie service session. Grading fees for size ranges. Monthly retainer contracts with fashion houses settled via escrow.', crestPath: 'Create 200 original patterns. Grade 100 patterns across 5+ sizes. Work with 25 fashion brands. Achieve ISO pattern accuracy certification.', businessSessionType: 'professional' },
  // ── EDUCATION & TRAINING ───────────────────────────────────
  { key: 'fashion_instructor', name: 'Fashion Instructor / Sewing Teacher', desc: 'Teaches fashion design, tailoring, and textile skills — from FADAN training centres in Lagos to Kigali fashion institutes to Kumasi polytechnic workshops Ghana', tools: ['workshop_scheduler', 'service_session', 'student_tracker', 'content_planner', 'mobile_payment_collect', 'certificate_issuer'], moneyFlow: 'Course fees via Cowrie — full upfront or 3-instalment plan. Workshop fees per session. Certificate issuance fee. Apprenticeship monthly stipend deducted from trainee earnings.', crestPath: 'Train 100 students. Issue 50 completion certificates. Maintain 90% graduation rate. Get 5 students placed in fashion houses.', businessSessionType: 'service' },
  { key: 'accessories_designer', name: 'Accessories Designer / Fashion Jewellery Creator', desc: 'Designs fashion accessories — scarves, brooches, cufflinks, hair accessories — from Lekki craft markets Lagos to Maasai Market Nairobi to Greenmarket Square Cape Town', tools: ['product_listing', 'social_shop', 'design_portfolio', 'trade_session', 'runner_dispatch'], moneyFlow: 'Direct-to-consumer via social shop Cowrie payments. Wholesale to boutiques via trade session. Market stall daily sales to Cowrie wallet.', crestPath: 'Design 100 unique accessories. Achieve 300 social shop sales. Supply 20 retail locations. Get featured in 5 fashion publications.', businessSessionType: 'creative' },
  // ── VINTAGE & RESALE ───────────────────────────────────────
  { key: 'vintage_dealer', name: 'Vintage Dealer / Retro Fashion Curator', desc: 'Curates and sells vintage and retro clothing and accessories — from Yaba thrift markets Lagos to Gikomba Nairobi to Milnerton Market Cape Town', tools: ['product_listing', 'social_shop', 'trade_session', 'price_checker', 'runner_dispatch', 'buyer_shadow_score'], moneyFlow: 'Source vintage pieces at thrift prices, sell at curated premium via social shop Cowrie. Bundle deals for repeat buyers. Delivery via runner dispatch.', crestPath: 'Curate 500 vintage pieces. Complete 200 social shop sales. Build collection of 50 rare finds. Maintain 90% buyer satisfaction.', businessSessionType: 'goods' },
  { key: 'children_clothing_maker', name: 'Children Clothing Maker / Kids Fashion Designer', desc: 'Designs and produces children clothing with African prints and child-safe materials — from Ruff n Tumble style houses in Lagos to Nairobi children boutiques', tools: ['product_listing', 'social_shop', 'trade_session', 'measurement_book', 'bulk_order_manager', 'inventory_tracker'], moneyFlow: 'Retail via social shop Cowrie. School uniform bulk contracts via escrow. Wholesale to children boutiques through trade session. Seasonal collections pre-ordered with 30% deposit.', crestPath: 'Produce 1,000 children garments. Supply 15 children boutiques. Complete 5 school uniform contracts. Maintain zero safety complaints.', businessSessionType: 'goods' },
  // ── COSTUME & PERFORMANCE ──────────────────────────────────
  { key: 'costume_designer', name: 'Costume Designer / Stage & Film Wardrobe', desc: 'Creates costumes for Nollywood films, theatre productions, and cultural festivals — from Surulere film studios Lagos to Kenya Film Commission productions in Nairobi', tools: ['service_session', 'design_portfolio', 'client_tracker', 'escrow_release', 'measurement_book', 'supplier_connect'], moneyFlow: 'Production contract via Cowrie escrow — milestone payments at design approval, fitting, and wrap. Rental costumes charged per day. Festival commissions settled post-event.', crestPath: 'Costume 20 film or theatre productions. Build wardrobe library of 200 pieces. Work with 10 production houses. Get AMVCA or AMAA nomination.', businessSessionType: 'creative' },
  { key: 'bespoke_suit_maker', name: 'Bespoke Suit Maker / Savile Row of Africa', desc: 'Crafts tailored suits, tuxedos, and formal wear to measure — from Mai Atafo atelier Lagos to Outfitters Nairobi to House of Monatic Cape Town South Africa', tools: ['measurement_book', 'service_session', 'appointment_book', 'fabric_calculator', 'client_tracker', 'escrow_release'], moneyFlow: 'Bespoke orders via Cowrie escrow — 40% deposit at measurement, 30% at first fitting, 30% on delivery. Premium fabrics sourced with client approval. Alteration fees separate.', crestPath: 'Tailor 100 bespoke suits. Maintain 3-fitting maximum per suit. Build VIP client list of 50. Get featured in GQ South Africa or Guardian Life.', businessSessionType: 'service' },
  { key: 'fashion_show_producer', name: 'Fashion Show Producer / Runway Director', desc: 'Produces full fashion shows and runway events — from Lagos Fashion Week to Arise Fashion Week to Mercedes Benz Fashion Week Johannesburg to Dakar Fashion Week', tools: ['event_planner', 'vendor_manager', 'ticket_sales', 'escrow_release', 'client_tracker', 'invoice_generator'], moneyFlow: 'Production fee via Cowrie escrow — 30% on contract, 40% pre-show, 30% post-show. Sponsorship revenue held in escrow. Model fees, venue, and tech crew paid via Cowrie invoices.', crestPath: 'Produce 15 runway shows. Manage 200 model bookings. Secure 30 brand sponsorships. Achieve 5,000 total audience attendance. Zero show delays.', businessSessionType: 'creative' },
]
