import type { RoleDefinition } from '../role-registry'

export const FINANCE_ROLES: RoleDefinition[] = [
  { key: 'bank_officer', name: 'Bank Officer', desc: 'Manages customer accounts, processes transactions, and ensures regulatory compliance at financial institutions', tools: ['transaction_log','daily_settlement','compliance_checker','audit_report','client_tracker','billing_dashboard','risk_calculator','document_vault'], moneyFlow: 'Salary → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'financial_analyst', name: 'Financial Analyst', desc: 'Analyses financial markets, builds investment models, and produces research reports for institutions and clients', tools: ['analytics_report','risk_calculator','portfolio_vault','publication_vault','report_generator','community_board','grant_tracker','daily_pnl'], moneyFlow: 'Analysis fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'microfinance', name: 'Microfinance / VSLA Coordinator', desc: 'Manages village savings and loan associations, tracks member contributions, and oversees credit disbursement', tools: ['ajo_circle','credit_book','community_connect','impact_tracker','attendance_tracker','daily_settlement','report_generator','alert_system'], moneyFlow: 'Management fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'fintech_entrepreneur', name: 'Fintech Entrepreneur', desc: 'Builds financial technology products and payment infrastructure for African markets', tools: ['api_tester','analytics_report','project_tracker','code_project','client_tracker','community_board','risk_calculator','compliance_checker'], moneyFlow: 'Product revenue → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'accountant', name: 'Accountant / Auditor', desc: 'Prepares financial statements, conducts audits, and ensures compliance with tax and accounting standards', tools: ['billing_dashboard','audit_report','compliance_checker','transaction_log','analytics_report','document_vault','report_generator','daily_settlement'], moneyFlow: 'Service fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'insurance_agent', name: 'Insurance Agent', desc: 'Sells and services insurance products, managing claims, policy administration, and risk assessment', tools: ['risk_calculator','client_tracker','compliance_checker','policy_vault','claims_log','billing_dashboard','analytics_report','alert_system'], moneyFlow: 'Commission → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'crypto_defi', name: 'Crypto / DeFi Expert', desc: 'Operates in digital asset trading, DeFi protocols, and blockchain-based financial infrastructure', tools: ['api_tester','transaction_log','compliance_checker','analytics_report','risk_calculator','code_project','community_board','alert_system'], moneyFlow: 'Trading profits → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'ajo_keeper', name: 'Ajo Circle Keeper', desc: 'Organises and manages rotating savings circles (susu, esusu, ajo, chama) within communities', tools: ['ajo_circle','transaction_log','community_connect','daily_settlement','member_tracker','alert_system','report_generator','quick_invoice'], moneyFlow: 'Circle management fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
]
