import type { RoleDefinition } from '../role-registry'

export const GOVERNMENT_ROLES: RoleDefinition[] = [
  { key: 'civil_servant', name: 'Civil Servant', desc: 'Delivers public services and implements government policies at community and national levels', tools: ['document_vault','compliance_checker','report_generator','queue_manager','daily_target_tracker','attendance_tracker','alert_system','community_board'], moneyFlow: 'Government salary → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'elected_official', name: 'Elected Official', desc: 'Represents constituents, shapes policy, and ensures accountable governance at local and national levels', tools: ['campaign_manager','community_board','analytics_report','outreach_planner','report_generator','impact_tracker','community_connect','media_list'], moneyFlow: 'Public salary → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'diplomat', name: 'Diplomat', desc: 'Represents national interests in foreign relations, trade negotiations, and international organisations', tools: ['document_vault','community_connect','outreach_planner','translation_log','booking_calendar','report_generator','analytics_report','publication_vault'], moneyFlow: 'Diplomatic salary → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'urban_planner', name: 'Urban Planner', desc: 'Designs sustainable cities, coordinates infrastructure development, and manages land-use planning', tools: ['site_survey','territory_map','technical_docs','project_tracker','analytics_report','community_connect','grant_tracker','report_generator'], moneyFlow: 'Planning fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'tax_collector', name: 'Tax Collector', desc: 'Assesses, collects, and processes taxes and government levies from individuals and businesses', tools: ['transaction_log','billing_dashboard','compliance_checker','territory_map','daily_settlement','alert_system','report_generator','analytics_report'], moneyFlow: 'Government salary → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'registrar', name: 'Registrar', desc: 'Manages official records including births, deaths, marriages, businesses, and land titles', tools: ['document_vault','queue_manager','billing_dashboard','compliance_checker','client_tracker','daily_target_tracker','alert_system','report_generator'], moneyFlow: 'Registration fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'policy_analyst', name: 'Policy Analyst', desc: 'Researches policy issues, evaluates programme effectiveness, and advises government on evidence-based decisions', tools: ['analytics_report','publication_vault','grant_tracker','report_generator','community_board','data_dashboard','impact_tracker','outreach_planner'], moneyFlow: 'Consultancy fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'elections_officer', name: 'Elections Officer', desc: 'Manages electoral processes, voter registration, and election day operations for credible democratic elections', tools: ['territory_map','community_alert','compliance_checker','attendance_tracker','report_generator','document_vault','alert_system','analytics_report'], moneyFlow: 'Government salary → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
]
