import type { RoleDefinition } from '../role-registry'

export const HEALTH_ROLES: RoleDefinition[] = [
  { key: 'doctor', name: 'Medical Doctor', desc: 'Diagnoses and treats patients, managing appointments, prescriptions, referrals, and telemedicine consultations.', tools: ["appointment_book","telemedicine","billing_dashboard","client_tracker","prescription_vault","referral_generator","analytics_report","community_alert"], moneyFlow: 'Consultation fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'nurse', name: 'Nurse / Midwife', desc: 'Provides frontline patient care, community outreach, and health monitoring across clinical and field settings.', tools: ["queue_manager","client_tracker","community_alert","appointment_book","daily_target_tracker","outreach_planner","report_generator","alert_system"], moneyFlow: 'Service fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'traditional_healer', name: 'Traditional Healer', desc: 'Offers culturally grounded healing services using traditional remedies, managing inventory and client sessions.', tools: ["inventory_tracker","community_board","document_vault","session_log","product_listing","review_tracker","quick_invoice","content_calendar"], moneyFlow: 'Session fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'community_health', name: 'Community Health Worker', desc: 'Conducts grassroots health education and outreach, tracking impact and connecting communities to health services.', tools: ["territory_map","outreach_planner","alert_system","attendance_tracker","impact_tracker","community_connect","report_generator","daily_target_tracker"], moneyFlow: 'Stipends and grants → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'pharmacist', name: 'Pharmacist', desc: 'Dispenses medications, manages pharmaceutical stock, and ensures drug compliance and expiry monitoring.', tools: ["stock_tracker","price_checker","pos_dashboard","compliance_checker","alert_system","daily_settlement","invoice_batch","inventory_tracker"], moneyFlow: 'Dispensing revenue → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'mental_health', name: 'Mental Health Practitioner', desc: 'Delivers therapy and counselling services via in-person and telemedicine sessions, managing client records and referrals.', tools: ["telemedicine","appointment_book","report_generator","client_tracker","session_log","referral_generator","analytics_report","community_connect"], moneyFlow: 'Session fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'lab_scientist', name: 'Lab Scientist', desc: 'Processes and analyses clinical samples, maintaining quality standards, compliance records, and test result documentation.', tools: ["quality_log","document_vault","queue_manager","sample_log","audit_report","compliance_checker","equipment_log","report_generator"], moneyFlow: 'Test fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'public_health', name: 'Public Health Officer', desc: 'Plans and implements population-level health programmes, tracking disease trends, campaigns, and community impact.', tools: ["community_alert","territory_map","impact_tracker","analytics_report","grant_tracker","outreach_planner","report_generator","campaign_manager"], moneyFlow: 'Government and grant funding → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
]
