import type { RoleDefinition } from '../role-registry'

export const HOLDINGS_ROLES: RoleDefinition[] = [
  { key: 'explorer', name: 'Explorer', desc: 'Discovering where they belong on the platform — new member exploring all 20 villages before committing', tools: ['analytics_report','community_board','daily_target_tracker','portfolio_vault','risk_calculator','outreach_planner','community_connect','content_calendar'], moneyFlow: 'Exploring → Cowrie wallet when active.', crestPath: 'Join a village to begin your journey.', businessSessionType: 'community' },
  { key: 'career_changer', name: 'Career Changer', desc: 'Transitioning between professions, leveraging existing skills while building new ones for a different village', tools: ['project_tracker','document_vault','outreach_planner','portfolio_vault','community_board','analytics_report','appointment_book','daily_target_tracker'], moneyFlow: 'Transition support → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'new_graduate', name: 'New Graduate', desc: 'Recently graduated professional beginning their career journey, building first professional networks', tools: ['portfolio_vault','community_board','daily_target_tracker','outreach_planner','content_calendar','analytics_report','appointment_book','community_connect'], moneyFlow: 'First earnings → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'entrepreneur_formation', name: 'Entrepreneur in Formation', desc: 'Building a business from scratch, testing ideas and finding the right village ecosystem for their venture', tools: ['risk_calculator','project_tracker','billing_dashboard','community_board','analytics_report','community_connect','outreach_planner','daily_target_tracker'], moneyFlow: 'Startup revenue → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'volunteer', name: 'Community Volunteer', desc: 'Gives time and skills to community causes, earning recognition while building professional credibility', tools: ['community_connect','impact_tracker','outreach_planner','community_board','attendance_tracker','report_generator','alert_system','daily_target_tracker'], moneyFlow: 'Community impact → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'multi_skilled', name: 'Multi-Skilled Worker', desc: 'Operates across multiple domains with a portfolio of skills that spans more than one village ecosystem', tools: ['analytics_report','portfolio_vault','community_board','daily_target_tracker','outreach_planner','content_calendar','community_connect','quick_invoice'], moneyFlow: 'Multiple income streams → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'navigator', name: 'Navigator', desc: 'Strategically maps their career path, using data to plan transitions between villages and opportunities', tools: ['analytics_report','risk_calculator','portfolio_vault','community_board','daily_target_tracker','outreach_planner','route_planner','community_connect'], moneyFlow: 'Strategic income → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'returning_citizen', name: 'Returning Citizen', desc: 'Re-entering professional life after a break — post-incarceration, illness, or extended absence', tools: ['document_vault','community_connect','outreach_planner','community_board','portfolio_vault','daily_target_tracker','alert_system','report_generator'], moneyFlow: 'Reintegration support → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
]
