import type { RoleDefinition } from '../role-registry'

export const HOSPITALITY_ROLES: RoleDefinition[] = [
  { key: 'hotel_manager', name: 'Hotel Manager', desc: 'Oversees all hotel operations including reservations, staff, guest experience, and financial performance', tools: ['booking_calendar','staff_manager','daily_settlement','quality_log','review_tracker','analytics_report','alert_system','community_board'], moneyFlow: 'Revenue share → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'chef', name: 'Chef / Cook', desc: 'Prepares meals for restaurants, hotels, events, and street food businesses across African culinary traditions', tools: ['daily_menu_board','quality_log','staff_manager','inventory_tracker','quick_invoice','pos_dashboard','review_tracker','daily_target_tracker'], moneyFlow: 'Catering fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'goods' },
  { key: 'tour_guide', name: 'Tour Guide', desc: 'Leads tourist experiences across Africa, sharing history, culture, and natural wonders with visitors', tools: ['appointment_book','route_planner','review_tracker','quick_invoice','content_calendar','portfolio_vault','community_board','analytics_report'], moneyFlow: 'Tour fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'events_coordinator', name: 'Events Coordinator', desc: 'Plans and executes weddings, corporate events, festivals, and cultural celebrations', tools: ['project_tracker','booking_calendar','client_tracker','staff_manager','billing_dashboard','vendor_log','analytics_report','community_board'], moneyFlow: 'Event fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'bartender', name: 'Bartender', desc: 'Serves drinks, manages bar operations, and creates an engaging hospitality experience for guests', tools: ['daily_menu_board','inventory_tracker','pos_dashboard','quick_invoice','review_tracker','daily_target_tracker','community_board','analytics_report'], moneyFlow: 'Bar sales → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'goods' },
  { key: 'travel_agent', name: 'Travel Agent', desc: 'Books flights, accommodation, and tours for individual and group travellers across Africa and beyond', tools: ['booking_calendar','route_planner','payment_link','client_tracker','review_tracker','quick_invoice','analytics_report','community_board'], moneyFlow: 'Booking commissions → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'resort_manager', name: 'Resort Manager', desc: 'Manages resort operations including guest experience, maintenance, staff, and financial performance', tools: ['booking_calendar','staff_manager','maintenance_log','quality_log','billing_dashboard','analytics_report','alert_system','review_tracker'], moneyFlow: 'Revenue share → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'camp_host', name: 'Camp Host', desc: 'Runs safari camps, eco-lodges, and glamping sites, managing bookings and outdoor guest experiences', tools: ['booking_calendar','safety_checklist','territory_map','inventory_tracker','quick_invoice','review_tracker','community_board','daily_target_tracker'], moneyFlow: 'Camp fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
]
