import type { RoleDefinition } from '../role-registry'

export const JUSTICE_ROLES: RoleDefinition[] = [
  { key: 'lawyer', name: 'Lawyer', desc: 'Provides legal representation, advice, and advocacy for clients in civil, criminal, and corporate matters', tools: ['case_log','document_vault','billing_dashboard','research_vault','client_tracker','compliance_checker','booking_calendar','analytics_report'], moneyFlow: 'Legal fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'mediator', name: 'Mediator', desc: 'Facilitates dispute resolution between parties, guiding them toward mutually acceptable agreements', tools: ['appointment_book','client_tracker','community_connect','session_log','case_log','report_generator','impact_tracker','community_board'], moneyFlow: 'Mediation fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'magistrate', name: 'Magistrate / Judge', desc: 'Presides over court proceedings, applies the law, and delivers judgments in civil and criminal cases', tools: ['case_log','attendance_tracker','compliance_checker','document_vault','report_generator','booking_calendar','analytics_report','alert_system'], moneyFlow: 'Judicial salary → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'paralegal', name: 'Paralegal', desc: 'Supports lawyers with case preparation, legal research, documentation, and client communication', tools: ['case_log','document_vault','compliance_checker','research_vault','client_tracker','quick_invoice','billing_dashboard','report_generator'], moneyFlow: 'Service fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'human_rights', name: 'Human Rights Defender', desc: 'Advocates for justice, civil rights, and community protection through legal and grassroots channels', tools: ['impact_tracker','grant_tracker','campaign_manager','community_board','outreach_planner','publication_vault','alert_system','report_generator'], moneyFlow: 'Grants → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'notary', name: 'Notary', desc: 'Authenticates legal documents, certifies agreements, and administers oaths for official purposes', tools: ['document_vault','compliance_checker','billing_dashboard','client_tracker','appointment_book','queue_manager','quick_invoice','daily_settlement'], moneyFlow: 'Notarial fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'justice_elder', name: 'Traditional Justice Elder', desc: 'Applies customary law and community-based conflict resolution in the tradition of Gacaca and village courts', tools: ['community_board','case_log','alert_system','community_connect','session_log','impact_tracker','report_generator','outreach_planner'], moneyFlow: 'Community contributions → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'prison_reform', name: 'Prison Reform Worker', desc: 'Works on rehabilitation, reintegration, and criminal justice reform to restore dignity to those affected', tools: ['impact_tracker','outreach_planner','grant_tracker','community_connect','community_board','analytics_report','report_generator','alert_system'], moneyFlow: 'NGO grants → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
]
