import type { RoleDefinition } from '../role-registry'

export const MEDIA_ROLES: RoleDefinition[] = [
  { key: 'journalist', name: 'Journalist', desc: 'Investigates and reports news stories across print, digital, and broadcast platforms', tools: ['article_vault','content_calendar','publication_vault','source_log','analytics_report','community_board','campaign_manager','outreach_planner'], moneyFlow: 'Story fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'creative' },
  { key: 'broadcaster', name: 'Radio/TV Broadcaster', desc: 'Hosts radio or television programmes, managing content scheduling and audience engagement', tools: ['analytics_report','moderation_queue','portfolio_vault','content_calendar','community_board','booking_calendar','social_shop','review_tracker'], moneyFlow: 'Broadcast fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'creative' },
  { key: 'photographer', name: 'Photographer', desc: 'Provides professional photography services for events, brands, editorial, and documentary work', tools: ['portfolio_vault','social_shop','product_listing','client_tracker','quick_invoice','review_tracker','content_calendar','analytics_report'], moneyFlow: 'Session fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'creative' },
  { key: 'social_creator', name: 'Social Media Creator', desc: 'Produces viral content for Jollof TV, Soro Soke Feed, and African platforms, monetising audience and brand deals', tools: ['content_calendar','analytics_report','payment_link','portfolio_vault','review_tracker','social_shop','community_board','daily_target_tracker'], moneyFlow: 'Brand deals → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'creative' },
  { key: 'pr_practitioner', name: 'PR Practitioner', desc: 'Manages public relations campaigns, media outreach, and brand reputation for clients and organisations', tools: ['campaign_manager','client_tracker','outreach_planner','press_kit_vault','analytics_report','media_list','content_calendar','report_generator'], moneyFlow: 'Retainer fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'podcast_host', name: 'Podcast Host', desc: 'Produces and distributes audio podcasts, managing episodes, guests, and listener monetisation', tools: ['content_calendar','moderation_queue','community_board','recording_vault','analytics_report','payment_link','review_tracker','episode_tracker'], moneyFlow: 'Sponsorship → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'creative' },
  { key: 'video_editor', name: 'Video Editor', desc: 'Edits and post-produces video content for social media, film, advertising, and broadcast clients', tools: ['project_tracker','portfolio_vault','client_tracker','quick_invoice','review_tracker','content_calendar','equipment_log','analytics_report'], moneyFlow: 'Project fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'creative' },
  { key: 'ad_creative', name: 'Ad Creative', desc: 'Develops advertising concepts, campaigns, and creative assets for brands across African markets', tools: ['design_brief','campaign_manager','analytics_report','client_tracker','portfolio_vault','content_calendar','quick_invoice','review_tracker'], moneyFlow: 'Campaign fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'creative' },
]
