import type { RoleDefinition } from '../role-registry'

export const SECURITY_ROLES: RoleDefinition[] = [
  { key: 'police_officer', name: 'Police Officer', desc: 'Maintains law and order, responds to incidents, and protects community safety through daily patrols', tools: ['territory_map','alert_system','community_alert','incident_log','report_generator','compliance_checker','daily_target_tracker','route_planner'], moneyFlow: 'Government salary → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'cybersecurity_gov', name: 'Cybersecurity Government', desc: 'Protects national digital infrastructure, monitors threats, and responds to cyber incidents for government systems', tools: ['remote_access_tool','backup_monitor','compliance_checker','audit_log','incident_log','technical_docs','alert_system','analytics_report'], moneyFlow: 'Government salary → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'fire_rescue', name: 'Fire & Rescue', desc: 'Responds to fires, accidents, and emergencies, managing equipment and coordinating disaster response', tools: ['safety_checklist','alert_system','maintenance_log','equipment_log','territory_map','incident_log','report_generator','community_alert'], moneyFlow: 'Government salary → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'private_security', name: 'Private Security', desc: 'Provides guarding, patrol, and asset protection services for businesses, events, and private clients', tools: ['territory_map','client_tracker','quick_invoice','daily_target_tracker','safety_checklist','incident_log','route_planner','review_tracker'], moneyFlow: 'Contract fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'border_guard', name: 'Border Guard', desc: 'Controls entry and exit at national borders, checking documents and preventing illegal crossings', tools: ['territory_map','compliance_checker','alert_system','incident_log','document_vault','daily_target_tracker','report_generator','community_alert'], moneyFlow: 'Government salary → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'forensic_expert', name: 'Forensic Expert', desc: 'Analyses physical and digital evidence for criminal investigations, preparing expert reports for courts', tools: ['document_vault','case_log','quality_log','evidence_vault','compliance_checker','report_generator','analytics_report','audit_log'], moneyFlow: 'Expert fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'community_watch', name: 'Community Watch', desc: 'Organises neighbourhood safety patrols, crime prevention, and community intelligence networks', tools: ['community_alert','territory_map','community_connect','alert_system','incident_log','daily_target_tracker','report_generator','outreach_planner'], moneyFlow: 'Community contributions → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'emergency_management', name: 'Emergency Management', desc: 'Coordinates disaster preparedness, response, and recovery operations across communities and regions', tools: ['alert_system','community_alert','safety_checklist','territory_map','incident_log','resource_tracker','analytics_report','report_generator'], moneyFlow: 'Government salary → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
]
