import type { RoleDefinition } from '../role-registry'

export const SPIRITUALITY_ROLES: RoleDefinition[] = [
  { key: 'imam', name: 'Islamic Scholar / Imam', desc: 'Leads Islamic worship, teaches Quranic studies, and serves as spiritual guide for Muslim communities', tools: ['community_board','attendance_tracker','outreach_planner','content_calendar','booking_calendar','community_connect','alert_system','report_generator'], moneyFlow: 'Community offerings → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'minister', name: 'Christian Minister', desc: 'Leads Christian worship, pastoral counselling, and community development through the church', tools: ['community_board','community_connect','billing_dashboard','attendance_tracker','outreach_planner','content_calendar','impact_tracker','alert_system'], moneyFlow: 'Tithes and offerings → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'traditional_priest', name: 'Traditional Priest', desc: 'Practices African traditional spirituality, preserving ancestral knowledge and conducting ceremonies', tools: ['community_board','conservation_log','content_calendar','recording_vault','community_connect','document_vault','alert_system','outreach_planner'], moneyFlow: 'Ceremony fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'spiritual_counselor', name: 'Spiritual Counselor', desc: 'Provides faith-based counselling and emotional support to individuals and families in crisis', tools: ['appointment_book','client_tracker','report_generator','session_log','community_board','community_connect','content_calendar','billing_dashboard'], moneyFlow: 'Session fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'spiritual_healer', name: 'Spiritual Healer', desc: 'Offers traditional and spiritual healing services using herbs, prayer, and ancestral guidance', tools: ['inventory_tracker','quick_invoice','review_tracker','appointment_book','client_tracker','social_shop','product_listing','community_board'], moneyFlow: 'Healing fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'meditation_guide', name: 'Meditation Guide', desc: 'Teaches mindfulness, meditation, and spiritual practices across African and global traditions', tools: ['appointment_book','content_calendar','payment_link','review_tracker','community_board','analytics_report','portfolio_vault','social_shop'], moneyFlow: 'Session fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'charity_worker', name: 'Charity Worker', desc: 'Runs faith-based charitable programmes, fundraises, and delivers aid to vulnerable communities', tools: ['grant_tracker','impact_tracker','campaign_manager','community_connect','community_board','outreach_planner','report_generator','donation_tracker'], moneyFlow: 'Grants and donations → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'funeral_director', name: 'Funeral Director', desc: 'Manages funeral services, burial coordination, and grief support within cultural and religious traditions', tools: ['appointment_book','document_vault','billing_dashboard','client_tracker','inventory_tracker','compliance_checker','quick_invoice','route_planner'], moneyFlow: 'Service fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
]
