import type { RoleDefinition } from '../role-registry'

export const SPORTS_ROLES: RoleDefinition[] = [
  { key: 'footballer', name: 'Footballer / Team Sport Athlete', desc: 'Competes professionally or semi-professionally in football and team sports, building a personal brand', tools: ['content_calendar','portfolio_vault','payment_link','analytics_report','community_board','social_shop','booking_calendar','review_tracker'], moneyFlow: 'Sponsorship → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'creative' },
  { key: 'track_athlete', name: 'Track & Field Athlete', desc: 'Trains and competes in running, jumping, and throwing events, managing training and sponsorships', tools: ['daily_target_tracker','portfolio_vault','social_shop','analytics_report','content_calendar','community_board','payment_link','review_tracker'], moneyFlow: 'Prize money → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'creative' },
  { key: 'coach', name: 'Coach / Trainer', desc: 'Develops athlete performance through training programmes, tactical coaching, and physical conditioning', tools: ['attendance_tracker','client_tracker','report_generator','daily_target_tracker','analytics_report','community_board','appointment_book','billing_dashboard'], moneyFlow: 'Coaching fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'referee', name: 'Referee / Sports Official', desc: 'Enforces rules and maintains fair play in competitive sports events at all levels', tools: ['attendance_tracker','compliance_checker','alert_system','report_generator','daily_target_tracker','community_board','analytics_report','document_vault'], moneyFlow: 'Match fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'community' },
  { key: 'gym_owner', name: 'Gym / Sports Facility Owner', desc: 'Operates fitness centres, sports halls, and training facilities, managing memberships and maintenance', tools: ['booking_calendar','staff_manager','pos_dashboard','maintenance_log','analytics_report','review_tracker','community_board','daily_settlement'], moneyFlow: 'Membership fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'sports_scout', name: 'Sports Scout / Agent', desc: 'Identifies talent, negotiates contracts, and manages athlete careers across African and international markets', tools: ['client_tracker','portfolio_vault','analytics_report','report_generator','community_board','outreach_planner','booking_calendar','payment_link'], moneyFlow: 'Agency commissions → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'esports', name: 'Esports Player', desc: 'Competes in competitive gaming tournaments, builds streaming audiences, and monetises gaming skills', tools: ['tournament_manager','analytics_report','community_board','payment_link','content_calendar','portfolio_vault','social_shop','review_tracker'], moneyFlow: 'Tournament prizes → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'creative' },
  { key: 'sports_journalist', name: 'Sports Journalist', desc: 'Reports on sports events, athlete stories, and sporting culture for broadcast, print, and digital media', tools: ['content_calendar','article_vault','analytics_report','publication_vault','community_board','media_list','outreach_planner','report_generator'], moneyFlow: 'Story fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'creative' },
]
