import type { RoleDefinition } from '../role-registry'

export const TECHNOLOGY_ROLES: RoleDefinition[] = [
  { key: 'developer', name: 'Software Engineer', desc: 'Designs, builds, and maintains software applications, managing code projects, tickets, and deployment pipelines.', tools: ["code_project","api_tester","ticket_system","debug_log","audit_log","project_tracker","analytics_report","community_board"], moneyFlow: 'Project and contract fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'data_scientist', name: 'AI / Data Scientist', desc: 'Builds machine learning models and data pipelines, publishing research and contributing to open-source communities.', tools: ["dataset_vault","analytics_report","publication_vault","code_project","project_tracker","community_board","grant_tracker","report_generator"], moneyFlow: 'Consulting and grant fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'cybersecurity', name: 'Cybersecurity Analyst', desc: 'Monitors, investigates, and responds to security threats, ensuring systems remain compliant and resilient.', tools: ["remote_access_tool","backup_monitor","alert_system","audit_log","compliance_checker","incident_log","technical_docs","report_generator"], moneyFlow: 'Security retainer fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'network_engineer', name: 'Network Engineer', desc: 'Designs and maintains network infrastructure, resolving connectivity issues and ensuring uptime and compliance.', tools: ["infrastructure_log","ticket_system","maintenance_log","technical_docs","alert_system","compliance_checker","analytics_report","report_generator"], moneyFlow: 'Infrastructure contract fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'mobile_dev', name: 'Mobile Developer', desc: 'Builds and deploys mobile applications, managing releases, debugging, and community feedback cycles.', tools: ["code_project","app_deploy_tracker","api_tester","debug_log","review_tracker","analytics_report","community_board","portfolio_vault"], moneyFlow: 'App and contract fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'cloud_engineer', name: 'Cloud Engineer', desc: 'Manages cloud infrastructure, monitoring costs, backups, uptime, and security compliance across hosted services.', tools: ["hosting_tracker","backup_monitor","infrastructure_log","cost_dashboard","alert_system","technical_docs","analytics_report","compliance_checker"], moneyFlow: 'Cloud management fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'ux_designer', name: 'UX Designer', desc: 'Creates user-centred digital experiences, managing design briefs, client feedback, and a showcase portfolio.', tools: ["design_brief","portfolio_vault","client_tracker","review_tracker","content_calendar","social_shop","analytics_report","community_board"], moneyFlow: 'Design project fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'creative' },
  { key: 'tech_support', name: 'Tech Support Specialist', desc: 'Resolves hardware and software issues for clients, managing tickets, remote sessions, and repair queues.', tools: ["ticket_system","remote_access_tool","repair_queue","knowledge_base","alert_system","client_tracker","daily_target_tracker","report_generator"], moneyFlow: 'Support service fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
]
