import type { RoleDefinition } from '../role-registry'

export const TRANSPORT_ROLES: RoleDefinition[] = [
  { key: 'road_driver', name: 'Road Driver', desc: 'Operates trucks, buses, and goods vehicles on intercity and rural routes across Africa', tools: ['daily_route','fuel_tracker','route_planner','safety_checklist','delivery_tracker','community_board','quick_invoice','alert_system'], moneyFlow: 'Per delivery → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'delivery' },
  { key: 'logistics_coordinator', name: 'Logistics Coordinator', desc: 'Manages dispatch, routing, and last-mile delivery coordination for goods across supply chains', tools: ['runner_dispatch','delivery_tracker','collection_tracker','bulk_order_manager','route_planner','client_tracker','analytics_report','daily_settlement'], moneyFlow: 'Coordination fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'vehicle_mechanic', name: 'Vehicle Mechanic', desc: 'Diagnoses and repairs cars, trucks, and motorcycles, managing parts and workshop operations', tools: ['repair_queue','parts_finder','maintenance_log','safety_checklist','work_order','client_tracker','quick_invoice','review_tracker'], moneyFlow: 'Repair fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'aviation_professional', name: 'Aviation Professional', desc: 'Works in commercial aviation — pilot, air traffic controller, aircraft mechanic, or airport crew', tools: ['flight_log','safety_checklist','technical_docs','compliance_checker','maintenance_log','alert_system','document_vault','report_generator'], moneyFlow: 'Professional fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'professional' },
  { key: 'marine_crew', name: 'Marine Crew', desc: 'Operates ferry, fishing vessel, or cargo ship on lakes, rivers, and coastal waters', tools: ['route_planner','safety_checklist','maintenance_log','fuel_tracker','weather_alert','cargo_log','quick_invoice','community_board'], moneyFlow: 'Voyage earnings → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'railway_crew', name: 'Railway Crew', desc: 'Operates, maintains, and manages trains, stations, and rail infrastructure across the continent', tools: ['maintenance_log','safety_checklist','alert_system','route_planner','daily_target_tracker','fuel_tracker','compliance_checker','report_generator'], moneyFlow: 'Service fees → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
  { key: 'boda_boda', name: 'Motorcycle Taxi (Boda-Boda)', desc: 'Provides last-mile transport via motorcycle, handling passengers and small parcel deliveries', tools: ['daily_route','mobile_payment_collect','fuel_tracker','community_board','safety_checklist','quick_invoice','review_tracker','route_planner'], moneyFlow: 'Ride earnings → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'delivery' },
  { key: 'fleet_manager_role', name: 'Fleet Manager', desc: 'Oversees vehicle fleet operations, driver management, compliance, and performance tracking', tools: ['fuel_tracker','staff_manager','daily_settlement','maintenance_log','analytics_report','route_planner','compliance_checker','vehicle_log'], moneyFlow: 'Management salary → Cowrie wallet.', crestPath: 'Complete 100 sessions. Maintain 4.5+ rating.', businessSessionType: 'service' },
]
